### ISSUE TITLE
Installing SHTools in Windows7

### ISSUE THREAD

**Issue by vaghaninirav10** [SHTOOLS/SHTOOLS#10]
Hi how to install SHTools on Windows.

**Comment by MarkWieczorek** [comment]
I am going to close this issue. 

In general, you need to start with a fortran 95 compiler, and have FFTW and LAPACK installed. If you want to use python, this will have to be installed as well.

If you meet these conditions, and if you are still having problem, please open a new issue with more details about your system configuration.
