### ISSUE TITLE
Fail to install Pyshtool on Ubuntu system

### ISSUE THREAD

**Issue by jijinzhu** [SHTOOLS/SHTOOLS#106]
When I install the pyshtools by pip, displayed: 
Importerror: No module named numpy.distutils.core
....................................................................................
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Y6T9Cz-build/

How to solve this problem?

Thank you very much!
Jinzhu

**Comment by jijinzhu** [comment]
Detail information:

Processing / media/uersloctaion/SHTOOLS-4.1/SHTOOL-4.1
       Complete output from command python setup.py egg_info:
       File "<string>", line 1, in <module>
       File"/tmp/pip-y3NMb_-build/setup.py", line 17, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-y3NMb_-build/

**Comment by jijinzhu** [comment]
Processing /media/jinzhu/Ubuntu_localdisk/SHTOOLS-4.1/SHTOOLS-4.1
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-y3NMb_-build/setup.py", line 17, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-y3NMb_-build/

**Comment by jijinzhu** [comment]
Detail problem displaying:
Processing /media/jinzhu/Ubuntu_localdisk/SHTOOLS-4.1/SHTOOLS-4.1
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-y3NMb_-build/setup.py", line 17, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-y3NMb_-build/


How to solve this problem?
Thank you very much!
Jinzhu

**Comment by MarkWieczorek** [comment]
Could you let me know exactly how you are trying to install shtools? Even though I just tagged v4.1 today, I did not upload it yet to pypi.

**Comment by jijinzhu** [comment]
I used the pip install shtools on Ubtuntu 16.04. I also tried to install v4.0 with the same problem.

**Comment by MarkWieczorek** [comment]
Could you try installing numpy? Also, perhaps doing 
````
pip install -v . 
````
will give you more info.

**Comment by jijinzhu** [comment]
I have installed the numpy, but Failed building wheel for pyshtools.

jijinzhu@ubuntu:/media/jijinzhu/Ubuntu_localdisk/SHTOOLS-4.0$ pip3 install .
Processing /media/jijinzhu/Ubuntu_localdisk/SHTOOLS-4.0
Building wheels for collected packages: pyshtools
  Running setup.py bdist_wheel for pyshtools ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-s09e6tb4-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpfmxb8lnupip-wheel- --python-tag cp35:
  no pandoc installed. Careful, pypi description will not be formatted correctly.
  INSTALLING SHTOOLS 4.0
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize IntelFCompiler
  Could not locate executable ifort
  Could not locate executable ifc
  customize LaheyFCompiler
  Could not locate executable lf95
  customize PGroupFCompiler
  Could not locate executable pgfortran
  customize AbsoftFCompiler
  Could not locate executable f90
  Could not locate executable f77
  customize NAGFCompiler
  customize VastFCompiler
  customize CompaqFCompiler
  Could not locate executable fort
  customize IntelItaniumFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize IntelEM64TFCompiler
  customize GnuFCompiler
  Could not locate executable g77
  customize G95FCompiler
  Could not locate executable g95
  customize PathScaleFCompiler
  Could not locate executable pathf95
  customize Gnu95FCompiler
  customize IntelFCompiler
  customize LaheyFCompiler
  customize PGroupFCompiler
  customize AbsoftFCompiler
  customize NAGFCompiler
  customize VastFCompiler
  customize CompaqFCompiler
  customize IntelItaniumFCompiler
  customize IntelEM64TFCompiler
  customize GnuFCompiler
  customize G95FCompiler
  customize PathScaleFCompiler
  searching SHTOOLS in: build/temp.linux-x86_64-3.5
  non-existing path in '': 'build/temp.linux-x86_64-3.5'
  non-existing path in '': 'build/temp.linux-x86_64-3.5'
  running bdist_wheel
  running build
  ---- BUILDING ----
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building library "SHTOOLS" sources
  building extension "pyshtools._SHTOOLS" sources
  f2py options: ['--quiet', '--quiet']
    adding 'build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/fortranobject.c' to sources.
    adding 'build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src' to include_dirs.
    adding 'build/src.linux-x86_64-3.5/src/_SHTOOLS-f2pywrappers.f' to sources.
  building extension "pyshtools._constant" sources
  f2py options: ['--quiet']
    adding 'build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/pyshtools/fortranobject.c' to sources.
    adding 'build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/pyshtools' to include_dirs.
    adding 'build/src.linux-x86_64-3.5/pyshtools/_constant-f2pywrappers2.f90' to sources.
  build_src: building npy-pkg config files
  running build_py
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/pyshtools
  copying pyshtools/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools
  copying pyshtools/make_docs.py -> build/lib.linux-x86_64-3.5/pyshtools
  creating build/lib.linux-x86_64-3.5/pyshtools/shclasses
  copying pyshtools/shclasses/shwindow.py -> build/lib.linux-x86_64-3.5/pyshtools/shclasses
  copying pyshtools/shclasses/shcoeffsgrid.py -> build/lib.linux-x86_64-3.5/pyshtools/shclasses
  copying pyshtools/shclasses/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/shclasses
  creating build/lib.linux-x86_64-3.5/pyshtools/constant
  copying pyshtools/constant/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/constant
  creating build/lib.linux-x86_64-3.5/pyshtools/utils
  copying pyshtools/utils/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/utils
  copying pyshtools/utils/datetime.py -> build/lib.linux-x86_64-3.5/pyshtools/utils
  creating build/lib.linux-x86_64-3.5/pyshtools/gravmag
  copying pyshtools/gravmag/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/gravmag
  creating build/lib.linux-x86_64-3.5/pyshtools/shtools
  copying pyshtools/shtools/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/shtools
  creating build/lib.linux-x86_64-3.5/pyshtools/expand
  copying pyshtools/expand/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/expand
  creating build/lib.linux-x86_64-3.5/pyshtools/legendre
  copying pyshtools/legendre/plm_index.py -> build/lib.linux-x86_64-3.5/pyshtools/legendre
  copying pyshtools/legendre/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/legendre
  creating build/lib.linux-x86_64-3.5/pyshtools/spectralanalysis
  copying pyshtools/spectralanalysis/spectrum.py -> build/lib.linux-x86_64-3.5/pyshtools/spectralanalysis
  copying pyshtools/spectralanalysis/cross_spectrum.py -> build/lib.linux-x86_64-3.5/pyshtools/spectralanalysis
  copying pyshtools/spectralanalysis/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/spectralanalysis
  creating build/lib.linux-x86_64-3.5/pyshtools/shio
  copying pyshtools/shio/icgem.py -> build/lib.linux-x86_64-3.5/pyshtools/shio
  copying pyshtools/shio/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/shio
  copying pyshtools/shio/yilm_index_vector.py -> build/lib.linux-x86_64-3.5/pyshtools/shio
  creating build/lib.linux-x86_64-3.5/pyshtools/rotate
  copying pyshtools/rotate/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/rotate
  running build_clib
  customize UnixCCompiler
  customize UnixCCompiler using build_clib
  customize Gnu95FCompiler
  customize IntelFCompiler
  customize LaheyFCompiler
  customize PGroupFCompiler
  customize AbsoftFCompiler
  customize NAGFCompiler
  customize VastFCompiler
  customize CompaqFCompiler
  customize IntelItaniumFCompiler
  customize IntelEM64TFCompiler
  customize GnuFCompiler
  customize G95FCompiler
  customize PathScaleFCompiler
  don't know how to compile Fortran code on platform 'posix'
  building 'SHTOOLS' library
  error: library SHTOOLS has Fortran sources but no Fortran compiler found
  
  ----------------------------------------
  Failed building wheel for pyshtools
  Running setup.py clean for pyshtools
Failed to build pyshtools
Installing collected packages: pyshtools
  Running setup.py install for pyshtools ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-s09e6tb4-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-m6yoaist-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    no pandoc installed. Careful, pypi description will not be formatted correctly.
    INSTALLING SHTOOLS 4.0
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize IntelFCompiler
    Could not locate executable ifort
    Could not locate executable ifc
    customize LaheyFCompiler
    Could not locate executable lf95
    customize PGroupFCompiler
    Could not locate executable pgfortran
    customize AbsoftFCompiler
    Could not locate executable f90
    Could not locate executable f77
    customize NAGFCompiler
    customize VastFCompiler
    customize CompaqFCompiler
    Could not locate executable fort
    customize IntelItaniumFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize IntelEM64TFCompiler
    customize GnuFCompiler
    Could not locate executable g77
    customize G95FCompiler
    Could not locate executable g95
    customize PathScaleFCompiler
    Could not locate executable pathf95
    customize Gnu95FCompiler
    customize IntelFCompiler
    customize LaheyFCompiler
    customize PGroupFCompiler
    customize AbsoftFCompiler
    customize NAGFCompiler
    customize VastFCompiler
    customize CompaqFCompiler
    customize IntelItaniumFCompiler
    customize IntelEM64TFCompiler
    customize GnuFCompiler
    customize G95FCompiler
    customize PathScaleFCompiler
    searching SHTOOLS in: build/temp.linux-x86_64-3.5
    non-existing path in '': 'build/temp.linux-x86_64-3.5'
    non-existing path in '': 'build/temp.linux-x86_64-3.5'
    running install
    ---- CUSTOM INSTALL ----
    running build
    ---- BUILDING ----
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building library "SHTOOLS" sources
    building extension "pyshtools._SHTOOLS" sources
    f2py options: ['--quiet', '--quiet']
      adding 'build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/fortranobject.c' to sources.
      adding 'build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src' to include_dirs.
      adding 'build/src.linux-x86_64-3.5/src/_SHTOOLS-f2pywrappers.f' to sources.
    building extension "pyshtools._constant" sources
    f2py options: ['--quiet']
      adding 'build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/pyshtools/fortranobject.c' to sources.
      adding 'build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/pyshtools' to include_dirs.
      adding 'build/src.linux-x86_64-3.5/pyshtools/_constant-f2pywrappers2.f90' to sources.
    build_src: building npy-pkg config files
    running build_py
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pyshtools
    copying pyshtools/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools
    copying pyshtools/make_docs.py -> build/lib.linux-x86_64-3.5/pyshtools
    creating build/lib.linux-x86_64-3.5/pyshtools/shclasses
    copying pyshtools/shclasses/shwindow.py -> build/lib.linux-x86_64-3.5/pyshtools/shclasses
    copying pyshtools/shclasses/shcoeffsgrid.py -> build/lib.linux-x86_64-3.5/pyshtools/shclasses
    copying pyshtools/shclasses/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/shclasses
    creating build/lib.linux-x86_64-3.5/pyshtools/constant
    copying pyshtools/constant/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/constant
    creating build/lib.linux-x86_64-3.5/pyshtools/utils
    copying pyshtools/utils/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/utils
    copying pyshtools/utils/datetime.py -> build/lib.linux-x86_64-3.5/pyshtools/utils
    creating build/lib.linux-x86_64-3.5/pyshtools/gravmag
    copying pyshtools/gravmag/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/gravmag
    creating build/lib.linux-x86_64-3.5/pyshtools/shtools
    copying pyshtools/shtools/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/shtools
    creating build/lib.linux-x86_64-3.5/pyshtools/expand
    copying pyshtools/expand/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/expand
    creating build/lib.linux-x86_64-3.5/pyshtools/legendre
    copying pyshtools/legendre/plm_index.py -> build/lib.linux-x86_64-3.5/pyshtools/legendre
    copying pyshtools/legendre/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/legendre
    creating build/lib.linux-x86_64-3.5/pyshtools/spectralanalysis
    copying pyshtools/spectralanalysis/spectrum.py -> build/lib.linux-x86_64-3.5/pyshtools/spectralanalysis
    copying pyshtools/spectralanalysis/cross_spectrum.py -> build/lib.linux-x86_64-3.5/pyshtools/spectralanalysis
    copying pyshtools/spectralanalysis/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/spectralanalysis
    creating build/lib.linux-x86_64-3.5/pyshtools/shio
    copying pyshtools/shio/icgem.py -> build/lib.linux-x86_64-3.5/pyshtools/shio
    copying pyshtools/shio/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/shio
    copying pyshtools/shio/yilm_index_vector.py -> build/lib.linux-x86_64-3.5/pyshtools/shio
    creating build/lib.linux-x86_64-3.5/pyshtools/rotate
    copying pyshtools/rotate/__init__.py -> build/lib.linux-x86_64-3.5/pyshtools/rotate
    running build_clib
    customize UnixCCompiler
    customize UnixCCompiler using build_clib
    customize Gnu95FCompiler
    customize IntelFCompiler
    customize LaheyFCompiler
    customize PGroupFCompiler
    customize AbsoftFCompiler
    customize NAGFCompiler
    customize VastFCompiler
    customize CompaqFCompiler
    customize IntelItaniumFCompiler
    customize IntelEM64TFCompiler
    customize GnuFCompiler
    customize G95FCompiler
    customize PathScaleFCompiler
    don't know how to compile Fortran code on platform 'posix'
    building 'SHTOOLS' library
    error: library SHTOOLS has Fortran sources but no Fortran compiler found
    
    ----------------------------------------

**Comment by MarkWieczorek** [comment]
It looks like this is your problem 

````
error: library SHTOOLS has Fortran sources but no Fortran compiler found
````
Do you have a fortran compiler installed?

**Comment by jijinzhu** [comment]
I installed a Fortran compiler, and re-installed Python and Numpy using Miniconda, and that's all working. Running "pip install pyshtools" also works, and says pyshtools (4.1) is successfully installed, in both Python 3 and Python 2 environments. Downloading and installing pyshtools 4.0 works too, by running "pip install ." in the same folder as setup.py. No matter how it's installed, though, or which version is installed, trying to import pyshtools now gives me this error:

``
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-500780b062bd> in <module>()
----> 1 import pyshtools

/media/jijinzhu/Ubuntu_localdisk/SHTOOLS-4.0/pyshtools/__init__.py in <module>()
     45 
     46 # ---- Import shtools subpackages ----
---> 47 from . import shtools
     48 from . import constant
     49 from . import shclasses

/media/jijinzhu/Ubuntu_localdisk/SHTOOLS-4.0/pyshtools/shtools/__init__.py in <module>()
     13 
     14 # legendre
---> 15 from .._SHTOOLS import PlmBar
     16 from .._SHTOOLS import PlmBar_d1
     17 from .._SHTOOLS import PlBar

ModuleNotFoundError: No module named 'pyshtools._SHTOOLS'
``

**Comment by MarkWieczorek** [comment]
First, could you please make sure that you do a `pip uninstall pyshtools` before installing each new version. It is possible that you have a system wide pyshtools installed that is conflicting with the local one you downloaded.

Then could you go into the folder `pyshtools` (found in the same directory as the setup.py file), and see if you have any files with names like this? 

`_SHTOOLS.cpython-36m-darwin.so`
`_constant.cpython-36m-darwin.so`

Also, could you use `pip install -v .` and see if you get any errors when compiling the fortran code?

Lastl

**Comment by jijinzhu** [comment]
Thanks for your help! I had a copy of pyshtools that I'd installed with the system pip3 - removing that solved the issue, and now pyshtools seems to be working properly!
