### ISSUE TITLE
ImportError: [...] libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/lib/liblapack.so.3gf)

### ISSUE THREAD

**Issue by MMesch** [SHTOOLS/SHTOOLS#11]
This Error comes from a bug in anaconda python and scipy > 0.16 . You can fix it by typing:

    conda install scipy=0.16

Click [here](https://github.com/ContinuumIO/anaconda-issues/issues/686) for further information

**Comment by scienceopen** [comment]
Suggest Closing this issue as this bug was resolved with new Anaconda version

**Comment by MarkWieczorek** [comment]
Please reopen this issue if this bug reappears when using the most recent version of anaconda.
