### ISSUE TITLE
How to evaluate a list of arbitrary points on the sphere from SH coeffs?

### ISSUE THREAD

**Issue by yfwang09** [SHTOOLS/SHTOOLS#115]
Dear Mark,

I am using SHTOOLS for analytically solving elasticity problems with spherical boundary values. Now I developed a solution in terms of a SHcoeffs matrix, and I want to evaluate this coefficient matrix on a list of arbitrary points (theta, phi). The coefficient matrix has around 800 non-zero modes (lmax=30).
I notice that there is a MakeGridPoint function that can evaluate a single point on the sphere. If I evaluate many points (say 500) through for loop, it will be very slow (about 1s/point). The expand method in SHCoeffs class is also using this implementation. However, considering multiple points of the DH/GLQ grid, SHCoeffs.expand also takes about 1s for evaluate the grid.
I was wondering is there a way that I can evaluate a list of arbitrary points from a SH coefficient matrix fastly? Thanks!

Best,
Yifan

**Comment by MarkWieczorek** [comment]
Sorry, but there is nothing more that can be done. Either you evaluate the function point by point, one at a time, or you evaluate the function everywhere on a regular grid using ffts over latitude bands. If all your points were at the same latitude, then it might be possible speed this up.

**Comment by ioshchepkov** [comment]
Basically, you can also try to use simple parallelization if you have a stand-alone script for one point and you have a multi-processor system. For example, with [GNU/Parallel](https://www.gnu.org/software/parallel/).
