### ISSUE TITLE
A documentation/code comment error 

### ISSUE THREAD

**Issue by dogod621** [SHTOOLS/SHTOOLS#122]
At: 
https://shtools.oca.eu/shtools/pyshrotaterealcoef.html
https://shtools.oca.eu/shtools/pyshrotatecoef.html
src/fdoc/shrotatecoef.md
src/fdoc/shrotaterealcoef.md
pyshtools/shclasses/shcoeffsgrid.py line 872

Error:
    alpha_y=alpha_x-pi/2, beta_x=beta_y, and gamma_y=gamma_x+pi/2.
My fix:
    alpha_y=alpha_x-pi/2, beta_y=-beta_x, and gamma_y=gamma_x+pi/2.

Is my version correct?
I check the Euler angles ZYZ and ZXZ matrix from wiki, 
and the code in src/SHRotateCoef.f95 line 110
```
    alpha = alpha - pi2
    gamma = gamma + pi2
    beta = -beta
```

**Comment by MarkWieczorek** [comment]
I think that this is correct. The documentation says

```
Note that this routine uses the “y convention”, where the second rotation is with respect to the new y axis. If alpha, beta, and gamma were originally defined in terms of the “x convention”, where the second rotation was with respect to the new x axis, the Euler angles according to the y convention would be alpha_y=alpha_x-pi/2, beta_x=beta_y, and gamma_y=gamma_x+pi/2.
```

Now, according to http://mathworld.wolfram.com/EulerAngles.html, the conversion from x to y convention is the same as in the above documentation. Nevertheless, I acknowledge that these definitions are very confusing, so I could be wrong.

**Comment by dogod621** [comment]
You are right, I make mistake when calculate ZYZ and ZXZ matrix.
Sorry for I didn't check the calculation twice.

So rotate function in  SHCoeffs class use euler angle ZYZ as parameters.
and code in src/SHRotateCoef.f95 line 110 is not performing x-convention to y-convention, but something else.
```
    alpha = alpha - pi2
    gamma = gamma + pi2
    beta = -beta
```

if that is true.
the code comment in https://shtools.oca.eu/shtools/pages/mydoc/notebooks/tutorial_3.html is wrong.
```
...
alpha = 0.  # around z-axis
beta = 90.  # around x-axis (lon=0)
gamma = 10.  # around z-axis again

coeffs_l5m0_rot = coeffs_l5m0.rotate(alpha, beta, gamma, degrees=True)
...
```

**Comment by MarkWieczorek** [comment]
Could you try doing a calculating to see if you get the result you expect? I did not write the rotation routine, and it is quite possible that the snippet of code you extracted from within the routine is correct.

**Comment by MarkWieczorek** [comment]
I figured it out. All of the documentation for the functions is correct: SHTOOLS uses the y-convention, and the default is to rotate the coordinate system, not the physical body. However, the description in the tutorial is indeed wrong. I have updated this with the following:

> The rotations are specified by the three Euler angles alpha, beta, and gamma. There are several different conventions for specifying these angles, and they can either provide the angles for rotating the physical body or coordinate system. Please read the documentation of this method carefully before proceeding! SHTOOLS uses the "y-convention" where the three angles correspond to (in this order):
>
> Rotation about the z axis by alpha,
> Rotation about the new y axis by beta,
> Rotation about the new z axis by gamma.
>
> By using the angles alpha, beta, and gamma as is, the coordinate system will be rotated without rotation of the physical body. To instead rotate the physical body, and not the coordinate system, you would specify the angles -gamma, -beta, and -alpha.

Then, the example is 
~~~~
alpha = 30.  # rotation around the initial z-axis
beta = 90.  # rotation aroung the new y-axis
gamma = 0.  # rotation around the new z-axis

coeffs_l5m0_rot = coeffs_l5m0.rotate(-gamma, -beta, -alpha, degrees=True)
~~~~

I hope this clears things up. I really hate rotation angles...

**Comment by dogod621** [comment]
Thanks man, i hate rotation angles too
