### ISSUE TITLE
A few mistakes in the Complex spherical harmonics document

### ISSUE THREAD

**Issue by lcx366** [SHTOOLS/SHTOOLS#125]
May be a few mistakes are in the Complex spherical harmonics document. The first one is  "where 
δ_{ij} is the Kronecker delta function", however no δ_{ij} is appeared in the formula (3), although the formula (3) is correct. The second one seems to be a symbol mistake. In formula (14), f_{lm} should be f_{l}^{m}.

**Comment by MarkWieczorek** [comment]
Thanks, I just fixed these in the develop branch.
