### ISSUE TITLE
A bug in shcoeffsgrid.py line 1396

### ISSUE THREAD

**Issue by dogod621** [SHTOOLS/SHTOOLS#133]
Hi,

in shcoeffsgrid.py line 1396:
```
...
if self.normalization != '4pi' or self.csphase != 1:
            temp = SHCoeffs.from_array(coeffs, kind='real')
...
```

but SHCoeffs.from_array function do not use "kind" parameter.
the from_array function automatically figure it out by coeffs's type is complex or not.

**Comment by MarkWieczorek** [comment]
Thanks. I just fixed this in the `convert` pull request that will be merged into the develop branch by the end of next week. A new release with all these updates should be about one month later.
