### ISSUE TITLE
Weird normalization conversion in _to_array function at shcoeffsgrid.py 

### ISSUE THREAD

**Issue by dogod621** [SHTOOLS/SHTOOLS#134]
Hi,

It seems all the normalization conversions in _to_array function are reversed.
Am I misunderstanding the function's purpose?

The SH coeff can be compute by:
<img src="https://user-images.githubusercontent.com/6807005/38193162-1c964b0c-36a3-11e8-832e-5efc3fc7d7c6.png" width="200" height="50" />

And if we scale Y_lm(w) by **X**, the SH coeff will be scaled by **X** too:
<img src="https://user-images.githubusercontent.com/6807005/38193255-b260accc-36a3-11e8-9bf6-917d06ef4a8f.png" width="250" height="50" />

Take normalization **'4pi'** to **'ortho'** for example, by the definition in:
https://shtools.oca.eu/shtools/real-spherical-harmonics.html#schmidt-semi-normalized

The **X** will be **1/(4*pi)^0.5**, and the output  SH coeff should been scaled by **1/(4*pi)^0.5** too.

But in shcoeffsgrid.py  line 1358:
```
elif self.normalization == '4pi' and output_normalization == 'ortho':
            coeffs *= _np.sqrt(4.0 * _np.pi)
```

it scale **(4*pi)^0.5** !!
If I am right,  then all of the normalization conversions have the same problem.

**Comment by dogod621** [comment]
Oh, the other normalization sh are not othonormal, so the equation is wrong.....

**Comment by MarkWieczorek** [comment]
The general approach I use is that the function in the space domain is independent of the chosen normalization, so

c_{lm}^{(4\pi)} Y_{lm}^^{(4\pi)} = c_{lm}^{(ortho)} Y_{lm}^^{(ortho)}

This gives

c_{lm}^{(4\pi)} = c_{lm}^{(ortho)} \(P_{lm}^^{(ortho)} / P_{lm}^^{(4\pi)}  \)

Cheers,
