### ISSUE TITLE
Installation Issue: Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Srwood93** [SHTOOLS/SHTOOLS#14]
I was recently able to import SHTOOLS into python (Canopy) until I did a system update today and now I cannot import the package at all and receive an import error: "Version 'GFORTRAN_1.4' not found". I'm wondering if it has to do with an update to libgfortran [(https://github.com/ContinuumIO/anaconda-issues/issues/686)]?

I tried to uninstall SHTOOLS and reinstall it but I get the same import error when running `make`

`Traceback (most recent call last):
  File "./pyshtools/make_docs.py", line 14, in <module>
    import _SHTOOLS
ImportError: /home/user/Enthought/Canopy_64bit/User/bin/../lib/libgfortran.so.3: version GFORTRAN_1.4 not found (required by /home/user/Documents/SHTOOLS-3.1/pyshtools/_SHTOOLS.so)
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 1`

Any help on this issue would be greatly appreciated.

**Comment by MarkWieczorek** [comment]
Were you even able to resolve this issue? I would suggest performing a ```make clean```. Also, could you please check that gfortran is in your search path?

**Comment by Srwood93** [comment]
Hi-


I ended up just downloading anaconda and spyder and that seemed to resolve the issue.


I'm sure the issue was probably gfortran not being in my search path, but I couldn't figure out how to fix that.


Thank you for checking in.


________________________________
