### ISSUE TITLE
issues with SHExpandLSQ

### ISSUE THREAD

**Issue by yfwang09** [SHTOOLS/SHTOOLS#140]
Dear Mark,

I was trying to use SHExpandLSQ to expand a function on irregular mesh points. I have d, lat, lon all float ndarrays with size (4256,), but the function ends up with an error: 
(lat_d0==d_d0 && lon_d0==d_d0) failed for hidden nmax: SHExpandLSQ:nmax=4256

This issue can also be reproduced for the following code:

import pyshtools
import numpy as np
d = np.zeros(20)
lat = 90-np.random.rand(20)*180
lon = np.random.rand(20)*360
cilm, chi2 = pyshtools.expand.SHExpandLSQ(d,lat,lon,5)

and the error shows up:
>Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
>  File "/usr/local/lib/python3.5/dist-packages/pyshtools/shtools/__init__.py", line 198, in wrapped_func
>    returned_values = func(*args, **kwargs)
>_SHTOOLS.error: (lat_d0==d_d0 && lon_d0==d_d0) failed for hidden nmax: SHExpandLSQ:nmax=20

I am using SHTOOLS 4.0 installed using pip on Ubuntu 16.04LTS with python 3.5.

I do not quite understand the python-fortran interface so I am not sure if it is a bug or I did not use it correctly. Would you mind helping me locate the problem?

Thank you!

**Comment by MarkWieczorek** [comment]
I just tried this on my installation, and it worked without any problems. Could you try installing the latest version (4.1) ? If this doesn't work, could you try installing from source (i.e., not using the binary wheel)?

In any case, the problem appears to be coming from the file pyshtools.pyf in the line 

~~~~
            integer intent(hide),check(lat_d0==d_d0 && lon_d0==d_d0) :: nmax = d_d0
~~~~
This is just checking that the dimension of all the input arrays are the same.

**Comment by yfwang09** [comment]
Thank you for your reply! This issue is resolved by re-installing from the source.
