### ISSUE TITLE
Documentation error for pyshtools.SHAdmitCorr?

### ISSUE THREAD

**Issue by andreww** [SHTOOLS/SHTOOLS#15]
The function signature for  `pyshtools.SHAdmitCorr` in the [online documentation](http://shtools.ipgp.fr/www/man/python/pyshadmitcorr.html) differs from that in the example in `examples/python/GlobalSpectralAnalysis/SHRealSpectralAnalysis.py` with the returned values being `admit, error, corr` and `admit, corr, dadmit`, respectively.

As far as I can tell (from testing with some coefficients where I think I know what the correlation should be) the order of the returned values in the example is correct. It would be useful if somebody could confirm this, and if I'm correct the documentation should be updated. 

These arguments are also switched in `src/pyshtools.pyf` and `src/PythonWrapper.f95`, I suppose f2py only cares about the order of the arguments so the fortran 'wins'?

**Comment by andreww** [comment]
I think there is also a problem with `MakeGridPoint`. As `lmax` is an optional argument it seems python treats this as a keyword argument and assumes it comes after the positional arguments. Thus [the documentation](http://shtools.ipgp.fr/www/man/python/pymakegridpoint.html) should list the arguments as:

    value = pyshtools.MakeGridPoint (cilm, lat, lon, [lmax, norm, csphase, dealloc])

not:

    value = pyshtools.MakeGridPoint (cilm, lmax, lat, lon, [norm, csphase, dealloc])

**Comment by MarkWieczorek** [comment]
Thanks for pointing these problems out!

First, the problem with SHAdmitCorr was fixed awhile back on the develop branch. I will push this to master sometime next week (or earlier). 

As for the documentation error, you are right. This will also be fixed.
