### ISSUE TITLE
projection onto a set of Slepian basis

### ISSUE THREAD

**Issue by lcx366** [SHTOOLS/SHTOOLS#154]
Dear Prof. Wieczorek

Can PyShtools provide a method to project a surface function onto a set of Slepian basis designed to capture an interested region? For example, we could use PyShtools to calculate a set of tapers $h_i(\theta,\phi)$ based on the best concentration within an interested region. Also we have a surface function $f(\theta,\phi)$, but how about the projection of $f(\theta,\phi)$ onto $h_i(\theta,\phi)$, satisfiying $$f(\theta,\phi) = \Sigma_i^N p_i h_i(\theta,\phi)$$, where $p_i$ is the corresponding coefficient, $N$ is the Shannon number.

Best regards

**Comment by MarkWieczorek** [comment]
This is implemented in the following pull request:

https://github.com/SHTOOLS/SHTOOLS/pull/169

I anticipate a new release at the end of the year.
