### ISSUE TITLE
Invalid output of the SHCoeffs.expand function

### ISSUE THREAD

**Issue by SivakSerg** [SHTOOLS/SHTOOLS#158]
The python3 code written down bellow calculates the spherical harmonics in two ways:
1. to use them from the scipy library
2. to use them from shtools.

The problem is in the following: the results of the calculations are not only different, the pyshtools result is inconsistent with basic properties of spherical harmonics - they should be zero for zero angles if their order is not zero itself, which is not the case.
Only the very first harmonic is right, but all the rest are failing.

Python 3 code:

```
import scipy

phi = 0.0
thetta = 0.0

Norder = 1

import pyshtools as psh

import scipy.special as sphSpec

for i in range(0, 4):
    customCoeffs = [0, 0, 0, 0]
    customCoeffs[i] = 1.0
    index = 0
    manualDecomposition = 0.0
    shcoeffs = psh.SHCoeffs.from_zeros(Norder, kind='complex', normalization='ortho')

    for l_order in range(0, Norder + 1):
        for m_order in range(-l_order, l_order + 1, 1):
            shcoeffs.set_coeffs(customCoeffs[index], l_order, m_order)
            manualDecomposition += customCoeffs[index] * sphSpec.sph_harm(m_order, l_order, thetta, phi)
            index = index + 1

    Phi = phi * 180 / scipy.pi
    Thetta = thetta * 180 / scipy.pi
    shToolsRes = shcoeffs.expand(lat=[phi], lon=[thetta])

    print(manualDecomposition)
    print(shToolsRes[0])
    print('\n')
```

**Comment by MarkWieczorek** [comment]
I think that you are confusing "colatitude" and "latitude": colatitude is 90-latitude, and if you fix this you get the same results as scipy. If you were to plot the harmonic in the space domain, this would have been obvious !

By the end of the day, I will add the option to use colatitude with the method expand.

**Comment by MarkWieczorek** [comment]
Here is the PR. I will merge this into `develop` later. This will be merged into master with a new release at the end of summer (~sept. 1).

https://github.com/SHTOOLS/SHTOOLS/pull/159

**Comment by SivakSerg** [comment]
Mark,

Thanks a lot. Your help is much appreciated.
