### ISSUE TITLE
Makefile - install-fortran broken - because of missing index.html and www directory

### ISSUE THREAD

**Issue by galitus** [SHTOOLS/SHTOOLS#160]
Hey,

i think, the Makefile needs to be modified because of the documentation change you did?
I had trouble to install the Version 4.2 because the installation routine for fortran is trying to copy the
index.html file and the www directory, but they are not in the code anymore.

So i think, the last two lines (bold) of this Makefile part can be just deleted?

install-fortran: fortran
        -rm -r $(DESTDIR)$(SYSMODPATH)/fftw3.mod
	-rm -r $(DESTDIR)$(SYSMODPATH)/planetsconstants.mod
	-rm -r $(DESTDIR)$(SYSMODPATH)/shtools.mod
	mkdir -pv $(DESTDIR)$(SYSLIBPATH)
	cp $(LIBDIR)/lib$(LIBNAME).a $(DESTDIR)$(SYSLIBPATH)/lib$(LIBNAME).a
	-cp $(LIBDIR)/lib$(LIBNAMEMP).a $(DESTDIR)$(SYSLIBPATH)/lib$(LIBNAMEMP).a
	mkdir -pv $(DESTDIR)$(SYSMODPATH)
	cp $(INCDIR)/*.mod $(DESTDIR)$(SYSMODPATH)/
	mkdir -pv $(DESTDIR)$(SYSSHAREPATH)/shtools
	cp -R examples $(DESTDIR)$(SYSSHAREPATH)/shtools/
	mkdir -pv $(DESTDIR)$(SYSSHAREPATH)/man/man1
	cp -R man/man1/ $(DESTDIR)$(SYSSHAREPATH)/man/man1/
	mkdir -pv $(DESTDIR)$(SYSDOCPATH)/shtools
	**cp index.html $(DESTDIR)$(SYSDOCPATH)/shtools/index.html
	cp -R www $(DESTDIR)$(SYSDOCPATH)/shtools/**"

I made an ebuild (gentoo portage) for this version 4.2 and had to patch the Makefile first, before it could be used.

Greetings
Galitus

**Comment by MarkWieczorek** [comment]
Thanks, I just fixed this in this PR: https://github.com/SHTOOLS/SHTOOLS/pull/157

This will be merged into develop in a day or two, and a new release with all these changes is exapected at the end of summer.
