### ISSUE TITLE
Spherical harmonics values

### ISSUE THREAD

**Issue by sekisushai** [SHTOOLS/SHTOOLS#167]
Hello,
Is there a method in SHTOOLS to evaluate the spherical harmonics at particular values in python? Something similar to the function `sph_harm` from the library `scipy.special`:

```
from scipy.special import sph_harm
sph_harm(1,2,3,4)
```

**Comment by MarkWieczorek** [comment]
No, there isn't, but this is trivial to do. 

The spherical harmonic functions are equal to the Legendre function multiplied by a sin or cos function (at least for the real harmonics, see Eq. 2 here: https://shtools.oca.eu/shtools/real-spherical-harmonics.html). 

I guess that we could make a convenience function for this. I'll add it to the list of things to do.

**Comment by MarkWieczorek** [comment]
How is this?

https://github.com/SHTOOLS/SHTOOLS/milestone/18

**Comment by sekisushai** [comment]
Looks great!
Thank you

**Comment by MarkWieczorek** [comment]
This is implemented here:

https://github.com/SHTOOLS/SHTOOLS/pull/170

I should be issuing a new release with these changes in the next week or two.
