### ISSUE TITLE
exchange X and Y labels in tutorial_1 notebook

### ISSUE THREAD

**Issue by MMesch** [SHTOOLS/SHTOOLS#168]
reported by @cryocuhk in Gitter:

Minor bugs in Tutorial 1 (https://github.com/SHTOOLS/SHTOOLS/blob/master/examples/notebooks/tutorial_1.ipynb): x and y labels of the first two power spectrum plots should be reversed.

**Comment by MarkWieczorek** [comment]
fixed: https://github.com/SHTOOLS/SHTOOLS/pull/169
