### ISSUE TITLE
Precision for fortran data

### ISSUE THREAD

**Issue by zerothi** [SHTOOLS/SHTOOLS#179]
There are several places in the code where data precision is not obeying the fortran standard:

1) The precision is specified through:
```fortran
real*8 :: a
```
which is not recommended (at least it isn't portable). It is better to do:
```fortran
 integer, parameter :: dp = selected_real_kind(p=15)
 real(dp) :: a
```

2) A code that looks like this:
```fortran
program test

  implicit none

  integer, parameter :: dp = selected_real_kind(p=15)
  real(dp) :: dat

  dat = 1.123456789123456789123456789
  print *, dat
  dat = 1.123456789123456789123456789_dp
  print *, dat
end program test
```
will print two different numbers, in the code there is a mixture of the former and latter.

**Comment by MarkWieczorek** [comment]
I figured that someone would complain about this at some point :)

Could you point me to a good reference on how this should be done? I will also need to declare things like complex*16, and a couple other funny things as well...

**Comment by zerothi** [comment]
Hehe, ;)

I don't have a good page since very little needs to be change:

0) Define some parameter as the precision (in this case `dp` for double precision)
1) All constants need to be suffixed with `_dp`
2) All `real*8` declarations should be changed to `real(dp)`
3) All `complex*16` declarations should be changed to `complex(dp)` (yes, this creates a double precision complex variable)
4) All `real(variable)` should be changed to `real(variable, dp)`
5) All `cmplx(re, im)` should be changed to `cmplx(re, im, dp)` and when one defines complex constants one should do `cmplx(1._dp, 0.2_dp, dp)`!! Important!! ;-D
6) Taking the double imaginary part of a complex value should be `aimag`.

I think this covers more or less everything...

**Comment by MarkWieczorek** [comment]
I am finally starting to work on this problem, and have two simple questions. 

First, do you know what is the preferred way to define a `dp` floating point variable? I used to use
```
f = 1.23d13
```
but I could see doing this as
```
f = 1.23d13_dp
```
or
```
f = 1.23e13_dp
```

Second, before hardcoding everything, I am wondering if I should use
```
real(kind=dp)
```
or if 
```
real(dp)
```
is equally portable.

**Comment by MarkWieczorek** [comment]
I'm going to close this issue as this has been updated in the following two PRs

* https://github.com/SHTOOLS/SHTOOLS/pull/186
* https://github.com/SHTOOLS/SHTOOLS/pull/187

A new release is planned in under a week, so if you have any other suggestions, please let me know.

**Comment by zerothi** [comment]
Thanks for your huge work. If tests pass, I would say go for it! :)
