### ISSUE TITLE
Bug in shcoeffsgrid.SHComplexCoeffs._expand_coord line 2079

### ISSUE THREAD

**Issue by yfwang09** [SHTOOLS/SHTOOLS#181]
Line 2079 in function shcoeffsgrid.SHComplexCoeffs._expand_coord():

`values = _np.empty_like(lat, dtype=float)`

However, when expanding complex SHCoeffs into arbitrary points on 2d (lon, lat) space, the value should also be complex. This leads to the following error when calling SHCoeffs.expand(lat, lon):

`TypeError: can't convert complex to float`

The fix is simply: dtype = _np.complex.

**Comment by MarkWieczorek** [comment]
Thanks.  I just fixed this and merged it into develop. This will be incorporated with the next release that will take place over the summer.
