### ISSUE TITLE
A bug in shcoeffsgrid.py line 1763

### ISSUE THREAD

**Issue by JNLossner** [SHTOOLS/SHTOOLS#183]
Hello,

when attempting to use the SHCoeffs.rotate() method on coefficients that are not 4pi-normalized, it throws a TypeError: " convert() got an unexpected keyword argument 'csphase' "

After looking through the code, I have determined the root of the problem is in the call to _convert() within SHCoeffs._rotate() on line 1763.

```
temp = _convert(coeffs, normalization_in='4pi', csphase=1,
                            normalization_out=self.normalization,
                            csphase_out=self.csphase)
```
Judging by the convert() method in shio, the keyword argument ```csphase``` should be ```csphase_in```.

**Comment by MarkWieczorek** [comment]
Thanks! This was just fixed here (https://github.com/SHTOOLS/SHTOOLS/pull/184) and merged into develop. This should be merged into master at the end of the month when a new version is released.
