### ISSUE TITLE
Build conda packages via conda-forge?

### ISSUE THREAD

**Issue by megies** [SHTOOLS/SHTOOLS#185]
Has anybody ever tried or considered building conda packages through conda-forge? I might give it a shot if not.. or nobody knows anything preventing it

**Comment by MarkWieczorek** [comment]
I don't use conda, so if you want to try that would be great. The only issue I can think of is that you need to find a conda package of FFTW with fortran binding support. In our travis tests we use 

```
conda install -n test-environment -c eumetsat fftw3
```

But there might be a better alternative.

**Comment by megies** [comment]
@MarkWieczorek see conda-forge/staged-recipes#9121. I'm no guru on the compiler setups but we'll see, I gave it a quick shot, maybe we get lucky..

**Comment by moorepants** [comment]
This is building if anyone would like to review: https://github.com/conda-forge/staged-recipes/pull/11298 I'm not familiar with this package but my cluster users want it and I was trying to get it on conda forge.

**Comment by MarkWieczorek** [comment]
Thanks! I'll try to look at this soon, but I don't use conda, so this might take a week to find some free time to figure it out.

Could you let me know how to maintain the conda package whenever there is a new release?

**Comment by moorepants** [comment]
I can add you as a maintainer on the conda forge package. It has a bot that will autoupdate the conda package when you make a PyPi release, so its possible we only have to merge a pull request each time (you can even set it to automerge for simple packages). If there are more complex changes in the release, you make have to manually update the conda feedstock.

**Comment by moorepants** [comment]
The pull request was merged and the feedstock resides here: https://github.com/conda-forge/pyshtools-feedstock

Users can now `conda install -c conda-forge pyshtools`.

**Comment by MarkWieczorek** [comment]
Last thing: Does this work with windows, or is it only for linux/macos?

**Comment by moorepants** [comment]
No. I did not spend any time on a windows build. It may be possible to build with flang on conda forge but someone will need to be that time in.

**Comment by megies** [comment]
@MarkWieczorek you can see the exact list of packages available here: https://anaconda.org/conda-forge/pyshtools/files

**Comment by MarkWieczorek** [comment]
Thanks for all the work on this! (we will worry about windows later....)

I just have one last question: is it possible to build from source with conda? With pip, we include the source files so that the fortran part can be compiled at install time using
```
pip install pyshtools --no-binary pyshtools
```
Just curious if a similar thing exists with conda.

**Comment by moorepants** [comment]
You can use `conda build` to build conda packages from source. If you download the feedstock recipe and run conda build in that directory if will build from source.

**Comment by MarkWieczorek** [comment]
I'm going to close this as the conda package appears to be working (but no Windows), and the documentation has been updated in this PR:

https://github.com/SHTOOLS/SHTOOLS/pull/228

**Comment by megies** [comment]
> is it possible to build from source with conda?

> Just curious if a similar thing exists with conda.

@MarkWieczorek the main point of Anaconda and having pre-built packages in conda-forge is actually to not have to compile on the user end. Anaconda is taking care of a sane library setup and conda-forge is using a standardized compiler setup, so unless you want to go on exotic systems like a supercomputer cluster, pre-compiled packages should work out of the box for 99% of users.

pip in installed in every conda environment too, though, so you can always install with `pip install ...` into a conda environment (after activating it), relying on that environment's compiler setup, so that packages will keep playing nicely with each other. In general it's a good idea to install all dependencies with conda first though, and only install with pip whenever necessary and ideally not pulling anything else in besides the package to be installed, so that conda has an easier time keeping hold of installed packages.

E.g. [for obspy, to set up a development installation](https://github.com/obspy/obspy/wiki/Developer-Installation) we recommend installing everything with conda (including obspy), then deinstalling only the obspy package with conda, and then doing an editable pip installation on a local git clone (which includes ad hoc compilation of some C extensions). This works like a charm for us.
