### ISSUE TITLE
`make -j fortran` (parallelized) is not stable

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#196]
When building the fortran components of SHTOOLS from the makefile, compilation will sometimes give an error when using `make -j fortran` (the `-j` option compiles the files in parallel). 

The problem is that some of the `.mod` files are required before compiling a given piece of code. In the makefile (`src/Makefile`), I have explicitly tried to list all the dependencies explicitly using 

```
ftypes.mod : ftypes.o
SHTOOLS.mod : SHTOOLS.o ftypes.mod
FFTW3.mod : FFTW3.o ftypes.mod
PlanetsConstants.mod : PlanetsConstants.o ftypes.mod
...
```
However, sometimes (not always) when compiling a file like `PlanetsConstants.f95`, the compiler will complain that `ftypes.mod` does not exist.

It is possible that this is a problem with `make` (I am using the system `make` on macOS).

As a temporary solution with the macOS brew package manager (which defaults to parallel compilation), I have explicitly required that brew compile these files sequentially (see https://github.com/SHTOOLS/homebrew-shtools/issues/4).

I note that this problem occurs about 1/6th of the time (or less) when compiling. If this error occurs, it is usually only necessary to try again.

**Comment by rainbowsend** [comment]
I think the problem is that the target SHReturnTapersMap.o does not has the dependency ftypes.mod
https://github.com/SHTOOLS/SHTOOLS/blob/bf88a99e3ccfbcd8df8b7c0c5d104a790e68a7f0/src/Makefile#L244

https://github.com/SHTOOLS/SHTOOLS/blob/bf88a99e3ccfbcd8df8b7c0c5d104a790e68a7f0/src/SHReturnTapersMap.f95#L66

**Comment by MarkWieczorek** [comment]
Thanks for catching that! Unfortunately, that doesn't solve the problem though. 1 out of X times (where X is approximately the number of processors I have), I will get a problem like this
```
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math ftypes.f95
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math SHTOOLS.f95
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math FFTW3.f95
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math PlanetsConstants.f95
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math PlmIndex.f95
PlanetsConstants.f95:11:9:

   11 |     use ftypes
      |         1
Fatal Error: Cannot open module file 'ftypes.mod' for reading at (1): No such file or directory
```
`PlanetsConstants.f95` is defined to depend on `ftypes.mod` in the Makefile. I have no idea how to solve this: ftypes is compiled first, but the mod file doesn't seem to be ready in time to be used on a different processor.

**Comment by rainbowsend** [comment]
`ftypes.mod` should not depend on `ftypes.o` but `ftypes.f95`
https://github.com/SHTOOLS/SHTOOLS/blob/bf88a99e3ccfbcd8df8b7c0c5d104a790e68a7f0/src/Makefile#L157

if you make SHTOOLS.mod a dependency of  the `%.o` rules you can delete everything below `PlanetsConstants.mod : ftypes.mod
`
``` make
%.mod: %.f95
	$(F95) -c $(F95FLAGS) $<
%.o: %.f95 SHTOOLS.mod
	$(F95) -c $(F95FLAGS) $<
%.o: %.F95 SHTOOLS.mod
	$(F95) -c $(F95FLAGS) $(LAPACK_FLAGS) $<

then the end of the makefile looks like this

ftypes.mod : ftypes.f95
SHTOOLS.mod : ftypes.mod
FFTW3.mod : ftypes.mod
PlanetsConstants.mod : ftypes.mod
```

Moreover, 
https://github.com/SHTOOLS/SHTOOLS/blob/bf88a99e3ccfbcd8df8b7c0c5d104a790e68a7f0/src/Makefile#L73-L92
can be replaced with a single line:
`OBJS0 := $(SRCS0:%.f95=%.o)`

to make that working a typo in https://github.com/SHTOOLS/SHTOOLS/blob/bf88a99e3ccfbcd8df8b7c0c5d104a790e68a7f0/src/Makefile#L66 needs to be corrected (missing l in  SHCi**l**mToVector.f95)

I am going to create a merge request
