### ISSUE TITLE
setup.py instead of Makefile for Python package

### ISSUE THREAD

**Issue by ioshchepkov** [SHTOOLS/SHTOOLS#2]
The main reason is the possibility of using true pythonic and recommended  way to distribute (pip), install, remove and upgrade package since all routines are fully wrapped now.

**Comment by MatthiasMeschede** [comment]
Agree, this needs to be done!

**Comment by ioshchepkov** [comment]
Great! Does it also means Python 3 in all .*py files?

**Comment by ioshchepkov** [comment]
Great! Does it also means support of Python 3?

**Comment by MatthiasMeschede** [comment]
That's the other thing that needs to be done! :)

**Comment by ioshchepkov** [comment]
I've already done (or I think so) this with the current 'master' branch and it is not hard with 2to3 tools if there is no need for Python 2. In other case it is also possible, of course. I can help with this, if required.

**Comment by MatthiasMeschede** [comment]
This would be great! It should go to the develop branch though which already has a few other additions for Python (a class interface). I don't know what the best way is to organize this, maybe you make your own fork of the project and then somehow push to the main repository?

**Comment by MarkWieczorek** [comment]
For info, here is our planned dev schedule.

https://github.com/SHTOOLS/SHTOOLS/wiki/Development-schedule

I will be writing doc and man pages for the next month, so any help would be appreciated as I'm not going to get anything else done... I'd suggest using the develop branch if you want to contribute.

**Comment by ioshchepkov** [comment]
Yes, I think to fork is the best way. The main question is: do we need Python 2?

**Comment by MarkWieczorek** [comment]
I think we need to support 2 and 3, as almost everyone used version 2 now. What if we just add some flag to the setup file for --with-python3 ?

**Comment by ioshchepkov** [comment]
In the Makefile it can be flag, yes. In the setup.py file there is no need for this, the version will depend on user.

**Comment by MMesch** [comment]
Here is a good introduction about the stuff that we need to add:

https://packaging.python.org/en/latest/distributing/#configuring-your-project
