### ISSUE TITLE
problem with Curve2Mask

### ISSUE THREAD

**Issue by lcx366** [SHTOOLS/SHTOOLS#204]
I construct a circle centered on [0E,0N] with a radius of 10 degrees. After masking the circle with the function Curve2Mask, I got an unexpected result, that is, the left side of the central meridian is not masked normally. If this is a bug, can you fix it? Or make it a normal mask globally, without concern about whether the closed curve passes through the central meridian. Following is the test code and results
```
from pyshtools.spectralanalysis import Curve2Mask
from pyshtools.utils import MakeCircleCoord

# Construct a circle centered on [0E,0N] with a radius of 10 degrees
lat0,lon0 = 0,0
theta0 = 10
circle = MakeCircleCoord(lat0, lon0, theta0)
curve_mask = Curve2Mask(180,circle,0, sampling = 2,centralmeridian=1)
# print the mask at 0N
print(curve_mask[90])
```
```
[0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

**Comment by MarkWieczorek** [comment]
This should be fixed in the develop branch. It is no longer necessary to specify `centralmeridian` and the algorithm is a bit more general than before. There are still some pathological cases that may cause problems (like straight lines in longitude), and I'm willing to fix these if they ever arise for you.
