### ISSUE TITLE
Bug Fix in shgravcoeffs.py

### ISSUE THREAD

**Issue by fghorow** [SHTOOLS/SHTOOLS#207]
I have stumbled across a route through the SHTools codebase where Python complains that `_shtools` is undefined in shgravcoeffs.py upon usage.

Adding the line:
`from .. import shtools as _shtools`
at an appropriate place in the imports of shgravcoeffs.py works for me.

Since it's a one liner, rather than providing a patch, I'll let you decide where you'd like it in your code.

**Comment by MarkWieczorek** [comment]
Hi. Thanks for pointing this out. It turns out that I already caught this, and the fix has been pushed to the `develop` branch. This should be included in the next release, probably in january...
