### ISSUE TITLE
Bug in PlBar_d1.f95 line 108

### ISSUE THREAD

**Issue by HattoriAkihisa** [SHTOOLS/SHTOOLS#210]
Hello,

When z = 1, the output of PlBar (p) does not match that of PlBar_d1.
I found a bug (?) in PlBar_d1.f95 line 108.
https://github.com/SHTOOLS/SHTOOLS/blob/8ce2b595197d3d24cf786d9adffe2bb508324a6e/src/PlBar_d1.f95#L106-L110

I think it should be replaced by
`p(l+1) = sqrt( dble(2*l+1))`

**Comment by MarkWieczorek** [comment]
Hi. Thanks for reporting this! It is indeed a bug. There is also a similar bug in the file `PlON_d1.f95`.

Would you be interested in opening a pull request for fix these two files? If not, I will do it before I leave the office today... (just base it off of the develop branch).

**Comment by HattoriAkihisa** [comment]
Thank you for your quick response.
I created a pull request for this.

**Comment by HattoriAkihisa** [comment]
I noticed that PlON_d1 had other bugs here, so I closed the pull request.

**Comment by MarkWieczorek** [comment]
I thought that the changes looked ok. Was there something else that wasn't working?

**Comment by HattoriAkihisa** [comment]
The factor `sqrt (4 * pi)` is missing in the calculation of PlON_d1 when abs (z) = 1, so PlON_d1 return the same values as PlBar_d1.
I created a pull request again.

**Comment by MarkWieczorek** [comment]
Changes have been merged into develop.
