### ISSUE TITLE
Compare MakeGridPoint() with own implementation

### ISSUE THREAD

**Issue by RoyJames** [SHTOOLS/SHTOOLS#225]
Hi there,

Thanks for putting this repo. It has helped me a lot.

I mainly use this tool for fitting spherical harmonics and use the coefficients for graphics rendering in another huge C++ based system. So I need to implement the expansion for 3D normalized Cartesian points myself and I need to make sure it's consistent with what pyshtools does.

Below is a simple test script I wrote, implementing real orthonormal spherical harmonics up to order 1, following https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics

```
import numpy as np
import pyshtools

def cart2sph(x, y, z):
    hxy = np.hypot(x, y)
    r = np.hypot(hxy, z)
    el = np.arctan2(z, hxy)
    az = np.arctan2(y, x)
    return az, el, r

def dot(dirvec, expansion):
    tempA = np.sqrt(1.0/(4*np.pi))
    tempB = np.sqrt(3.0/(4*np.pi))
    result = expansion[0] * tempA - expansion[1] * tempB * dirvec[1] + expansion[2] * tempB * dirvec[2] - expansion[3] * tempB * dirvec[0]
    return result

shvec = [0.096947, 0.002988, -0.035554, 0.009518]
direction = [0.47531935795211927, 0.4482499486689892, -0.7570624092333694]

coeff = pyshtools.shio.SHVectorToCilm(shvec)
az, el, r = cart2sph(direction[0], direction[1], direction[2])
lon = np.rad2deg(az)
lat = np.rad2deg(el)
print('lat: {} long: {}'.format(lat,lon))

shres = pyshtools.expand.MakeGridPoint(coeff, lat, lon, norm=4, csphase=-1)
dotres = dot(direction, shvec)

print('pyshtool:\t{}\nMy result:\t{}'.format(shres, dotres))
```

And the result is
> lat: -49.20590631270726 long: 43.32116658151345
> pyshtoosl:       0.03241552037797725
> My result:      0.03763485910768707

I've read your documentation many times but couldn't understand the difference here. I'd appreciate it if you can tell me whether I misinterpreted anything. Thanks a lot.

**Comment by MarkWieczorek** [comment]
For degree 1, it should be really straightforward to check what the answer should be. The Legendre function is simply sin(lat) or cos(lat), and then you just multiply this by sin(lon) or cos(lon). Could you let me know if this is a problem with pyshtools, or with your code?

I would first check to see if the problem is in the "latitude" or "longitude" direction. What if you make a map of the how the two routines differ as a function of latitude and longitude? I would also verify that the output of `SHVectorToCilm(shvec)` is what you expect it to be. It is possible that your convention is different from what this routine expects. Then, I would try to do the test using only a single spherical harmonic (not all 4) in order to determine if they are all wrong, or just one.

**Comment by RoyJames** [comment]
> For degree 1, it should be really straightforward to check what the answer should be. The Legendre function is simply sin(lat) or cos(lat), and then you just multiply this by sin(lon) or cos(lon). Could you let me know if this is a problem with pyshtools, or with your code?
> 
> I would first check to see if the problem is in the "latitude" or "longitude" direction. What if you make a map of the how the two routines differ as a function of latitude and longitude? I would also verify that the output of `SHVectorToCilm(shvec)` is what you expect it to be. It is possible that your convention is different from what this routine expects. Then, I would try to do the test using only a single spherical harmonic (not all 4) in order to determine if they are all wrong, or just one.

Hi Mark,

Thank you for the quick reply. You gave great suggestions which I followed and visualized lat-lon maps per SH coefficient. Then I found out it was due to both an unexpected direction offset and SH vector ordering. I especially need to bring up the ordering issue while I try reordering them using the `YilmIndexVector()` function. There is an example in the its Fortran implementation but not in its python version (also a minor typo at L7):
https://github.com/SHTOOLS/SHTOOLS/blob/551a35ec8e2e6de54e870678cf4ea60b47d490c1/src/YilmIndexVector.f95#L1-L16
I suspect this implementation is not right. Take (1, -1) in the 2nd row for example, if I call `pyshtools.shio.YilmIndexVector(2,1,-1)`, the result is `1`, which is equal to `pyshtools.shio.YilmIndexVector(1,1,1)` but its index should be `3` in the vector form. The obvious fix I see is to flip the sign of `m` in the final expression if it was negative.

Best,
Zhenyu

**Comment by MarkWieczorek** [comment]
I see your problem. You can not input negative angular orders into this function. The first index tells whether you want the sin or cos term, and m has to be positive. I'll see what I can do to make this more obvious in the documentation....

**Comment by RoyJames** [comment]
Having realized that, I managed to make everything work. I think the caveat here is that the fortran implementation throws error for a negative `m`, where as the python version does not do the same thing. Adding a warning there should best avoid misuse. Thank you again for attending to my issue.

**Comment by MarkWieczorek** [comment]
I've updated the docs and now throw an error for negative values. This should be merged into the develop branch in a week or so, and then merged into master with the next release a few months from now.
