### ISSUE TITLE
GPL license of FFTW

### ISSUE THREAD

**Issue by moorepants** [SHTOOLS/SHTOOLS#227]
When I packaged shtools for conda forge I noticed that FFTW is licensed under the GPL. As far as I understand, if you link against GPL code your code will have to be licensed GPL. There is much discussion of this online, an example is here: https://softwareengineering.stackexchange.com/questions/158789/can-i-link-to-a-gpl-library-from-a-closed-source-application

I don't know anything about the innards of this library, but this just raised a red flag for me when specifying the licenses on conda forge. If you haven't looked into this already and determined that your current license is fine, it is probably worth a look.

**Comment by MarkWieczorek** [comment]
I'm aware of this problem, but am not to concerned about it. Here is my understanding (please correct me if I'm wrong):

* pyshtools can link to either Intel's MKL library or the FFTW library (the two are interchangeable). The licensing issue arises when someone compiles a binary *and* decides to distribute it.
* Given that pyshtools is BSD-3, you are allowed to take it and relicense it however you want. Thus, if you want to, you can change the license of your conda build to GPL: I don't mind :). The conda build is not techically built by the pyshools maintainers (but I would be happy to add you to the team if you like!), so technically, I don't think this is my problem...
* I talked to the FFTW people a while ago, and they said that if I distribute a binary, the only obligation I have is to also distribute the FFTW source code, which is freely available on their web site. If I don't distribute the source code, this is technically illegal, but they don't seem to mind.
* The pip binary is potentially problematic as I don't distribute the FFTW source code with it (even though it is freely available). If this ever becomes a problem, I will either (1) build the binary with MKL, (2) stop distributing binaries all together, or (3) find a way to include the FFTW source code with the binary distribution.

As I said, I'm not expert, so if you have any advice, please let me know!

**Comment by moorepants** [comment]
Maybe I should license the conda feedstock as GPL as the easiest solution. I don't think the FFTW conda forge package distributes the source code with that binary. I don't think it is a GPL requirement to include the source code you link against, I think you just have to share the code you write under the GPL.

Your interpretation is questionable, in my opinion. If true, then every author of code that links against GPL code doesn't have to license their source code as GPL, only those that distribute binaries of said code have to release the associated source code as GPL. But a random Joe that builds a binary of the author's code doesn't necessarily have the rights to release the author's code as GPL in all cases. It may in this case, because BSD code can be included in GPL code if the license is present.

Regardless this all seems like a ball of wax. It think the simplest thing for code authors to do is to release their source code as GPL if that source code will link to GPL'd code when compiled. I see how it gets complex if you can swap a dependency for multiple equivalent options that happen to be licensed differently.

Ok, my head hurts thinking about this :)

**Comment by moorepants** [comment]
> Given that pyshtools is BSD-3, you are allowed to take it and relicense it however you want.

I don't think this is technically true. You have to abide by the BSD license (i.e. include the license with the source and/or binary). You can't "relicense it" in the sense that you remove the BSD license and replace with GPL.

**Comment by moorepants** [comment]
I've licensed the Conda Forge binary under the GPL 2.0 (or later) and included the licenses of FFTW and SHTOOLS to be on the safe side. Feel free to close this if you are happy with how you are handling things in this repository.

**Comment by moorepants** [comment]
As a reference, the conversation continues at conda forge: https://github.com/conda-forge/conda-forge.github.io/issues/1065
