### ISSUE TITLE
Can't output geoid gridded data to netcdf.

### ISSUE THREAD

**Issue by ymwanghub** [SHTOOLS/SHTOOLS#230]
Hi there,

When I followed the introduction-3 example and was trying to output the geoid data created from the gravity file, there is an error says:

mars_geoid = clm.geoid(u0, lmax=719)
mars_geoid.to_netcdf('Mars_geoid.nc')

AttributeError: 'SHGeoid' object has no attribute 'to_netcdf'

But I do have checked the SHGeoid class in the master branch, there is a "to_netcdf()" under Class method. I don't know how to solve this issue, anyone can help?

Yongming

**Comment by MarkWieczorek** [comment]
Just to let you know, I found that there was a small problem with the `to_netcdf()` function. One of the attributes was a boolean, which netcdf doesn't seem to support, this is fixed in an ongoing PR. A simple fix is to use `mars_geoid.geoid.to_netcdf()`.

**Comment by ymwanghub** [comment]
Thanks, Mark.
