### ISSUE TITLE
cannot import name 'spharm_lm_' from 'pyshtools'

### ISSUE THREAD

**Issue by wudlike** [SHTOOLS/SHTOOLS#236]
My system is linux, when I use pyshtools by
`from pyshtools import spharm_lm_`

the error shows as: cannot import name 'spharm_lm_' from 'pyshtools' (but other functions like `SHCoeffs,utils`  work very well)
in addition, `spharm` cannot be imported as well.
(also, another way, `import pyshtools as pysh`  and then call function using `pysh.spharm_lm_` does not work too.

**Comment by MarkWieczorek** [comment]
I think that there are two things going on:

First, the function name is `spharm_lm`, and second, this function is located in the `expand` submodule.
 
Could you try if the following works?

```
from pyshtools.expand import spharm_lm
```
Also, please check back in about 2 or 3 weeks: we should be putting out a new version then with lots of great things!

**Comment by wudlike** [comment]
Thanks, yes 
          `from pyshtools.expand import spharm_lm`
works well, Great!

**Comment by wudlike** [comment]
Hi, one more question,
I find that the results from `spharm_lm` are different from the real values.
For instance, I want to get the answer of Y(ell,m,theta,phi), where ell=m=1, theta=30 degrees and phi=0,
from [wiki](https://en.wikipedia.org/wiki/Spherical_harmonics), we can see the answer should be -1/2*sqrt(3/2pi)sin(theta)e^iphi,
which equals to -0.17274... (substitute theta=30 and phi=0)
While the answer from pyshtools is:

           `print(spharm_lm(1, 1, 30, 0, normalization='ortho',csphase=-1))`
>>> -0.42314...

Taking into account the difference between `latitude` and 'colatitude', then I change theta to 60 degrees, the answer is
>>> -0.24430...

I don't know where I am wrong.

**Comment by MarkWieczorek** [comment]
You are using complex spherical harmonics, so you need to set `kind='complex'` like this

```
pysh.expand.spharm_lm(1, 1, 30, 0, normalization='ortho',csphase=-1, kind='complex')
```
which yields `(-0.17274707473566767+0j)`

The default parameters for pyshtools are to use real spherical harmonics that are 4pi normalized, without the -1 phase factor.

**Comment by wudlike** [comment]
ok, that's the point, really appreciate your help!
