### ISSUE TITLE
inconsistent argument naming in SHTOOLS.f95

### ISSUE THREAD

**Issue by rainbowsend** [SHTOOLS/SHTOOLS#248]
This is a rather pedantic remark:
In SHTOOLS.f95 somtimes `c` is used instead of `cilm`. The documentation always uses `cilm`

``` fortran
        function SHPowerL(c, l)
            integer, parameter :: dp = selected_real_kind(p=15)
            real(dp) :: SHPowerL
            real(dp), intent(in) :: c(:,:,:)
            integer, intent(in) :: l
        end function SHPowerL
```
More Examples: SHPowerDensityL, SHCrossPowerL, SHCrossPowerDensityL,...

I think nothing can break when making those names consistent

**Comment by rainbowsend** [comment]
In SHMultiTaperSE and  SHMultiTaperCSE `sh` is used instead of `cilm`.
In SHLocalizedAdmitCorr `g` and `t` are used instead of cilm. The documentation is clearer here using `gilm`, `tilm`

**Comment by MarkWieczorek** [comment]
Thanks! I can rename these. Just let me know if you find any other inconsistencies (I'll look too).

**Comment by MarkWieczorek** [comment]
It turns out that it is trivial to change the variable names in the `SHTOOLS.f95` interface block. However, to have 100% consistency, we should probably also change the variable names in the original source code as well (i.e., such as `SHMultiTaperSE.f95`). This later part is annoying (but easy), but I won't have time to get to this until after the 4.7 release. If all goes well with pygmt, their 0.2 release will be out on thursday/friday, and I will start the release procedure for shtools over the weekend.

If it is useful to you, I could modify the `SHTOOLS.f95` file right away, and then work on the source code later in the month. If it's not important, I will just do this all at the same time later.

**Comment by rainbowsend** [comment]
That are good news.
The updated argument names in SHTOOLS.f95 would be useful for me for automatically generating the c wrapper (with reduced amount of additional arguments for the dimensions). Unfortunately, I cannot work on this before Friday. So I can not promise that everything is finished in time.

**Comment by MarkWieczorek** [comment]
`SHTOOLS.f95` and fortran documentation have been modified to use a systematic "cilm" nomenclature for spherical harmonic variables (merged to develop). However, the original source code of these functions has not (yet) been updated to reflect these changes. This should pose no problems as none of these variables are optional.

These fortran subroutines should eventually be updated to use the same nomenclature as the documentation and `SHTOOLS.f95` interface block:
```
SHPowerL
SHPowerDensityL
SHCrossPowerL
SHCrossPowerDensityL
SHPowerSpectrum
SHPowerSpectrumDensity
SHCrossPowerSpectrum
SHCrossPowerSpectrumDensity

SHPowerLC
SHPowerDensityLC
SHPowerDensityLC
SHCrossPowerLC
SHCrossPowerDensityLC
SHPowerSpectrumC
SHPowerSpectrumDensityC
SHCrossPowerSpectrumDensityC

SHAdmitCorr
SHLocalizedAdmitCorr
SHMultiTaperSE
SHMultiTaperCE
SHMultiply
SHMultiTaperMaskSE
SHMultiTaperMaskCSE
SHMagPowerSpectrum
SlepianCoeffs
SlepianCoeffsToSH
```

**Comment by rainbowsend** [comment]
thank you!

**Comment by MarkWieczorek** [comment]
And I just fixed all the fortran source files too. This will be merged into develop in the next couple of days. I do not plan on updating the python wrapper functions as this will be a huge pain.

**Comment by MarkWieczorek** [comment]
I think that this is all taken care of in v4.7 PR (which will be released next week), so I am going to close this. Let me know if there is anything that I might have missed.

**Comment by rainbowsend** [comment]
https://shtools.github.io/SHTOOLS/shmultitapercse.html

> call SHMultiTaperCSE (mtse, sd, sh1, lmax1, sh2, lmax2, tapers, taper_order, lmaxt, k, alpha, lat, lon, taper_wt, norm, csphase, exitstatus)

**Comment by MarkWieczorek** [comment]
Thanks for catching this before the official release went out! 

https://github.com/SHTOOLS/SHTOOLS/pull/250
