### ISSUE TITLE
Add windows support to the pyshtools conda package

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#263]
The pyshtools conda package currently supports macOS and linux, **but does not yet support windows**.

See this [related issue at the pyshtools feedstock](https://github.com/conda-forge/pyshtools-feedstock/issues/2). Insight into installing pyshtools on windows might be found [here](https://github.com/SHTOOLS/build-shtools/blob/master/appveyor.yml) for the pypi windows wheels.

**Comment by k-dominik** [comment]
This seems to be done in https://github.com/conda-forge/pyshtools-feedstock/pull/30
