### ISSUE TITLE
SHcoefs.expand returns uncorrect result when used with radians (degrees = False option)  

### ISSUE THREAD

**Issue by GuillaumeVoisi** [SHTOOLS/SHTOOLS#271]
Hello,
When running the following code with pyshtools 4.7.1
```python
import pyshtools as psh 
import numpy as np
lmax = 3
coefs = np.array([[[ 0.,  0.,  0.,  0.],
        [ 1.,  4.,  0.,  0.],
        [ 2.,  5.,  7.,  0.],
        [ 3.,  6.,  8.,  9.]],
       [[ 0.,  0.,  0.,  0.],
        [ 0., -4.,  0.,  0.],
        [ 0., -5.,  7.,  0.],
        [ 0., -6.,  8., -9.]]])
pshcoefs = psh.SHCoeffs.from_array(coefs,
                         lmax=lmax, csphase =-1,
                          normalization='schmidt')
print("With degrees=True : ", pshcoefs.expand(colat=45., lon=90., degrees=True))
print("With degrees=False : ", pshcoefs.expand(colat=np.pi/4, lon=np.pi/2, degrees=False))
```

I get : 

> With degrees=True :  0.7085541930105346
With degrees=False :  10.413469906070663

Where obviously the two results should be the same. The correct answer is the one with `degrees=True`. 

Thank you !

**Comment by MarkWieczorek** [comment]
Thanks for catching this. It turns out that your code would work fine if you specified `lat` instead of `colat`.

I just fixed this on the develop branch, so if you are comfortable with installing from source, you could test this. Otherwise, a new release should come out in about a month.

**Comment by GuillaumeVoisi** [comment]
That's great, thanks for the quick fix !
