### ISSUE TITLE
Ability to use sampling from SSHT

### ISSUE THREAD

**Issue by paddyroddy** [SHTOOLS/SHTOOLS#274]
I usually use the SSHT code to perform my harmonic transforms https://astro-informatics.github.io/ssht/ https://pypi.org/project/pyssht/ which has sampling methods `MW`, `MWSS`, `MW_pole` in addition to `DH` & `GL` which I see are already supported. Is it possible to use this code with SSHT easily?

**Comment by MarkWieczorek** [comment]
Hi. At present, its not possible to use other backends for doing the spherical harmonic transforms. We would like to implement this at some point, and here is the relevant open issue: https://github.com/SHTOOLS/SHTOOLS/issues/258

Unfortunately, this is low on my priority list. If this is something that you might be interested in working on, that would be great!

**Comment by MarkWieczorek** [comment]
I am going to close this issue. Please see #258 for adding additional spherical harmonic backends to pyshtools.
