### ISSUE TITLE
install script setup.py

### ISSUE THREAD

**Issue by MMesch** [SHTOOLS/SHTOOLS#29]
There are a few issues remaining:

* Fortran part should be build by ```setup.py``` if possible
* ```F95FLAGS``` are set manually
* ```pip install -e``` . doesn't work. It imports the ```pyshtools``` dir from the base directory, not the one from ```build/``` . ```pip uninstall pyshtools``` doesn't seem to clean up properly in this case either.

**Comment by QuLogic** [comment]
> pip install -e . ... imports the pyshtools dir from the base directory

That's the point of `-e`...

**Comment by MMesch** [comment]
Yes. But pyshtools is not build in the base dir but in
build/lib.../pyshtools . This means it doesn't import the correct folder.
Am 23.07.2016 10:14 schrieb "Elliott Sales de Andrade" <
notifications@github.com>:

**Comment by MMesch** [comment]
works now. ```develop``` doesn't call ```build``` and therefore didn't build the docs.
