### ISSUE TITLE
Online tutorial links are broken

### ISSUE THREAD

**Issue by janabrah** [SHTOOLS/SHTOOLS#292]
**Description of the problem**

The links to tutorials at this page https://shtools.github.io/SHTOOLS/python-examples.html are broken, they say "Error 503 Backend is unhealthy"

**System information**

**Comment by MarkWieczorek** [comment]
Thanks for spotting this, but it looks like this is a system wide problem with jupyter : I get the same error on https://nbviewer.jupyter.org/. I'll contact someone there next week if its not resolved over the weekend.
