### ISSUE TITLE
# How can use it in windows for python?

### ISSUE THREAD

**Issue by xiaojingdounaodan** [SHTOOLS/SHTOOLS#293]
# when i use it in windows 
```
from pyshtools.spectralanalysis import Curve2Mask
...
mask = Curve2Mask(2*(self.degree_order+1), points, north_pole,
                          sampling=2, centralmeridian=central_meridian)
```

there is  a problem:
```
发生异常: TypeError
'centralmeridian' is an invalid keyword argument for _SHTOOLS.Curve2Mask()
```

how can i resolve this problem in windows?All my programs are built in windows!

**Comment by MarkWieczorek** [comment]
Hi there. The problem is that this parameter was deprecated in version 4.6.2: https://github.com/SHTOOLS/SHTOOLS/releases/tag/v4.6.2

If you just remove this parameter, things should work fine. If you run into any problems, let me know.

**Comment by xiaojingdounaodan** [comment]
> Hi there. The problem is that this parameter was deprecated in version 4.6.2: https://github.com/SHTOOLS/SHTOOLS/releases/tag/v4.6.2
> 
> If you just remove this parameter, things should work fine. If you run into any problems, let me know.

when i remove the parameter ,like this:
```
mask = Curve2Mask(2*(self.degree_order+1), points, north_pole,
                          sampling=2)
```
here is a new problem:
```
SHToolsError
Improper dimensions of input array.
```

and i have seen the issues in this project，i find  ‘pyshtools’ do not support windows now? why some funtions in pyshtools which installed by conda on windows can work ?or some sulutions can make it supports windows?

i do really  not put my program on unix system!

thanks!

**Comment by MarkWieczorek** [comment]
I suspect that `points` isn't formatted properly. Could you let me know what the shape is? It should be a numpy ndarray with something like `(1000, 2)`

As for windows: Today, pyshtools for windows works when installing with `pip`. There is some work to get this to work with conda as well (https://github.com/conda-forge/pyshtools-feedstock/issues/2). If only "some" functions are working, then you should check to make sure that you are using the latest version, and that you have uninstall all previous versions.

**Comment by xiaojingdounaodan** [comment]
thank you very much! when i use the solution which you gave , the problem is solved perfectly!
