### ISSUE TITLE
libtool:  error: unrecognised option: '-static'

### ISSUE THREAD

**Issue by chdyxh** [SHTOOLS/SHTOOLS#295]
**Description of the problem**
when I compiled the SHTOOLS using 'make',  an error appeared: **libtool:  error: unrecognised option: '-static'**. I checked the manual of libtool at https://www.gnu.org/software/libtool/manual/libtool.html#Compile-mode which shows the libtool program has the following synopsis: libtool [option]… [mode-arg]… . So I modified the **Makefile** file in _SHTOOLS/src/_ to match the standard usage, but it didn't work. I have to ask for your help! 

**System information**
Centos 8.3  with libtool --version 2.4.6

**Comment by MarkWieczorek** [comment]
Based on the gnu documentation [here](https://www.gnu.org/software/libtool/manual/libtool.html), `-static` is a standard option, so I'm not sure why you are getting an error on Centos. On macOS, the man page says that this option is the default, so my guess is that you should be able to remove this with no problems.

If you are having problems with gnu's `libtool`, if you read further down in the makefile, you'll see that there is an option to use `ar` and `ranlib` instead. However, for this, you will need to manually comment the libtool call and uncomment the other two calls.

If what we are doing here is non-standard, or not portable, I'd be interested in fixing this! I just need more details.

**Comment by chdyxh** [comment]
Firstly, thanks for your reply. I remove -static by commenting the  code `LIBTOOLFLAGS = -static`. However, another error appear:
`Usage: /usr/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-o'
make[1]: *** [Makefile:83: /home/yangxh/SHTOOLS-4.8/lib/libSHTOOLS.a] Error 1
make[1]: Leaving directory '/home/yangxh/SHTOOLS-4.8/src'
make: *** [Makefile:256: fortran] Error 2
`
So, I use ar instead and make it.  Also, I find that the $(PWD) in SHTOOLS/Makefile, do not  seem to work and get the absolute path.I modifies the following code:
`LIBPATH = $(PWD)./$(LIBDIR)
MODPATH = $(PWD)./$(MODDIR)
INCPATH = $(PWD)./$(INCDIR)`
`cp /lib/libSHTOOLS.a /usr/local/lib/libSHTOOLS.a
cp: cannot stat '/lib/libSHTOOLS.a': No such file or directory
make: *** [Makefile:280: install] Error 1`
and complete the  installation. I am not sure whether it is because I'm using a cloud server so that such unusual errors appear.  At last, thanks for your reply again.

**Comment by chdyxh** [comment]
Because this is my second time to comment on Github, I don't know how to inserted newlines in the code piece, resulting in poor readability. Soor about that

**Comment by MarkWieczorek** [comment]
`-o` also appears to be a standard option for libtool, so I'm not sure what is going on. Maybe you could check the version of libtool and make sure it is up to date? Not sure what else to suggest....

As for `$(PWD)`, I'm also confused why this isn't working. Adding the dot doesn't work on my system...

Let me know if you figure any of this out. I'd be happy to change the makefiles to make things more portable.

**Comment by chdyxh** [comment]
I suggest adding a line of codes, thus the relative path approach:
`PWD = .`
I guess, the reason why `$PWD` don't wokk is that  `PWD` in the makefile is treated as a variable instead of a command in the terminal, at least on my machine. A more portable, also more usual way is to take the relative path.

**Comment by MarkWieczorek** [comment]
Could you find out if the environment variable PWD is set on your system? The make file sets the shell to `SHELL = /bin/sh` so you could perhaps try using a different shell, like tcsh or bash. If it is not set, could you tell me how you obtain the current working directory in your system (there must be a way to do this!)?

**Comment by chdyxh** [comment]
On Centos 8.3 systerm, `pwd` is set to obtain the current working directory. But after I change `PWD` to `pwd`, it still does't work. I am also confused. Maybe `$(pwd)` work well on other's meachine. 

Thanks for your time， Dr. Wieczorek

**Comment by MarkWieczorek** [comment]
I am just checking back from a long hiatus of coding. Could you let me know if you ever resolved these problems, and if there are any outstanding problems that should be addressed? We will be putting out a new release in a week or two, so if you have a solution, I would like to include it.

**Comment by chdyxh** [comment]
All my attempts are listed above. Actually, I bypassed these problems rather than resolved them directly. I will test them on Ubuntu later and check  if they will appear again?

**Comment by MarkWieczorek** [comment]
For info, I am going to remove the "-static" option that is used with libtool. It turns out that this is the default value anyways, and I noticed that this was causing problems on another linux system. We just released v4.10, and I will likely release a minor update 4.10.1 as soon as we fix some minor build issues with conda and pypi.

https://github.com/SHTOOLS/SHTOOLS/pull/351

**Comment by mjh217** [comment]
Just in case anyone else ends up here, I had the same issues with the libtool call. Specs are Ubuntu 20.04.4 LTS operating system, SHTOOLS v4.10 (git cloned today), libtool version 2.4.6 (checked it was the latest update). As suggested above, switching to ar (i.e. entering the Makefile located in the src directory, commenting line 83 and uncommenting lines 85 and 86) got everything working. So I think the problem has to do with the GNU libtool option flags. Thanks!

**Comment by MarkWieczorek** [comment]
Could you please check out this PR? https://github.com/SHTOOLS/SHTOOLS/pull/386

I'm making two changes that will hopefully fix these issues.

1. As far as I can tell $(PWD) is not in the gnu make documentation, and they suggest using $(CURDIR) to get the current directory path. I suspect that PWD was deprecated at some point, even though it appears to work on some systems.
2. I have replaced libtool by calls to ar and ranlib. Other people have recently complained about this, and it appears that the arguments for libtool are different on different systems. If ar + ranlib works for everyone, then I am happy to do it that way!
