### ISSUE TITLE
make_docs.py does not use specified python executable

### ISSUE THREAD

**Issue by lmaibaum** [SHTOOLS/SHTOOLS#30]
The Makefile invokes the utility make_docs.py using

`./pyshtools/make_docs.py .`

which gets executed by the default python interpreter. If one builds against a non-default python installation this might fail. For example, on my Mac I am using a MacPorts installation of python, but the make_docs call above fails because it tries to load the pyshtools module into Apple's python executable.

This should be easily fixable by replacing the above line with

`$(PYTHON) ./pyshtools/make_docs.py .`

in the Makefile targets all, all2, all3, and python.

**Comment by MarkWieczorek** [comment]
Thanks! I'll be pushing a fix to this later today.
