### ISSUE TITLE
Inaccuracy in conversion from complex grid to SHCoeff

### ISSUE THREAD

**Issue by mreineck** [SHTOOLS/SHTOOLS#300]
The following snippet generates SHCoeffs, converts them to a grid and back again, and compared the result to the input. The resulting number should be very small (around 1e-15), but in some cases like the presented one it is much larger.

```
import numpy as np
import pyshtools as pysh

lmax=15
csphase=1
grd="DH"
normalization="4pi"
extend=True
degrees = np.arange(2*lmax+1, dtype=float)
degrees[0] = np.inf
power = degrees**(-2)

clm = pysh.SHCoeffs.from_random(power, seed=12345, kind='complex')
clm = clm.convert(normalization=normalization,
                  csphase=csphase,
                  lmax=lmax)

grid = clm.expand(grid=grd,extend=extend)
cilm = grid.expand(normalization=normalization,
                  csphase=csphase)

print(np.max(np.abs(cilm.to_array()-clm.to_array())))
```

This inaccuracy only happens when
- the grid is "DH" or "DH2"
- lmax is odd
- the transforms are complex-valued

As far as I can tell, there is some problem in the `grid.expand` call when computing the coefficient for (lmax, lmax), but I didn't analyze this any further.

**Comment by MarkWieczorek** [comment]
This is fixed in this PR. I will merge this into develop within a week after I do a bit more testing.

https://github.com/SHTOOLS/SHTOOLS/pull/303
