### ISSUE TITLE
Release GIL in fortran calls

### ISSUE THREAD

**Issue by sehoffmann** [SHTOOLS/SHTOOLS#304]
By adding `!f2py threadsafe` to the declarations in the f2py signature file, pythons Global Interpreter Lock (GIL) gets released during fortran calls, allowing other code to be processed in the meanwhile.

**Comment by MarkWieczorek** [comment]
Are there any downsides to doing this? f2py has very little documentation!

**Comment by sehoffmann** [comment]
Unless the Fortran code interacts with the python interpreter in some way, it should be safe to do so. I am however by no means an expert on this.

**Comment by mreineck** [comment]
To my knowledge, dropping the GIL is perfectly fine as long as you are only manipulating the _content_ of Python buffers (which is what the Fortran codes do ... they read/write `numpy` arrays, which are presented to it as Fortran arrays), in contrast to creating/deleting Python objects.
This reminds me that I should also release the GIL in my wrapper functions ... I'll make the necessary changes.
