### ISSUE TITLE
Windows wheel for Python 3.9

### ISSUE THREAD

**Issue by richli** [SHTOOLS/SHTOOLS#319]
I see on PyPi that Windows wheels are available for Python 3.7 and 3.8, but not Python 3.9:

https://pypi.org/project/pyshtools/4.9.1/#files

Would it be possible to build and upload a wheel for Python 3.9?

**Comment by MarkWieczorek** [comment]
Adding 

```
image:
  - Visual Studio 2019
```

Breaks all the appveyor builds: https://ci.appveyor.com/project/MarkWieczorek/build-shtools

I think that I put this is in the right place. If you don't have any ideas on what is happening, I'll just revert this change.

**Comment by richli** [comment]
So it's failing here because this path doesn't exist in that image:

```
dir "C:/Program Files/Microsoft SDKs/Windows"
```

It doesn't seem like this is used for anything in the script other than displaying information, so it could probably be removed. But then there may be other things later on that also have different paths...

Looking at the [upstream version](https://github.com/MacPython/scipy-wheels/blob/master/appveyor.yml), they use the Visual Studio 2017 image, which *doesn't* include Python 3.9, but it appears they install Python 3.9 using multibuild.

**Comment by MarkWieczorek** [comment]
Just let me know if you want me to make any specific changes (I don't have the time to debug this, and don't understand windows....).

**Comment by MarkWieczorek** [comment]
You can try, I have no idea. If it doesn't, I'll see what I need to do to trigger it.

I would really like to get the windows CI to work with github actions, but I don't know enough about windows to do this myself.
