### ISSUE TITLE
function MakeGravGradGridDH() giving error

### ISSUE THREAD

**Issue by saurabhsrvastav** [SHTOOLS/SHTOOLS#322]
**Description of the problem**
I have Spherical harmonic coefficients up to degree 40 which is stored in Cilm (dimension (2, 41, 41) for gravity observation. I want the spherical harmonic gradient of the function and hence use MakeGravGradGridDH(). The snippet of the code is given below with the corresponding error.

    GM = 398600441500000.0
    a = 6378.137e3 
    b = 6356.752e3 
    f = (a-b)/a
    d = 40 # Max degree
vxx, vyy, vzz, vxy, vxz, vyz = pysh.gravmag.MakeGravGradGridDH(Cilm, GM, R, a, f, lmax = d)
The error which I am getting is shown below

I am not able to understand, what mistake I am doing. Please help me

**System information*
![error](https://user-images.githubusercontent.com/5467023/140876234-8618f57d-9f2c-46df-911c-8709335d2dc5.PNG)
*

**Comment by MarkWieczorek** [comment]
`a` and `f` are optional arguments. Could you try this and let me know if it works?

```
vxx, vyy, vzz, vxy, vxz, vyz = pysh.gravmag.MakeGravGradGridDH(Cilm, GM, R, a=a, f=f, lmax=d)
```

**Comment by saurabhsrvastav** [comment]
Thank you for the suggestion and it works. I have one more query. Just like MakeGrid2D() routine where we can create a grid of the desired size, is there a similar routine for calculating gradient at desired grid size? Thanks in advance.

**Comment by MarkWieczorek** [comment]
No there isn't. However, if you use global DH/GLQ grids, these routine are much faster than the MakeGrid2D routine.

**Comment by MarkWieczorek** [comment]
Also, in the next release the docs will be updated to note that the correct order of the optional arguements is `lmax, a, f...`.

**Comment by saurabhsrvastav** [comment]
Thanks for your reply and suggestions.
