### ISSUE TITLE
Expand a 3d shape model into spherical harmonics?

### ISSUE THREAD

**Issue by gaowutong** [SHTOOLS/SHTOOLS#326]
Hello, I am new to shtools.

I am wondering if I can generate gravitational coefficients from a 3d shape model (*.obj file) using this library. There is a direct relationship between them.

But according to the documentation, it seems I need to transform the shape data into topography grid. Is there any direct method?

Thanks!

**Comment by MarkWieczorek** [comment]
You will need to convert your shape model into one of the grid formats that shtools uses. Here is the relevant documentation:

https://shtools.oca.eu/shtools/public/grid-formats.html
