### ISSUE TITLE
Radius parameter in cMakeGradientDH should be real, not integer

### ISSUE THREAD

**Issue by eschnett** [SHTOOLS/SHTOOLS#328]
**Description of the problem**
The line https://github.com/SHTOOLS/SHTOOLS/blob/8d83c42d1313d5624c4db8c2e57300c5d819834e/src/cWrapper.f95#L307 declares the new `radius` parameter for `cMakeGradientDH` to be `integer`. I assume it should be `real` instead.

**Comment by MarkWieczorek** [comment]
Thanks for reporting this. However, it looks like this is correct in the latest version (4.9.1). Could you try updating to the latest version and see if this gets resolved? If this is a problem with the brew/macports version, please let me know (it's possible I need to update those). If you are not in a hurry, we will be putting out a new release (4.10) in about 1 or 2 weeks, so you could just wait until then.

**Comment by MarkWieczorek** [comment]
As far as I can tell, the commit with the 4.9.1 tag on master has the correct version of this file. I'm just going to close this.

**Comment by eschnett** [comment]
The [released version](https://github.com/SHTOOLS/SHTOOLS/releases/download/v4.9.1/SHTOOLS-4.9.1.tar.gz) has the radius still as integer...

Anyway, I'm looking forward to the next release. (No need to re-open this ticket.)

**Comment by MarkWieczorek** [comment]
Sorry for the confusion. I looked at that code several times, and only today do I see what you were talking about. Maybe I was just tired... I just pushed a change for the variable declaration. Also, I noted that the new `radius` parameter was missing from the fortran call. Hopefully this is all ok now :)
