### ISSUE TITLE
Building of wheels for Windows is failing, again (pyshtools 4.10)

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#352]
In our continuous battle with building wheels for windows, they are once again failing for pyshtools 4.10. 

If you have *any* familiarity with windows, please take a look at the output here: https://ci.appveyor.com/project/MarkWieczorek/build-shtools We are not very familar with windows, so any advice or comments would be appreciated.

The only thing of substance that changed is the location of build library in the setup.py (there was a breaking change going from setuptools 62.0.0 to 62.1.0): https://github.com/SHTOOLS/SHTOOLS/commit/f696d048b79f9bd42c6a5386cc16bce6fcd23aba However, as far as I can tell, this is not the issue.

**Comment by alxkalinin** [comment]
Please try to apply the following patch to the `https://github.com/SHTOOLS/build-shtools/blob/master/appveyor.yml`, line number 152

```
  # Setup mingw C++ compiler explicitly
  # We want to compile C++ and Fortran sources with the same mingw compiler
  - echo [build]>> %PYTHON%\Lib\distutils\distutils.cfg
  - echo compiler = mingw32>> %PYTHON%\Lib\distutils\distutils.cfg
  - echo [build]>> %PYTHON%\Lib\site-packages\setuptools\_distutils\distutils.cfg
  - echo compiler = mingw32>> %PYTHON%\Lib\site-packages\setuptools\_distutils\distutils.cfg
```

In the build log files I found that the gcc is not used and system tries to use visual studio cl. Probably the reason is that the distutils now deprecated and not used. The setuptools\_distutils are the replacement.

**Comment by MarkWieczorek** [comment]
That helped, but there are still some problems. It appears that everything now compiles fine. However, when trying to make the documentation, there is an error that `_SHTOOLS` can't be imported.

```
---- BUILDING DOCS ----
  creating build\lib.win-amd64-cpython-38\pyshtools\doc
  Traceback (most recent call last):
    File "build\lib.win-amd64-cpython-38\pyshtools\make_docs.py", line 12, in <module>
      import _SHTOOLS
  ImportError: DLL load failed while importing _SHTOOLS: The specified module could not be found.
  Traceback (most recent call last):
```
Also, I am curious, do we need all 4 of these lines, or only the last two?
```
- echo [build]>> %PYTHON%\Lib\distutils\distutils.cfg
  - echo compiler = mingw32>> %PYTHON%\Lib\distutils\distutils.cfg
  - echo [build]>> %PYTHON%\Lib\site-packages\setuptools\_distutils\distutils.cfg
  - echo compiler = mingw32>> %PYTHON%\Lib\site-packages\setuptools\_distutils\distutils.cfg
```

**Comment by alxkalinin** [comment]
> That helped, but there are still some problems. It appears that everything now compiles fine. However, when trying to make the documentation, there is an error that `_SHTOOLS` can't be imported.

Now the problem is in the "PYTHON_BUILD_DIR" variable in the https://github.com/SHTOOLS/build-shtools/blob/master/appveyor.yml file.

The old format is `build\lib.win-amd64-3.7`, from the log files I get that the new format is `build\lib.win-amd64-cpython-37`. Please try to change the `appveyor.yml` starting from the line 55:
```
build\lib.win-amd64-3.7 --> build\lib.win-amd64-cpython-37
build\lib.win-amd64-3.8 --> build\lib.win-amd64-cpython-38
build\lib.win-amd64-3.9 --> build\lib.win-amd64-cpython-39
build\lib.win-amd64-3.10 --> build\lib.win-amd64-cpython-310
```

> Also, I am curious, do we need all 4 of these lines, or only the last two?

For the python-3.10 and latest setuptools we need only the last two. But may be for the old python and old setuptools we need the first two. We can try to keep only the last two and see what happens.

**Comment by MarkWieczorek** [comment]
That worked! I probably could have figured out the last step, but not the first, so thanks. Also, I remove the first two "echo" lines and it worked on all the builds. 

If you see anything that needs to be updated in the appveyor file, let me know. We will probably put out 4.10.1 very soon to patch a couple small issues...

**Comment by alxkalinin** [comment]
> That worked!

I was happy to help, thanks for the nice SHTOOLS project!

> If you see anything that needs to be updated in the appveyor file, let me know. We will probably put out 4.10.1 very soon to patch a couple small issues...

In the appveyor file in the line 72 we have python version '3.10' in the quotes, but in the lines 57, 62 and 67 we have python version without the quotes. I think this is not important, but it will be cleaner if we have the common python version notation.
