### ISSUE TITLE
Import of pyshtools results in multiple DeprecationWarnings

### ISSUE THREAD

**Issue by markdjwilliams** [SHTOOLS/SHTOOLS#354]
**Description of the problem**

Importing pyshtools under python3 with warnings filters disabled produces multiple DeprecationWarnings. To reproduce:

`
$ python -Wdefault -c 'import pyshtools'
`

...which yields:

`
.../pyshtools/shclasses/shgravgrid.py:359: DeprecationWarning: invalid escape sequence \p
  cb_triangles='neither', cb_label='$g_\phi$, m s$^{-2}$',
.../pyshtools/shclasses/shgravgrid.py:443: DeprecationWarning: invalid escape sequence \p
  """
.../pyshtools/shclasses/shtensor.py:1995: DeprecationWarning: invalid escape sequence \l
  """
.../pyshtools/shclasses/shtensor.py:2106: DeprecationWarning: invalid escape sequence \l
  """
.../pyshtools/shclasses/shtensor.py:2217: DeprecationWarning: invalid escape sequence \l
  """
.../pyshtools/shclasses/shtensor.py:2467: DeprecationWarning: invalid escape sequence \l
  """
.../pyshtools/shclasses/shtensor.py:2578: DeprecationWarning: invalid escape sequence \l
  """
.../pyshtools/shclasses/shtensor.py:2689: DeprecationWarning: invalid escape sequence \l
  """
.../pyshtools/shclasses/shtensor.py:2959: DeprecationWarning: invalid escape sequence \l
  long_name='${\lambda}_1$',
.../pyshtools/shclasses/shtensor.py:2962: DeprecationWarning: invalid escape sequence \l
  long_name='${\lambda}_2$',
.../pyshtools/shclasses/shtensor.py:2965: DeprecationWarning: invalid escape sequence \l
  long_name='${\lambda}_3$',
.../pyshtools/shclasses/shtensor.py:2986: DeprecationWarning: invalid escape sequence \l
  long_name='${\lambda}_{h1}$',
.../pyshtools/shclasses/shtensor.py:2989: DeprecationWarning: invalid escape sequence \l
  long_name='${\lambda}_{h2}$',
.../pyshtools/shclasses/shtensor.py:2992: DeprecationWarning: invalid escape sequence \l
  long_name='${\lambda}_{hh}$',
.../pyshtools/shclasses/shtensor.py:3131: DeprecationWarning: invalid escape sequence \l
  self._eig1_label = '$\lambda_1$, ' + self.units
.../pyshtools/shclasses/shtensor.py:3132: DeprecationWarning: invalid escape sequence \l
  self._eig2_label = '$\lambda_2$, ' + self.units
.../pyshtools/shclasses/shtensor.py:3133: DeprecationWarning: invalid escape sequence \l
  self._eig3_label = '$\lambda_3$, ' + self.units
.../pyshtools/shclasses/shtensor.py:3135: DeprecationWarning: invalid escape sequence \l
  self._eigh1_label = '$\lambda_{h1}$, ' + self.units
.../pyshtools/shclasses/shtensor.py:3136: DeprecationWarning: invalid escape sequence \l
  self._eigh2_label = '$\lambda_{h2}$, ' + self.units
.../pyshtools/shclasses/shtensor.py:3137: DeprecationWarning: invalid escape sequence \l
  self._eighh_label = '$\lambda_{hh}$, ' + self.units
.../pyshtools/shclasses/shtensor.py:3294: DeprecationWarning: invalid escape sequence \l
  self._eig1_label = '$\lambda_1$, ' + self._units_formatted
.../pyshtools/shclasses/shtensor.py:3295: DeprecationWarning: invalid escape sequence \l
  self._eig2_label = '$\lambda_2$, ' + self._units_formatted
.../pyshtools/shclasses/shtensor.py:3296: DeprecationWarning: invalid escape sequence \l
  self._eig3_label = '$\lambda_3$, ' + self._units_formatted
.../pyshtools/shclasses/shtensor.py:3298: DeprecationWarning: invalid escape sequence \l
  self._eigh1_label = '$\lambda_{h1}$, ' + self._units_formatted
.../pyshtools/shclasses/shtensor.py:3299: DeprecationWarning: invalid escape sequence \l
  self._eigh2_label = '$\lambda_{h2}$, ' + self._units_formatted
.../pyshtools/shclasses/shtensor.py:3300: DeprecationWarning: invalid escape sequence \l
  self._eighh_label = '$\lambda_{hh}$, ' + self._units_formatted
.../pyshtools/shclasses/shmaggrid.py:342: DeprecationWarning: invalid escape sequence \p
  cb_triangles='neither', cb_label='$B_\phi$, nT',
.../pyshtools/shclasses/shmaggrid.py:426: DeprecationWarning: invalid escape sequence \p
  """
.../pyshtools/gravmag/mag_spectrum.py:93: DeprecationWarning: invalid escape sequence \s`

I suspect these docstrings need to be converted to raw strings (using `r"""` instead of `"""`)

**System information**

python 3.7.11
pyshtools 4.10

**Comment by MarkWieczorek** [comment]
Thanks for catching this. I had a hard time reproducing this, as my system (macos + conda) didn't catch these errors in a consistent manner. In any case, I added `r` to all the strings I found that had latex characters with backslashes in them. I think that this fixes everything, but if I missed anything, let me know: https://github.com/SHTOOLS/SHTOOLS/pull/351

I would like to put out a new minor release in the next week or so with these changes. Beforehand, though, I was hoping to fix the conda packaging issues that we are having: https://github.com/conda-forge/pyshtools-feedstock/pull/27

**Comment by markdjwilliams** [comment]
Changing the python flags to `-B -Wall` seems to make this repro more reliably for me.

**Comment by MarkWieczorek** [comment]
I think I caught the remaining problems. If you could check, that would be great. My system doesn't complain about these (even though it probably should...)

**Comment by markdjwilliams** [comment]
Thanks again, this is now good with your latest changes.
