### ISSUE TITLE
Core dumped error for calling pyshtools (4.10) 

### ISSUE THREAD

**Issue by leon-cmg** [SHTOOLS/SHTOOLS#359]
**Description of the problem**
I installed pyshtools using 'pip install pyshtools'.
But I am stuck by a 'core dumped' error when I import pyshtools within python :
**leon-cmg@air:~/test/SHTOOLS$** python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import pyshtools as pysh
Segmentation fault (core dumped)

It cannot be solved with 'ulimit -c unlimited'
How to fix this error?

**System information**

Distributor ID: Ubuntu
Description: Ubuntu 18.04.1 LTS
Release: 18.04
Codename: bionic

**Comment by MarkWieczorek** [comment]
Could you try installing using conda? If that doesn't work, you could try compiling it yourself using
```
pip install pyshtools --no-binary pyshtools
```

**Comment by leon-cmg** [comment]
Hi Mark, I have tried each method of installation using pip or conda as you proposed, and got the same error.

**Comment by leon-cmg** [comment]
The following is the installation tips using conda
`(base) leon_cmg@air:~/test/SHTOOLS$ conda install -c conda-forge pyshtools`
Collecting package metadata (current_repodata.json): done
Solving environment: done

\## Package Plan ##

  environment location: /home/leon_cmg/software/miniconda3

  added / updated specs:
    - pyshtools


The following NEW packages will be INSTALLED:

  pyshtools          conda-forge/linux-64::pyshtools-4.10-py39h3174c5b_2


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done
`(base) leon_cmg@air:~/test/SHTOOLS$ cat test.py`
`import matplotlib.pyplot as plt`
`import pyshtools as pysh`
`from pyshtools import constants`

`#pysh.utils.figstyle(rel_width=0.75)`
`#clm = pysh.datasets.Mars.GMM3()`
`#clm.info()`

`(base) leon_cmg@air:~/test/SHTOOLS$ python test.py`
Segmentation fault (core dumped)

**Comment by MarkWieczorek** [comment]
I have no idea how to debug this given that pyshtools works on Ubuntu as part of the github action tests. The only things that I could suggest would be to create a new conda environment and start over. You could also try installing a previous version (like 4.9) and see if that works (perhaps the conda package got messed up somehow).

**Comment by leon-cmg** [comment]
Creating a new conda environment is the solution!

 `conda create -n pyshtools python=3.10`
 `conda activate pyshtools`
 `conda install -c conda-forge pyshtools`

`(pyshtools)leon_cmg@air:~/test/SHTOOLS$ cat test.py`
`import matplotlib.pyplot as plt`
`import pyshtools as pysh`
`from pyshtools import constants`

`pysh.utils.figstyle(rel_width=0.75)`
`clm = pysh.datasets.Mars.GMM3()`
`clm.info()`

`(pyshtools) leon_cmg@air:~/test/SHTOOLS$ python test.py`
kind = 'real'
normalization = '4pi'
csphase = 1
lmax = 120
GM (m3 / s2) = 42828372854187.76
r0 (m) = 3396000.0
Omega (rad / s) = 7.088218127854995e-05
error_kind = 'unspecified'
header = ['3.3960000000000000e+03', '4.2828372854187757e+04', '1.6202815226760665e-05', '120', '120', '1', '0.0000000000000000e+00', '0.0000000000000000e+00']
header2 = None
name = 'GMM3'
epoch = None

Thanks! this issue can be closed.
