### ISSUE TITLE
pygmt is not compatible with SHTOOLS

### ISSUE THREAD

**Issue by jason996cj** [SHTOOLS/SHTOOLS#361]
Hello, thank you and your team for developing such a good tool, but I have noticed that PyGMT and ShTools do not seem to be compatible while learning your code:
1. In the notebooks folder in the Examples folder, there is a Jupyter code called Plotting - Maps, which uses PyGMT, but cannot import after installation.
2. After installing PyGMT, although you cannot use it, ShTools also starts to report errors. Only after you uninstall PyGMT can you continue to use ShTools.

I don't understand what's going on, so I want to ask the version numbers of the various packages of ShTools. And I guess it may be PYGMT problem, so I want to ask you how you successfully make PYGMT compatible with your Shtools, thank you!
my email: cjungeo@163.com ,looking forward to your reply or email !

**Comment by MarkWieczorek** [comment]
Hi. You will have to provide more information if you want us to help you debug this problem. Could you start by letting us know which operating system you are using, how you installed shtools and pygmt, and what the version numbers are?

**Comment by jason996cj** [comment]
Hello, thank you very much for your reply! I'm using windows 10 professional, cpu is 11th Gen Inter i7-11700. python software I'm using conda 4.14.0 platform, current python version is 3.9.12. GMT version installed on computer is 6.4.0, pygmt installed during debugging is latest version v0.7.0, shtools version is latest 4.10. During debugging I have used python 3.10, 3.8, 3.7 and other virtual environments, none of which are compatible with pygmt and shtools.

**Comment by MarkWieczorek** [comment]
Since you are using conda, I would try the following:
1. create a new environment, and try to install pyshtools. If that fails,
2. create a new environment and try to install pygmt.

**Comment by jason996cj** [comment]
1. I tried many different versions of python virtual environment, pygmt can't be successfully imported after installation (only testing pygmt alone didn't work either).
2. shtools can be installed and used successfully, but as soon as I install pygmt (still can't import after installation), it starts not working.

**Comment by MarkWieczorek** [comment]
So it sounds like the problem is that the pygmt conda package doesn't work on your system. Could you open an issue on the pygmt project and let them know? 

pyshtools should work fine without pygmt. In particular, pyshtools tests whether pygmt is correctly installed before using with this code
```
try:
    import pygmt as _pygmt
    _pygmt_module = True
except ModuleNotFoundError:
    _pygmt_module = False
```
So the easiest solution for you would be to uninstall pygmt.

In any case, could you send me the error message you get when trying to import pyshtools? It is possible that I should add another exception in addition to `ModuleNotFoundError`.

**Comment by jason996cj** [comment]
The method you provided does work, I haven't tried using the [try:...] statement here in import before. statement, but the part involving pygmt still doesn't work, so I'll ask the pygmt community about it. But I just found out that after I installed pygmt and then pyshtools pyshtools no longer reports errors (although pygmt still doesn't work). Now it seems that the problem is with pygmt, and I will come back here tomorrow when I encounter the original error again, so thank you for your diligence in answering my question!

**Comment by jason996cj** [comment]
> conda activate pygmt

> python -m ipykernel install --user --name pygmt  #to install conda env properly

> jupyter kernelspec list --json


![屏幕截图 2022-09-08 204444](https://user-images.githubusercontent.com/58262284/189125133-f5b8fdfe-ce3a-4210-af51-5ca5d78e09dc.png)
![屏幕截图 2022-09-08 204509](https://user-images.githubusercontent.com/58262284/189125143-eb4f81bc-c5e1-4c6a-91e8-eb6aa81f0583.png)

**Comment by MarkWieczorek** [comment]
Great. And also, just to make sure you know, the "try" statement is already in the pyshtools code.
