### ISSUE TITLE
gravity correction excludes the effect of the polar flattening

### ISSUE THREAD

**Issue by leon-cmg** [SHTOOLS/SHTOOLS#362]
As gravity &magnetic tutorials shown, the bouguer anomaly of Mars can be calculated via:
`bc = bc.change_ref(r0=clm.r0)`
`bouguer = clm - bc`
`bouguer_grid = bouguer.expand(lmax=95, a=a, f=f)`

`It is immediately obvious that the Bouguer anomaly plot has a large component associated with the flattening of the planet: This is simply because the Bouguer correction was computed for relief with respect to a sphere, and not with respect to a flattened ellipsoid.`

How to compute Bouguer anomalies which respect a flattened ellipsoid and do not include the effect of the polar flattening?
I tried to remove degree-1 in `bc` (through `bouguer.coeffs` in `pyshtools`) along the scheme of `MarsCrustalThickness.f95`, however, I got a similar result with degree-1. Is there a way to do this?

**Comment by MarkWieczorek** [comment]
I made the following changes to the jupyter notebook

> It is immediately obvious that the Bouguer anomaly plot has a large component associated with the flattening of the planet: This is because the Bouguer correction was computed for relief with respect to a sphere, and not with respect to a flattened ellipsoid. To compute the Bouguer anomaly with respect to a flattened ellipsoid, it is only necessary to add the gravity coefficients of the flattened ellipsoid to the `bouguer` coefficients. Here, for simplicity, we assume that the reference flattened ellipsoid has a constant density:
```
b = constants.Mars.b.value

ellipsoid = pysh.SHGrid.from_ellipsoid(lmax=bc.lmax,
                                       a=a,
                                       b=b)
clm_ellipsoid = pysh.SHGravCoeffs.from_shape(ellipsoid,
                                      rho=2800.,
                                      gm=clm.gm)

clm_ellipsoid = clm_ellipsoid.change_ref(r0=clm.r0)
bouguer_ellipsoid = bouguer + clm_ellipsoid
bouguer_ellipsoid_grid = bouguer_ellipsoid.expand(lmax=95, a=a, f=f)
fig8, ax8 = bouguer_ellipsoid_grid.plot_total(cmap='RdBu_r', show=False)
```
What do you think?

The problem is that we really should have a routine that computes the spherical harmonic coefficients of the reference sphere using something like the Somigliana formula. We would either need to write this from scratch, or perhaps use the [Boule](https://github.com/fatiando/boule) project to do this. My goal is to use Boule at some point, but I just haven't had the time to work on this.

**Comment by MarkWieczorek** [comment]
The shape of Mars (when referenced to a flattened ellipsoid) has a large degree-1 component, so the Bouguer anomaly will also have a large degree-1 signal. This degree-1 Bouguer anomaly is most likely a result of hemispheric variations in crustal thickness.
