### ISSUE TITLE
Load the coefficients from Complex spherical harmonics

### ISSUE THREAD

**Issue by qzhu2017** [SHTOOLS/SHTOOLS#368]
I am wondering is there is a way to initialize the SHCoeffs class from the coefficients of Complex spherical harmonics. 

According to the [definition](https://shtools.github.io/SHTOOLS/complex-spherical-harmonics.html),
<img width="881" alt="image" src="https://user-images.githubusercontent.com/29445366/197644030-78a98086-97c1-47eb-aaa5-74626724af20.png">

The corresponding coefficients (f_lm) should consist of (l_max+1)**2 numbers. If I already have these f_lm values (a 2D array of [L_max+1, L_max+1]), can I initialize the SHCoeffs class from the `SHCoeffs.from_array` function?

It seems to me that the current SHCoeffs can only be initialized by a 3D array of [2, L_max+1, L_max+1]. Can someone help?

**Comment by MarkWieczorek** [comment]
Unfortunately, you will need to reorder to the coefficients to be in the `[2, L_max+1, L_max+1` format. I understand that this is not an efficient storage scheme, but it would be nontrivial to modify all the code to accept a different format.

What we could do is the following:
1. Create some kind of helper function that reorders the coeffiecients to the expected format. We could put it in the utils subpackage.
2. Add some kind of flag to the `from_array` method allowing the user to specify the format of the array and then convert internally.

I won't have time to work on this for the next couple of months, so if this is something that interests, please put in a PR!

**Comment by qzhu2017** [comment]
@MarkWieczorek 
Thanks for you prompt reply. I am happy to create some helper function to transform the data format. 
However, I am not sure how to do such reorder. If we follow the eq(1), there should be only `(l_max+1)**2` complex numbers. Can you instruct how to convert them to `2(l_max+1)^2` numbers and then  `[2, L_max+1, L_max+1]` array?

**Comment by MarkWieczorek** [comment]
The `coeffs` array is formatted as `[i, l, m]` where` i=0` is for positive `m` and `i=1` is for negative `m`. I'll try to add this into the docstrings to make it more obvious.

**Comment by qzhu2017** [comment]
sorry, I am still confused. If I have 4 coefficients when l_max = 1. 
$f_0^0,  f_1^{-1},  f_1^{0},  f_1^{1}$,

How shall I arrange them into a [2, 2, 2] array?

**Comment by MarkWieczorek** [comment]
$\mbox{coeffs}[0, 0, 0] = f_0^0 $
$\mbox{coeffs}[0, 1, 0] = f_1^0 $
$\mbox{coeffs}[0, 1, 1] = f_1^1 $
$\mbox{coeffs}[1, 1, 1] = f_1^{-1} $

**Comment by qzhu2017** [comment]
How about the rest elements in the array, e.g. coeffs[1, 0, 0]? Shall we just set them as zero or any number?

**Comment by MarkWieczorek** [comment]
Just set them to zero (or any other value you want, it really doesn't matter as these spherical harmonics don't exist...).

**Comment by MarkWieczorek** [comment]
I have added additional documentation to the `SHCoeffs`, `SHGravCoeffs` and `SHMagCoeffs` classes as to how the array `coeffs` is formatted. Hopefully this helps. If you still have questions, feel free to open this issue. (The PR should be merged into develop by the end of the day).
