### ISSUE TITLE
installation issue on Mac with M1 chip

### ISSUE THREAD

**Issue by usccolumbia** [SHTOOLS/SHTOOLS#370]
**Description of the problem**

pip install pyshtools  
got this error
No such file or directory: '/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_ce18o7jvqb/croots/recipe/python-split_1661469471615/_build_env/bin/llvm-ar'

**System information**
macbook pro

**Comment by MarkWieczorek** [comment]
I have a couple suggestions:
1. reinstall xcode using `xcode-select --install`
2. add `export AR=/usr/bin/ar` to your shell (I don't think that llvm-ar exists on macos).
3. try to build from source.

Let me know what you find. I build from source on an M1 with no problems.

**Comment by MarkWieczorek** [comment]
I'm going to close this issue as it is most likely outdated. We just put out a new release today (4.13.1) so you might want to try updating. If you have any further problems, please open a new issue.
