### ISSUE TITLE
brew install on linux fails with libtool error

### ISSUE THREAD

**Issue by ibrewster** [SHTOOLS/SHTOOLS#377]
**Description of the problem**
When trying to install on linux using `brew install shtools` as per the readme, the install fails with the error `libtool: error: unrecognized option: 'o'`. Full output:

```
parallels@parallels-Parallels-Virtual-Platform:~$ brew install shtools
==> Fetching shtools
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/bb9c49df97d024855d99cc08b51db44b895bd787/Formula/shtools.rb
######################################################################## 100.0%
==> Downloading https://github.com/SHTOOLS/SHTOOLS/releases/download/v4.10.1/SHTOOLS-4.10.1.tar.gz
Already downloaded: /home/parallels/.cache/Homebrew/downloads/bd11104df4b564c883cb2695e33bc38a01f54c5d6c445778b5483fc1579de798--SHTOOLS-4.10.1.tar.gz
==> make fortran
Last 15 lines from /home/parallels/.cache/Homebrew/Logs/shtools/01.make:
gfortran -c -m64 -fPIC -O3 -std=gnu -ffast-math SHExpandGLQC.f95
gfortran -c -m64 -fPIC -O3 -std=gnu -ffast-math MakeGravGradGridDH.f95
gfortran -c -m64 -fPIC -O3 -std=gnu -ffast-math MakeGravGridDH.f95
gfortran -c -m64 -fPIC -O3 -std=gnu -ffast-math MakeMagGridDH.f95
gfortran -c -m64 -fPIC -O3 -std=gnu -ffast-math MakeMagGradGridDH.f95

--> Compilation of source files successful

libtool  -o /tmp/shtools-20230307-5833-23wewl/SHTOOLS-4.10.1/lib/libSHTOOLS.a ftypes.o SHTOOLS.o FFTW3.o PlanetsConstants.o CilmPlus.o CilmMinus.o ComputeDG82.o ComputeDm.o DHaj.o djpi2.o BAtoHilm.o MakeGrid2D.o GLQGridCoord.o MakeGridPoint.o MakeGridPointC.o PlBar.o PlBar_d1.o PLegendre.o PLegendre_d1.o PLegendreA.o PLegendreA_d1.o PlmBar.o PlmBar_d1.o PlmIndex.o PlmSchmidt.o PlmSchmidt_d1.o PlSchmidt.o PlSchmidt_d1.o PreGLQ.o Random.o SHAdmitCorr.o SHBias.o SHBiasK.o SHConvertCoef.o SHFindLWin.o SHGLQ.o SHLocalizedAdmitCorr.o SHMultiply.o SHMultiTaperCSE.o SHMultiTaperSE.o SHPowerSpectra.o SHRead.o SHReadJPL.o SHReturnTapersM.o SHRotateCoef.o SHRotateRealCoef.o SphericalCapCoef.o Wigner3j.o DownContFilter.o SHRead2.o MakeGeoidGrid.o MakeCircleCoord.o SHMTCouplingMatrix.o SHReturnTapers.o SHSjkPG.o PlON.o PlON_d1.o PlmON.o PlmON_d1.o SHConfidence.o SHMagPowerSpectra.o SHPowerSpectraC.o SHBiasAdmitCorr.o SHCilmToVector.o YilmIndexVector.o ComputeDMap.o SHReturnTapersMap.o Curve2Mask.o MakeEllipseCoord.o CilmPlusRhoH.o CilmMinusRhoH.o BAtoHilmRhoH.o NormalGravity.o SHMultiTaperMaskSE.o SHMultiTaperMaskCSE.o SHBiasKMask.o SHRotateTapers.o SlepianCoeffs.o SlepianCoeffsToSH.o SHSCouplingMatrix.o SHMTVar.o SHSlepianVar.o SHSCouplingMatrixCap.o cWrapper.o MakeGravGridPoint.o MakeMagGridPoint.o MakeGradientDH.o EigValSym.o EigValVecSym.o EigValVecSymTri.o SHExpandLSQ.o SHMTDebias.o SHMTVarOpt.o MakeGridDH.o MakeGridDHC.o MakeGridGLQ.o MakeGridGLQC.o SHExpandDH.o SHExpandDHC.o SHExpandGLQ.o SHExpandGLQC.o MakeGravGradGridDH.o MakeGravGridDH.o MakeMagGridDH.o MakeMagGradGridDH.o
Usage: /home/linuxbrew/.linuxbrew/opt/libtool/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-o'
make[1]: *** [Makefile:82: /tmp/shtools-20230307-5833-23wewl/SHTOOLS-4.10.1/lib/libSHTOOLS.a] Error 1
make[1]: Leaving directory '/tmp/shtools-20230307-5833-23wewl/SHTOOLS-4.10.1/src'
make: *** [Makefile:257: fortran] Error 2
```

**System information**
Ubuntu 20.0.4(?) or 22.04.2 - I tried ubuntu 20.0.4 (I think) first, then upgraded to 22.04.2 to see if that helped.

NOTE: Install on Mac works fine, only linux brew install is having this issue

**Comment by MarkWieczorek** [comment]
This is odd. Can you look at the man page, or do a `libtool --help` to see if `-o` is accepted or not? This should be a standard option, so this is strange.

In any case, someone else came to me with the same problem on windows. We solved it by making a very simple modification to the makefile in the directory `/src` : 

https://github.com/SHTOOLS/SHTOOLS/blob/master/src/Makefile#L82-L85

As you can see in the comment, you just need to comment out the line about libtool and then uncomment the following lines about ranlib and ar. 

I would like to properly resolve this, so if you find a better solution than this hack, please let me know!

(and sorry for the delay in getting back to you. been really busy lately. In about 2 weeks I'm going to go through the backlog of issues...)

**Comment by ibrewster** [comment]
`lib tool --help`:

```
Usage: /usr/bin/libtool [OPTION]... [MODE-ARG]...

Provide generalized library-building support services.

Options:
       --config             show all configuration variables
       --debug              enable verbose shell tracing
   -n, --dry-run            display commands without modifying any files
       --features           display basic configuration information and exit
       --mode=MODE          use operation mode MODE
       --no-warnings        equivalent to '-Wnone'
       --preserve-dup-deps  don't remove duplicate dependency libraries
       --quiet, --silent    don't print informational messages
       --tag=TAG            use configuration variables from tag TAG
   -v, --verbose            print more informational messages than default
       --version            print version information
   -W, --warnings=CATEGORY  report the warnings falling in CATEGORY [all]
   -h, --help, --help-all   print short, long, or detailed help message


Warning categories include:
       'all'          show all warnings
       'none'         turn off all the warnings
       'error'        warnings are treated as fatal errors

MODE must be one of the following:

       clean           remove files from the build directory
       compile         compile a source file into a libtool object
       execute         automatically set library path, then run a program
       finish          complete the installation of libtool libraries
       install         install libraries or executables
       link            create a library or an executable
       uninstall       remove libraries from an installed directory

MODE-ARGS vary depending on the MODE.  When passed as first option,
'--mode=MODE' may be abbreviated as 'MODE' or a unique abbreviation of that.
Try 'libtool --help --mode=MODE' for a more detailed description of MODE.

When reporting a bug, please describe a test case to reproduce it and
include the following information:

       host-triplet:   x86_64-pc-linux-gnu
       shell:          /bin/bash
       compiler:       gcc
       compiler flags: -g -O2 -ffile-prefix-map=/build/libtool-2.4.6=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
       linker:         /usr/bin/ld -m elf_x86_64 (gnu? yes)
       version:        libtool (GNU libtool) 2.4.6 Debian-2.4.6-15build2
       automake:       automake (GNU automake) 1.16.5
       autoconf:       autoconf (GNU Autoconf) 2.71

Report bugs to <bug-libtool@gnu.org>.
GNU libtool home page: <http://www.gnu.org/s/libtool/>.
General help using GNU software: <http://www.gnu.org/gethelp/>.
```
So unless I'm missing something, no mention of a -o option there. man libtool is a bit more verbose, but similarly lacks mention of a -o switch, unless I am missing something. That said, it *does* make reference to MODE-ARGS that "vary depending on the MODE", which isn't overly helpful...

Editing the makefile *does* work, with the caveat that I can't figure out how to integrate that into my homebrew workflow. I'm using shutil as a dependency in another homebrew formula, not directly, so just being able to get it to install via manual intervention isn't quite good enough for me 😁

**Comment by ibrewster** [comment]
One thing I just noticed: looking at the output of `libtool --help --mode=link` (which I'm *guessing* is what you are doing here?) I do see `-o` as an option. BUT I also see the usage as this:

`libtool [OPTION]... --mode=link LINK-COMMAND...`

The output of the actual command being run, however, is this:

```
libtool  -o /tmp/shtools-20230316-7889-y0q4f3/SHTOOLS-4.10.1/lib/libSHTOOLS.a ftypes.o SHTOOLS.o FFTW3.o PlanetsConstants.o ... <and so on>```

Which seems to omit both the `--mode=link` portion of the command, as well as `LINK-COMMAND`, thereby pushing -o up to a top-level `[OPTION]` where, in fact, there is no `-o` option

...but maybe I'm missing something, and am completely off base here. Just thought I'd mention it.

**Comment by MarkWieczorek** [comment]
Thanks. But I don't understand :)

In a couple weeks I am going to go through the backlog of issues, and it is possible that I might run into the same problem running the CI tests on ubuntu. Sorry I can't take care of this right away. If you make any progress, please let me know. If there aren't any problems with using ar/ranlib, we can change that. The fact that there are two solutions in the makefile suggests that I had problems with this in the past, so I am worried that this might break something.

Also, I note that I never attempted to install shtools using brew on linux. You might want to take a look at the homebrew-core: https://github.com/Homebrew/homebrew-core/issues?q=shtools+ One comment was that linux was failing but I can't find the logs.

**Comment by ibrewster** [comment]
I think I understand your confusion here - libtool on MacOS looks to be a VERY different beast than GNU libtool. With GNU libtool, you have multiple "modes" you can run in, including:

```
       clean           remove files from the build directory
       compile         compile a source file into a libtool object
       execute         automatically set library path, then run a program
       finish          complete the installation of libtool libraries
       install         install libraries or executables
       link            create a library or an executable
       uninstall       remove libraries from an installed directory
```

From what I can tell, that is not the case with the MacOS version of libtool.

Perhaps the simplest option is to put in a switch depending on which OS you are installing on, such that MacOS uses libtool, while Linux uses the alternative?

**Comment by ibrewster** [comment]
If it helps, I put together an alternate shtools-linux formula for my formulas to use that patches the Makefile to use the alternate linking option: https://github.com/ibrewster/homebrew-avo/blob/master/shtools-linux.rb

For what it's worth, in doing some searching on creating libraries on Linux with fortran, it seems to me this alternate approach is the "correct" way to things on linux - various pages make statements like "on MacOS you can also use libtool", implying that you don't use it on Linux. That's just my impression, however, so take it with a grain of salt.

**Comment by MarkWieczorek** [comment]
I'm going to close this issue because I don't think that it is a problem after this PR: https://github.com/SHTOOLS/SHTOOLS/pull/386

In summary, other people have started complaining about libtool, and I have no idea why this function no longer works the same way on all systems. Instead of using `libtool`, we are now using `ar` followed by `ranlib`. This was already in the makefile as an alternative way of compiling the library, so the change was easy!
