### ISSUE TITLE
Issue with using taper weights when calculating a multitaper localized spectrum

### ISSUE THREAD

**Issue by nlwagner** [SHTOOLS/SHTOOLS#381]
I'm performing a localized spectral analysis on mars using an arbitrary domain (I'm using a set of lat/lon values and a call to Curve2mask and SHReturnTapersMask to get the tapers needed given a specificed Lwin). I'm able to get this working and plot some nice admittance and correlation curves, however, I want to also input the taper weight based on a call to SHMTVarOpt to make sure the taper weights are being included. 

Inputting the weights into my call to SHMultiTaperMaskSE is where the issue pops up. From what I can tell from the documentation, the output from SHMTVarOpt I need is weight_opt which is size (kin,kin). However, the size of the taper weight just needs to be the size of kin. Obviously putting this into the SHmultitaperMaskSe results in an error. The code below is this case. I also try to substitute out weight_opt with var_opt and var_unit and still no luck. I should note I did not recoginize the errors these cases spit out. The code below spits out the error "ValueError: too many axes: 2 (effrank=2), expected rank=1". Inputting the other two variables spit out: "ValueError: 0-th dimension must be fixed to 196 but got 7"

Any help would be appreciated. I'm not sure if this is a bug persay and perhaps I just misunderstood the inputs into these functions, but hopefully some clarity will come forward about the issue.

Here's a snippit of my code. I have the mask in a separate file but copied it over so it should run without it:
 ```

  import numpy as np
  import pyshtools as sh
  
  mask = [[297.50, -14.77]
          ,[305.96, -24.62]
          ,[298.67, -32.35]
          ,[286.27, -37.89]
          ,[275.38, -34.11]
          ,[275.20, -24.00]
          ,[277.13, -13.28]
          ,[288.47, -9.85]
          ,[301.57, -14.33]
          ,[305.96, -24.62]
          ,[306.40, -35.87]
          ,[299.11, -55.12]
          ,[280.65, -66.80]
          ,[254.72, -71.46]
          ,[235.82, -71.64] 
          ,[221.94, -63.20]
          ,[228.09, -55.29]
          ,[240.83, -52.21]
          ,[255.07, -56.35]
          ,[258.41, -66.19]
          ,[251.82, -69.79]
          ,[235.82, -71.64]
          ,[215.96, -57.49]
          ,[207.44, -37.89]
          ,[213.15, -18.55]
          ,[228.44, -8.80]
          ,[252.52, -7.21]
          ,[269.05, -9.94]
          ,[285.04, -7.92]
          ,[297.50, -14.77]]
  
  hellas_mask = np.flip(mask,1) # order it lat/lon
  
  lmax = 120 # max SH degree of analysis
  
  # load gravity and topo
  pot_lm = sh.datasets.Mars.GMM3(lmax=lmax)
  gm = pot_lm.gm
  topo_lm = sh.datasets.Mars.MarsTopo2600(lmax=lmax)
  
  # correct gravity
  R = topo_lm.coeffs[0,0,0]
  topo_lm.coeffs[0,0,0] = 0
  pot_lm = pot_lm.change_ref(r0=R) # downward continuate to mean radius
  pot_lm.set_omega(sh.constants.Mars.omega.value)
  
  percent_c20 = 5. # reduce degree 2 term by 95%
  topo_lm.coeffs[0,2,0] = (percent_c20/100.) * topo_lm.coeffs[0,2,0]
  pot_lm.coeffs[0,2,0] = (percent_c20/100.) * pot_lm.coeffs[0,2,0]
  
  # create localization window
  lwin0 =13 # spectral bandwidth 
  
  mask = sh.spectralanalysis.Curve2Mask(len(hellas_mask),hellas_mask,NP=0,sampling=2)
  tapers, eigenvalues = sh.spectralanalysis.SHReturnTapersMap(mask, lwin0)
  
  loc_factor = 0.9
  count = len([i for i in eigenvalues if i > loc_factor]) # find tapers with good enough localization
  #%%
  # get taper weights
  var_opt_sgg, var_unit_sgg, weight_opt_sgg = sh.spectralanalysis.SHMTVarOpt(90, tapers, eigenvalues, pot_lm.admittance(topo_lm), lwin=lwin0,kmax=count)
  #%%
  # Admittance and correlation between gravity and topography
  sgg,sgg_sd = sh.spectralanalysis.SHMultiTaperMaskSE(pot_lm.coeffs, tapers, lmaxt=lwin0, k=count, taper_wt = weight_opt_sgg)
```

**Comment by MarkWieczorek** [comment]
Hi there. I'm pretty sure that `SHMTVarOpt` only works with the spherical cap windows, and not with arbitrary domain windows. I'll need to look into this to convince myself, but after I do (in about a week), I'll  update the documentation to make this more clear.

**Comment by nlwagner** [comment]
Ah, thanks for the help!

**Comment by MarkWieczorek** [comment]
Confirmed. I added this to the function description "This routine only works using the tapers of the spherical cap concentration problem."
