### ISSUE TITLE
Earth2012 and Earth2014 not callable

### ISSUE THREAD

**Issue by Nikbert** [SHTOOLS/SHTOOLS#399]
**Description of the problem**

When loading the "Earth2012" or "Earth2014" Topography dataset via:
pysh.datasets.Earth.Earth2014()
I get the following Error:
"TypeError: 'module' object is not callable"

The Problem does not occur when loading "EGM2008" with pysh.datasets.Earth.EGM2008().

The Earth models seem to be still available under "https://ddfe.curtin.edu.au/models/".

All the best 
Nikbert

**Comment by MarkWieczorek** [comment]
Thanks for catching this. They changed the path of where these files are located and I just added fixed this in the develop branch:

https://github.com/SHTOOLS/SHTOOLS/pull/400

This will get merged into the master branch when we put out a new release in about a month or so.

**Comment by Nikbert** [comment]
Super! Thanks for the quick fix!
