### ISSUE TITLE
autopep8

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#4]
Could someone add either a script, or describe explicitly the commands that were used to autopep8 the python files here? This could perhaps be added to the wiki under "coding convections". This way we can try to ensure that new commits conform to this convection.

**Comment by ioshchepkov** [comment]
autopep8 is the tool itself: https://pypi.python.org/pypi/autopep8
I used this (from shell):
```shell
autopep8 --recursive --in-place --ignore=E501 **/*.py
```
then I checked some issues with pep8: https://pypi.python.org/pypi/pep8

It is quite simple and automated, but needs some work to do with unfixed issues. I'll try to do this part  simultaneously with the adding support for Python 3.

**Comment by MarkWieczorek** [comment]
I'm going to close this issue. I just copied the command and links to the shtools dev-doc repo.
