### ISSUE TITLE
Installation on Python 3.10.12 error: metadata-generation-failed, No module named 'numpy.distutils'

### ISSUE THREAD

**Issue by TasminSarkany** [SHTOOLS/SHTOOLS#412]
**Description of the problem**

I am trying to install pyshtools into a conda virtual environment on a Windows computer. When I install using pip as directed I get the following output:

```
Collecting pyshtools
  Using cached pyshtools-4.10.4.tar.gz (38.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      C:\Users\ts854\AppData\Local\Temp\pip-install-3euc_uox\pyshtools_916db3ab09934f74a095f04cc086ca28\setup.py:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources  # noqa: E402
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ts854\AppData\Local\Temp\pip-install-3euc_uox\pyshtools_916db3ab09934f74a095f04cc086ca28\setup.py", line 26, in <module>
          from numpy.distutils.core import setup  # noqa: E402
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Is there any way to resolve this error?

**System information**

Windows 10 64-bit
Python 3.10.12

**Packages installed in base environment:**

Name                    Version                Build channel
anyio                     4.0.0                    pypi_0    pypi
archspec                  0.2.1              pyhd3eb1b0_0
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.4.0                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
boltons                   23.0.0          py310haa95532_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotli-python             1.0.9           py310hd77b12b_7
bzip2                     1.0.8                he774522_0
ca-certificates           2023.08.22           haa95532_0
certifi                   2023.7.22       py310haa95532_0
cffi                      1.15.1          py310h2bbff1b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
colorama                  0.4.6           py310haa95532_0
comm                      0.1.4                    pypi_0    pypi
conda                     23.10.0         py310haa95532_0
conda-content-trust       0.1.3           py310haa95532_0
conda-libmamba-solver     23.11.0         py310haa95532_0
conda-package-handling    2.2.0           py310haa95532_0
conda-package-streaming   0.9.0           py310haa95532_0
console_shortcut_miniconda 0.1.1                haa95532_1
cryptography              39.0.1          py310h21b164f_2
cycler                    0.11.0             pyhd3eb1b0_0
debugpy                   1.7.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.14                   pypi_0    pypi
exceptiongroup            1.1.3                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.18.0                   pypi_0    pypi
fmt                       9.1.0                h6d14046_0
fonttools                 4.25.0             pyhd3eb1b0_0
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               ha860e81_0
giflib                    5.2.1                h8cc25b3_3
icu                       73.1                 h6c2663c_0
idna                      3.4             py310haa95532_0
intel-openmp              2023.1.0         h59b6b97_46320
ipykernel                 6.25.2                   pypi_0    pypi
ipython                   8.15.0                   pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.19.0                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
json5                     0.9.14                   pypi_0    pypi
jsonpatch                 1.32               pyhd3eb1b0_0
jsonpointer               2.1                pyhd3eb1b0_0
jsonschema                4.19.0                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
jupyter-client            8.3.1                    pypi_0    pypi
jupyter-core              5.3.1                    pypi_0    pypi
jupyter-events            0.7.0                    pypi_0    pypi
jupyter-lsp               2.2.0                    pypi_0    pypi
jupyter-server            2.7.3                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab                4.0.5                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.24.0                   pypi_0    pypi
kiwisolver                1.4.4           py310hd77b12b_0
krb5                      1.20.1               h5b6d351_0
lerc                      3.0                  hd77b12b_0
libarchive                3.6.2                hb62f4d4_2
libblas                   3.9.0                     8_mkl    conda-forge
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  14.0.6          default_hb5a9fac_1
libclang13                14.0.6          default_h8e68704_1
libcurl                   8.1.1                h86230a5_0
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.4                hd77b12b_0
libiconv                  1.16                 h2bbff1b_2
liblapack                 3.9.0                     8_mkl    conda-forge
libmamba                  1.5.3                hcd6fe79_0
libmambapy                1.5.3           py310h77c03ed_0
libpng                    1.6.39               h8cc25b3_0
libpq                     12.15                h906ac69_1
libsolv                   0.7.24               h23ce68f_0
libssh2                   1.10.0               he2ea4bf_2
libtiff                   4.5.1                hd77b12b_0
libwebp                   1.3.2                hbc33d0d_0
libwebp-base              1.3.2                h2bbff1b_0
libxml2                   2.10.4               h0ad7f3c_1
lz4-c                     1.9.4                h2bbff1b_0
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.5.3           py310h5588dad_2    conda-forge
matplotlib-base           3.5.3           py310hd77b12b_0
matplotlib-inline         0.1.6                    pypi_0    pypi
menuinst                  1.4.19          py310h59b6b97_0
mistune                   3.0.1                    pypi_0    pypi
mkl                       2020.4             hb70f87d_311    conda-forge
munkres                   1.1.4                      py_0
nbclient                  0.8.0                    pypi_0    pypi
nbconvert                 7.8.0                    pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
nest-asyncio              1.5.7                    pypi_0    pypi
notebook                  7.0.3                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numpy                     1.22.3          py310hed7ac4c_2    conda-forge
openjpeg                  2.4.0                h4fc8c34_0
openssl                   3.0.12               h2bbff1b_0
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.1            py310haa95532_0
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pcre2                     10.42                h0ff8eda_0
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.0.1          py310h045eedc_0
pip                       23.1.2          py310haa95532_0
platformdirs              3.10.0                   pypi_0    pypi
pluggy                    1.0.0           py310haa95532_1
ply                       3.11            py310haa95532_0
powershell_shortcut_miniconda 0.0.1                haa95532_1
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.39                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pybind11-abi              4                    hd3eb1b0_1
pycosat                   0.6.6           py310h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.16.1                   pypi_0    pypi
pyopenssl                 23.2.0          py310haa95532_0
pyparsing                 3.0.9           py310haa95532_0
pyqt                      5.15.10         py310hd77b12b_0
pyqt5-sip                 12.13.0         py310h2bbff1b_0
pysocks                   1.7.1           py310haa95532_0
python                    3.10.12              he1021f5_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-json-logger        2.0.7                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pywin32                   306                      pypi_0    pypi
pywinpty                  2.0.11                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.1                   pypi_0    pypi
qt-main                   5.15.2              h19c9488_10
referencing               0.30.2                   pypi_0    pypi
reproc                    14.2.4               hd77b12b_1
reproc-cpp                14.2.4               hd77b12b_1
requests                  2.31.0          py310haa95532_0
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rpds-py                   0.10.2                   pypi_0    pypi
ruamel.yaml               0.17.21         py310h2bbff1b_0
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1
send2trash                1.8.2                    pypi_0    pypi
setuptools                67.8.0          py310haa95532_0
sip                       6.7.12          py310hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
stack-data                0.6.2                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tomli                     2.0.1           py310haa95532_0
tornado                   6.3.3           py310h2bbff1b_0
tqdm                      4.65.0          py310h9909e9c_0
traitlets                 5.9.0                    pypi_0    pypi
truststore                0.8.0           py310haa95532_0
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.18         py310haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.2                    pypi_0    pypi
wheel                     0.38.4          py310haa95532_0
win_inet_pton             1.1.0           py310haa95532_0
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.2                h8cc25b3_0
yaml-cpp                  0.8.0                hd77b12b_0
zlib                      1.2.13               h8cc25b3_0
zstandard                 0.19.0          py310h2bbff1b_0
zstd                      1.5.5                hd43e919_0

**Packages installed in virtual environment I'm trying to install pyshtools into:**

Name                    Version                   Build  Channel
blas                      1.0                         mkl    conda-forge
bzip2                     1.0.8                he774522_0
ca-certificates           2023.08.22           haa95532_0
contourpy                 1.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
deprecated                1.2.14                   pypi_0    pypi
expat                     2.5.0                hd77b12b_0
fonttools                 4.44.1                   pypi_0    pypi
intel-openmp              2023.2.0         h57928b3_50497    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_0
libhwloc                  2.9.1                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libxml2                   2.10.4               h0ad7f3c_1
matplotlib                3.8.1                    pypi_0    pypi
mkl                       2023.2.0         h6a75c08_50497    conda-forge
mkl-service               2.4.0           py312h2bbff1b_1
numpy                     1.26.2                   pypi_0    pypi
numpy-base                1.26.0          py312h4dde369_0
openssl                   3.1.4                hcfcfb64_0    conda-forge
packaging                 23.2                     pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3            py312haa95532_0
plotly                    5.18.0                     py_0    plotly
plyfile                   1.0.2              pyhd8ed1ab_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pygments                  2.16.1                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.12.0               h1d929f7_0
python-dateutil           2.8.2                    pypi_0    pypi
setuptools                68.0.0          py312haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
tbb                       2021.9.0             h91493d7_0    conda-forge
tenacity                  8.2.2           py312haa95532_1
tk                        8.6.12               h2bbff1b_0
tzdata                    2023c                h04d1e81_0
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.2                 h21ff451_1
vc14_runtime              14.36.32532         hdcecf7f_17    conda-forge
vedo                      2023.4.6                 pypi_0    pypi
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
vtk                       9.3.0                    pypi_0    pypi
wheel                     0.41.2          py312haa95532_0
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.2                h8cc25b3_0
zlib                      1.2.13               h8cc25b3_0

**Comment by albrigc** [comment]
Did you manage to fix this issue, I am having some similar and unable to figure it out?

**Comment by TasminSarkany** [comment]
Since it is an issue with numpy.distutils.core and this has been changed between Python versions, I tried setting up a virtual environment in Python 3.11 and it worked. Maybe you can try the same thing and tell me if it solves the problem for you?
