### ISSUE TITLE
Meson can't determine version of pyshtools when installing from a source tarball

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#419]
**Description of the problem**

Python 3.12 no longer supports `distutils` and we are now using Meson and Meson-Python (https://github.com/mesonbuild/meson-python) as the backend for building pyshtools. Unfortunately, as far as I can tell, neither versioneer (https://github.com/python-versioneer/python-versioneer) nor setuptools_scm (https://setuptools-scm.readthedocs.io/en/latest/) are fully compatible with Meson-python: They either require using a setup.py file, or to use the `setuptools.build_meta` build-backend.

At the present time, we are setting the package version the following way https://github.com/SHTOOLS/SHTOOLS/pull/418:

In the main `meson.build` file, we set the version in the project function using
```
project('shtools', 'c', 'fortran',
  version: run_command(find_program('python3'), '-m', 'setuptools_scm').stdout().strip(),
  license: 'BSD-3-Clause',
  meson_version: '>=1.1.0',
  default_options: [
    'buildtype=release',
  ])
```
in the `pyproject.toml` file, we set
```
[project]
dynamic = ['version',]
```
and in `pyshtools/__init__.py` we set
```
try:
    __version__ = version('pyshtools')
except PackageNotFoundError:
    # package is not installed
    pass
```
This works fine when run within in git repository. However, when used in a source tarball, `setuptools_scm` fails to find a version, and hence meson fails to build the project.

What we need to do is to have the version info written to a file whenever a git archive command is used to generate a tarball, but I don't know how to do this. As a last resort, we could just set the version to something like `0.0.0` whenever `setuptools_scm` fails, but there has to be a better solution!

**Comment by QuLogic** [comment]
For downstreams, they can force the version for setuptools-scm with [`SETUPTOOLS_SCM_PRETEND_VERSION`](https://setuptools-scm.readthedocs.io/en/latest/overrides/).

For generating a versioned file when running `git archive`, there's https://setuptools-scm.readthedocs.io/en/latest/usage/#git-archives though I'm not sure how that interacts with meson-python or setuptools-scm run at build time.

**Comment by MarkWieczorek** [comment]
Here is a partial solution for the case where the tarball is generated by Meson : https://github.com/martinpitt/umockdev/commit/cf0d7b4cd0c74e99655c1bc57e2ca5f6ea99ba03#

To deal with the more generic case where the tarball is generated by git archive (or github), we would probably need to follow the approach as described in the above setuptools_scm git-archive docs.

**Comment by MarkWieczorek** [comment]
And here is a PR that uses versioneer... https://github.com/SHTOOLS/SHTOOLS/pull/439

This mostly works, but as described in the PR, when run from a tarball, the version is set to '0+unknown'. This is better than not building at all, but I think that we can do better!

**Comment by QuLogic** [comment]
I just came across [this `parentdir_prefix_version` option](https://setuptools-scm.readthedocs.io/en/latest/config/) in setuptools-scm which might be useful also? Basically if you get a GitHub archive, it'll have a directory named `$project-$version` and this option parses the version out of that parent directory name.

**Comment by MarkWieczorek** [comment]
Thanks! That seems to work. I also added a fallback method to 0.0.0 for the worst case. https://github.com/SHTOOLS/SHTOOLS/pull/460

```
parentdir_prefix_version = 'SHTOOLS-'
fallback_version = '0.0.0'
```
