### ISSUE TITLE
installing pyshtools lead to error: metadata-generation-failed (PyCharm)

### ISSUE THREAD

**Issue by Taras007** [SHTOOLS/SHTOOLS#445]
**Description of the problem**
After running the pip installs pyshtools appears the following:

**System information**
pip install pyshtools
Collecting pyshtools
  Using cached pyshtools-4.11.10.tar.gz (41.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      + meson setup C:\Users\Administrator\AppData\Local\Temp\pip-install-j70ft_68\pyshtools_239690ffa425420ab4347c2627d49415 C:\Users\Administrat
or\AppData\Local\Temp\pip-install-j70ft_68\pyshtools_239690ffa425420ab4347c2627d49415\.mesonpy-kv4n4ypj -Dbuildtype=release -Db_ndebug=if-release 
-Db_vscrt=md --default-library=static --native-file=C:\Users\Administrator\AppData\Local\Temp\pip-install-j70ft_68\pyshtools_239690ffa425420ab4347
c2627d49415\.mesonpy-kv4n4ypj\meson-python-native-file.ini
      The Meson build system
      Version: 1.3.1
      Source dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-j70ft_68\pyshtools_239690ffa425420ab4347c2627d49415
      Build dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-j70ft_68\pyshtools_239690ffa425420ab4347c2627d49415\.mesonpy-kv4n4ypj      
      Build type: native build
      Program python3 found: YES (C:\msys64\mingw64\bin\python3.EXE)
      WARNING: You should add the boolean check kwarg to the run_command call.
               It currently defaults to false,
               but it will default to true in future releases of meson.
               See also: https://github.com/mesonbuild/meson/issues/9300
      Project name: shtools
      Project version: 4.11.10
      Fortran compiler for the host machine: gfortran (gcc 13.2.0 "GNU Fortran (Rev4, Built by MSYS2 project) 13.2.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.42
      C compiler for the host machine: cc (gcc 13.2.0 "cc (Rev4, Built by MSYS2 project) 13.2.0")
      C linker for the host machine: cc ld.bfd 2.42
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Did not find pkg-config by name 'pkg-config'
      Found pkg-config: NO
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      Run-time dependency blas found: NO
     
      ..\meson.build:15:9: ERROR: Dependency lookup for BLAS with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving
 up.
     
      A full log can be found at C:\Users\Administrator\AppData\Local\Temp\pip-install-j70ft_68\pyshtools_239690ffa425420ab4347c2627d49415\.mesonp
y-kv4n4ypj\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by MarkWieczorek** [comment]
Please note that version 4.11.x is not fully released at this point. We are having issues building the wheels and conda packages, see:
* https://github.com/SHTOOLS/SHTOOLS/issues/417

What is happening for you is that pip is trying to compile from source, and for this you need to install some dependencies (see https://shtools.github.io/SHTOOLS/python-installing.html), such as cmake, blas/lapack, fftw. I do not use windows, so if you could provide us with the exact commands need to install the dependencies, I will add it to the online documentation.

Otherwise, the easiest would be to install the previous version of 4.10, which should work.

**Comment by Taras007** [comment]
From my side, everything is installed, including:  gfortran, BLAS/LAPACK (via openblas), and FFTW:

Administrator@home-pc CLANG64 ~
$
pacman -S mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-openblas mingw-w64-x86_64-fftw
warning: mingw-w64-x86_64-gcc-fortran-13.2.0-4 is up to date -- reinstalling
warning: mingw-w64-x86_64-openblas-0.3.26-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (3) mingw-w64-x86_64-fftw-3.3.10-5  mingw-w64-x86_64-gcc-fortran-13.2.0-4
             mingw-w64-x86_64-openblas-0.3.26-1

Total Download Size:     4.64 MiB
Total Installed Size:  182.25 MiB
Net Upgrade Size:       35.61 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 mingw-w64-x86_64-fftw-3.3....     4.6 MiB  1368 KiB/s 00:03 [###############################] 100%
(3/3) checking keys in keyring                               [###############################] 100%
(3/3) checking package integrity                             [###############################] 100%
(3/3) loading package files                                  [###############################] 100%
(3/3) checking for file conflicts                            [###############################] 100%
(3/3) checking available disk space                          [###############################] 100%
:: Processing package changes...
(1/3) reinstalling mingw-w64-x86_64-gcc-fortran              [###############################] 100%
(2/3) reinstalling mingw-w64-x86_64-openblas                 [###############################] 100%
(3/3) installing mingw-w64-x86_64-fftw                       [###############################] 100%

Thanks, I will try to install the previous version.

**Comment by MarkWieczorek** [comment]
And you have pkg-config and cmake installed too?

**Comment by MarkWieczorek** [comment]
Could you let me know if you were able to resolve this problem? We just put out a new version today (4.13.1), so you might want to try updating.
