### ISSUE TITLE
Error message when attempting to install pyshtools on Mac OS X 14.2.0

### ISSUE THREAD

**Issue by rklees** [SHTOOLS/SHTOOLS#450]
**Description of the problem**
When installing pyshtools on Mac OS X 14.2.0 I get the following error message:

Compiler stderr:
      <built-in>: error: unknown value ‘14.2.0’ of ‘-mmacosx-version-min’

The whole output is:
Collecting pyshtools
  Using cached pyshtools-4.11.10.tar.gz (41.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [390 lines of output]
      + meson setup /private/var/folders/zt/rg6420k534d3rzp028wjk_4r0000gn/T/pip-install-qs2mqsur/pyshtools_a642a2ec8c694a1b8b092f05dc3bc38e /private/var/folders/zt/rg6420k534d3rzp028wjk_4r0000gn/T/pip-install-qs2mqsur/pyshtools_a642a2ec8c694a1b8b092f05dc3bc38e/.mesonpy-nmkstgam -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --default-library=static --native-file=/private/var/folders/zt/rg6420k534d3rzp028wjk_4r0000gn/T/pip-install-qs2mqsur/pyshtools_a642a2ec8c694a1b8b092f05dc3bc38e/.mesonpy-nmkstgam/meson-python-native-file.ini
      The Meson build system
      Version: 1.3.2
      Source dir: /private/var/folders/zt/rg6420k534d3rzp028wjk_4r0000gn/T/pip-install-qs2mqsur/pyshtools_a642a2ec8c694a1b8b092f05dc3bc38e
      Build dir: /private/var/folders/zt/rg6420k534d3rzp028wjk_4r0000gn/T/pip-install-qs2mqsur/pyshtools_a642a2ec8c694a1b8b092f05dc3bc38e/.mesonpy-nmkstgam
      Build type: native build
      Program python3 found: YES (/Library/Frameworks/Python.framework/Versions/3.11/bin/python3)
      WARNING: You should add the boolean check kwarg to the run_command call.
               It currently defaults to false,
               but it will default to true in future releases of meson.
               See also: https://github.com/mesonbuild/meson/issues/9300
      Project name: shtools
      Project version: 4.11.10
      
      ../meson.build:1:0: ERROR: Unable to detect GNU compiler type:
      Compiler stdout:
      #define __DBL_MIN_EXP__ (-1021)
      #define __LDBL_MANT_DIG__ 53
      #define __UINT_LEAST16_MAX__ 0xffff
      #define __ARM_SIZEOF_WCHAR_T 4
      #define __ATOMIC_ACQUIRE 2
      #define __FLT128_MAX_10_EXP__ 4932
      #define __FLT_MIN__ 1.17549435082228750796873653722224568e-38F
      #define __GCC_IEC_559_COMPLEX 2
      #define __UINT_LEAST8_TYPE__ unsigned char
      #define __INTMAX_C(c) c ## L
      #define __CHAR_BIT__ 8
      #define __UINT8_MAX__ 0xff
      #define __USER_LABEL_PREFIX__ _
      #define __WINT_MAX__ 0x7fffffff
      #define __WCHAR_MAX__ 0x7fffffff
      #define __CONSTANT_CFSTRINGS__ 1
      #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
      #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
      #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
      #define __GCC_ATOMIC_CHAR_LOCK_FREE 2
      #define __GCC_IEC_559 2
      #define __FLT32X_DECIMAL_DIG__ 17
      #define __FLT_EVAL_METHOD__ 0
      #define __FLT64_DECIMAL_DIG__ 17
      #define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
      #define __UINT_FAST32_TYPE__ unsigned int
      #define __UINT_FAST64_MAX__ 0xffffffffffffffffULL
      #define __SIG_ATOMIC_TYPE__ int
      #define __DBL_MIN_10_EXP__ (-307)
      #define __FINITE_MATH_ONLY__ 0
      #define __FLT32X_MAX_EXP__ 1024
      #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
      #define __GNUC_PATCHLEVEL__ 0
      #define __FLT32_HAS_DENORM__ 1
      #define __UINT_FAST8_MAX__ 0xff
      #define __FLT32_MAX_10_EXP__ 38
      #define __INT8_C(c) c
      #define __INT_LEAST8_WIDTH__ 8
      #define __UINT_LEAST64_MAX__ 0xffffffffffffffffULL
      #define __SHRT_MAX__ 0x7fff
      #define __LDBL_MAX__ 1.79769313486231570814527423731704357e+308L
      #define __ARM_FEATURE_IDIV 1
      #define __FLT64X_MAX_10_EXP__ 4932
      #define __FLT64_NORM_MAX__ 1.79769313486231570814527423731704357e+308F64
      #define __LDBL_IS_IEC_60559__ 2
      #define __ARM_FP 14
      #define __FLT64X_IS_IEC_60559__ 2
      #define __FLT64X_HAS_QUIET_NAN__ 1
      #define __WINT_TYPE__ int
      #define __UINT_LEAST8_MAX__ 0xff
      #define __FLT128_DENORM_MIN__ 6.47517511943802511092443895822764655e-4966F128
      #define __APPLE_CC__ 1
      #define __UINTMAX_TYPE__ long unsigned int
      #define __FLT_EVAL_METHOD_TS_18661_3__ 0
      #define __UINT32_MAX__ 0xffffffffU
      #define __DBL_DENORM_MIN__ ((double)4.94065645841246544176568792868221372e-324L)
      #define __AARCH64_CMODEL_SMALL__ 1
      #define __LDBL_MAX_EXP__ 1024
      #define __INT_FAST32_WIDTH__ 32
      #define __FLT128_MIN_EXP__ (-16381)
      #define __FLT128_MIN_10_EXP__ (-4931)
      #define __FLT32X_IS_IEC_60559__ 2
      #define __INT_LEAST16_WIDTH__ 16
      #define __SCHAR_MAX__ 0x7f
      #define __FLT128_MANT_DIG__ 113
      #define __DBL_MAX__ ((double)1.79769313486231570814527423731704357e+308L)
      #define __WCHAR_MIN__ (-__WCHAR_MAX__ - 1)
      #define __INT64_C(c) c ## LL
      #define __GCC_ATOMIC_POINTER_LOCK_FREE 2
      #define __FLT_MAX__ 3.40282346638528859811704183484516925e+38F
      #define __SIZEOF_INT__ 4
      #define __FLT32X_MANT_DIG__ 53
      #define __FLT64X_EPSILON__ 1.92592994438723585305597794258492732e-34F64x
      #define __STDC_HOSTED__ 1
      #define __DBL_DIG__ 15
      #define __FLT32_DIG__ 6
      #define __FLT_EPSILON__ 1.19209289550781250000000000000000000e-7F
      #define __SHRT_WIDTH__ 16
      #define __FLT32_IS_IEC_60559__ 2
      #define __LDBL_MIN__ 2.22507385850720138309023271733240406e-308L
      #define __STDC_UTF_16__ 1
      #define __DBL_IS_IEC_60559__ 2
      #define __FLT16_HAS_QUIET_NAN__ 1
      #define __strong
      #define __ARM_SIZEOF_MINIMAL_ENUM 4
      #define __FLT64X_DENORM_MIN__ 6.47517511943802511092443895822764655e-4966F64x
      #define __FP_FAST_FMA 1
      #define __FLT32X_HAS_INFINITY__ 1
      #define __INT32_MAX__ 0x7fffffff
      #define __FLT16_DIG__ 3
      #define __INT_WIDTH__ 32
      #define __SIZEOF_LONG__ 8
      #define __APPLE__ 1
      #define __UINT16_C(c) c
      #define __DECIMAL_DIG__ 17
      #define __FLT64_EPSILON__ 2.22044604925031308084726333618164062e-16F64
      #define __INT16_MAX__ 0x7fff
      #define __FLT128_IS_IEC_60559__ 2
      #define __FLT64X_MIN_10_EXP__ (-4931)
      #define __LDBL_HAS_QUIET_NAN__ 1
      #define __FLT16_MIN_EXP__ (-13)
      #define __FLT64_MANT_DIG__ 53
      #define __FLT64X_MANT_DIG__ 113
      #define __DYNAMIC__ 1
      #define __GNUC__ 12
      #define __FLT16_DECIMAL_DIG__ 5
      #define __FLT_HAS_DENORM__ 1
      #define __SIZEOF_LONG_DOUBLE__ 8
      #define __FLT64_MAX_10_EXP__ 308
      #define __FLT16_MAX_10_EXP__ 4
      #define __INT_FAST32_MAX__ 0x7fffffff
      #define __DBL_HAS_INFINITY__ 1
      #define __INT64_MAX__ 0x7fffffffffffffffLL
      #define __HAVE_SPECULATION_SAFE_VALUE 1
      #define __INTPTR_WIDTH__ 64
      #define __FLT64X_HAS_INFINITY__ 1
      #define __FLT32X_HAS_DENORM__ 1
      #define __INT_FAST16_TYPE__ short int
      #define __LDBL_HAS_DENORM__ 1
      #define __FLT128_HAS_INFINITY__ 1
      #define __weak
      #define __DBL_MAX_EXP__ 1024
      #define __WCHAR_WIDTH__ 32
      #define __FLT32_MAX__ 3.40282346638528859811704183484516925e+38F32
      #define __GCC_ATOMIC_LONG_LOCK_FREE 2
      #define __FLT32_HAS_QUIET_NAN__ 1
      #define __LONG_LONG_MAX__ 0x7fffffffffffffffLL
      #define __SIZEOF_SIZE_T__ 8
      #define __SIG_ATOMIC_WIDTH__ 32
      #define __ARM_ALIGN_MAX_PWR 28
      #define __SIZEOF_WINT_T__ 4
      #define __LONG_LONG_WIDTH__ 64
      #define __FLT32_MAX_EXP__ 128
      #define __ARM_FP16_FORMAT_IEEE 1
      #define __FP_FAST_FMAF32x 1
      #define __FLT_MIN_EXP__ (-125)
      #define __FLT32X_MIN_EXP__ (-1021)
      #define __INT_FAST64_TYPE__ long long int
      #define __ARM_FP16_ARGS 1
      #define __DBL_DECIMAL_DIG__ 17
      #define __FP_FAST_FMAF 1
      #define __FLT128_NORM_MAX__ 1.18973149535723176508575932662800702e+4932F128
      #define __FP_FAST_FMAL 1
      #define __FLT64_DENORM_MIN__ 4.94065645841246544176568792868221372e-324F64
      #define __DBL_MIN__ ((double)2.22507385850720138309023271733240406e-308L)
      #define __ARM_FEATURE_CLZ 1
      #define __FLT16_DENORM_MIN__ 5.96046447753906250000000000000000000e-8F16
      #define __FLT64X_NORM_MAX__ 1.18973149535723176508575932662800702e+4932F64x
      #define __SIZEOF_POINTER__ 8
      #define __SIZE_TYPE__ long unsigned int
      #define __LP64__ 1
      #define __DBL_HAS_QUIET_NAN__ 1
      #define __FLT_EVAL_METHOD_C99__ 0
      #define __FLT32X_EPSILON__ 2.22044604925031308084726333618164062e-16F32x
      #define __FLT64_MIN_EXP__ (-1021)
      #define __LDBL_DECIMAL_DIG__ 17
      #define __aarch64__ 1
      #define __FLT64_MIN_10_EXP__ (-307)
      #define __INT_FAST64_WIDTH__ 64
      #define __FLT64X_DECIMAL_DIG__ 36
      #define __REGISTER_PREFIX__
      #define __UINT16_MAX__ 0xffff
      #define __INTMAX_WIDTH__ 64
      #define __GXX_ABI_VERSION 1017
      #define __AARCH64EL__ 1
      #define __LDBL_HAS_INFINITY__ 1
      #define __UINT8_TYPE__ unsigned char
      #define __FLT_DIG__ 6
      #define __NO_INLINE__ 1
      #define __DEC_EVAL_METHOD__ 2
      #define __FLT_MANT_DIG__ 24
      #define __FLT16_MIN_10_EXP__ (-4)
      #define __VERSION__ "12.1.0"
      #define __UINT64_C(c) c ## ULL
      #define __INT_LEAST32_MAX__ 0x7fffffff
      #define __GCC_ATOMIC_INT_LOCK_FREE 2
      #define __FLT128_MAX_EXP__ 16384
      #define __FLT32_MANT_DIG__ 24
      #define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
      #define __FLT16_MAX_EXP__ 16
      #define __BIGGEST_ALIGNMENT__ 16
      #define __INT32_C(c) c
      #define __FLT128_HAS_DENORM__ 1
      #define __FLT128_DIG__ 33
      #define __SCHAR_WIDTH__ 8
      #define __ORDER_PDP_ENDIAN__ 3412
      #define __ARM_64BIT_STATE 1
      #define __INT_FAST32_TYPE__ int
      #define __FLT128_MIN__ 3.36210314311209350626267781732175260e-4932F128
      #define __UINT_LEAST16_TYPE__ short unsigned int
      #define __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ 1000
      #define __UINT64_MAX__ 0xffffffffffffffffULL
      #define __FLT_IS_IEC_60559__ 2
      #define __GNUC_WIDE_EXECUTION_CHARSET_NAME "UTF-32LE"
      #define __FLT64X_DIG__ 33
      #define __ARM_FEATURE_FMA 1
      #define __INT8_TYPE__ signed char
      #define __GCC_ASM_FLAG_OUTPUTS__ 1
      #define __arm64__ 1
      #define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
      #define __FLT_RADIX__ 2
      #define __INT_LEAST16_TYPE__ short int
      #define __ARM_ARCH_PROFILE 65
      #define __LDBL_EPSILON__ 2.22044604925031308084726333618164062e-16L
      #define __UINTMAX_C(c) c ## UL
      #define __ARM_PCS_AAPCS64 1
      #define __SIG_ATOMIC_MAX__ 0x7fffffff
      #define __INT_LEAST64_WIDTH__ 64
      #define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
      #define __SIZEOF_PTRDIFF_T__ 8
      #define __arm64 1
      #define __ATOMIC_RELAXED 0
      #define __LDBL_DIG__ 15
      #define __FLT64_IS_IEC_60559__ 2
      #define __FLT16_IS_IEC_60559__ 2
      #define __INT_FAST16_MAX__ 0x7fff
      #define __GCC_CONSTRUCTIVE_SIZE 64
      #define __FLT64_DIG__ 15
      #define __UINT_FAST32_MAX__ 0xffffffffU
      #define __UINT_LEAST64_TYPE__ long long unsigned int
      #define __FLT16_EPSILON__ 9.76562500000000000000000000000000000e-4F16
      #define __FLT_HAS_QUIET_NAN__ 1
      #define __FLT_MAX_10_EXP__ 38
      #define __LONG_MAX__ 0x7fffffffffffffffL
      #define __FLT64X_HAS_DENORM__ 1
      #define __FLT_HAS_INFINITY__ 1
      #define __GNUC_EXECUTION_CHARSET_NAME "UTF-8"
      #define __DBL_HAS_DENORM__ 1
      #define __UINT_FAST16_TYPE__ short unsigned int
      #define __FLT32X_HAS_QUIET_NAN__ 1
      #define __CHAR16_TYPE__ short unsigned int
      #define __PRAGMA_REDEFINE_EXTNAME 1
      #define __SIZE_WIDTH__ 64
      #define __INT_LEAST16_MAX__ 0x7fff
      #define __FLT16_NORM_MAX__ 6.55040000000000000000000000000000000e+4F16
      #define __FLT32_DENORM_MIN__ 1.40129846432481707092372958328991613e-45F32
      #define __INT_LEAST64_TYPE__ long long int
      #define __INT16_TYPE__ short int
      #define __INT_LEAST8_TYPE__ signed char
      #define __FLT16_MAX__ 6.55040000000000000000000000000000000e+4F16
      #define __STDC_VERSION__ 201710L
      #define __INT_FAST8_MAX__ 0x7f
      #define __ARM_ARCH 8
      #define __FLT128_MAX__ 1.18973149535723176508575932662800702e+4932F128
      #define __INTPTR_MAX__ 0x7fffffffffffffffL
      #define __FLT64_HAS_QUIET_NAN__ 1
      #define __INTMAX_TYPE__ long int
      #define __FLT64X_MIN_EXP__ (-16381)
      #define __FLT32_MIN_10_EXP__ (-37)
      #define __FLT32X_DIG__ 15
      #define __PTRDIFF_WIDTH__ 64
      #define __FLT64_HAS_INFINITY__ 1
      #define __FLT64X_MAX__ 1.18973149535723176508575932662800702e+4932F64x
      #define __FLT16_HAS_INFINITY__ 1
      #define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
      #define __PTRDIFF_MAX__ 0x7fffffffffffffffL
      #define __FLT16_MANT_DIG__ 11
      #define __INTPTR_TYPE__ long int
      #define __UINT16_TYPE__ short unsigned int
      #define __WCHAR_TYPE__ int
      #define __pic__ 2
      #define __UINTPTR_MAX__ 0xffffffffffffffffUL
      #define __ARM_ARCH_8A 1
      #define __ARM_FEATURE_UNALIGNED 1
      #define __FLT32_DECIMAL_DIG__ 9
      #define __INT_FAST64_MAX__ 0x7fffffffffffffffLL
      #define __FLT_NORM_MAX__ 3.40282346638528859811704183484516925e+38F
      #define __FLT32_HAS_INFINITY__ 1
      #define __FLT64X_MAX_EXP__ 16384
      #define __UINT_FAST64_TYPE__ long long unsigned int
      #define __INT_MAX__ 0x7fffffff
      #define __INT64_TYPE__ long long int
      #define __FLT_MAX_EXP__ 128
      #define __ORDER_BIG_ENDIAN__ 4321
      #define __DBL_MANT_DIG__ 53
      #define __INT_LEAST64_MAX__ 0x7fffffffffffffffLL
      #define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
      #define __FP_FAST_FMAF32 1
      #define __UINT_LEAST32_TYPE__ unsigned int
      #define __SIZEOF_SHORT__ 2
      #define __FLT32_NORM_MAX__ 3.40282346638528859811704183484516925e+38F32
      #define __LDBL_MIN_EXP__ (-1021)
      #define __GCC_ATOMIC_BOOL_LOCK_FREE 2
      #define __FLT64_MAX__ 1.79769313486231570814527423731704357e+308F64
      #define __MACH__ 1
      #define __LITTLE_ENDIAN__ 1
      #define __WINT_WIDTH__ 32
      #define __FP_FAST_FMAF64 1
      #define __INT_LEAST8_MAX__ 0x7f
      #define __FLT32X_MAX_10_EXP__ 308
      #define __SIZEOF_INT128__ 16
      #define __FLT16_MIN__ 6.10351562500000000000000000000000000e-5F16
      #define __LDBL_MAX_10_EXP__ 308
      #define __DBL_EPSILON__ ((double)2.22044604925031308084726333618164062e-16L)
      #define __FLT32_MIN_EXP__ (-125)
      #define _LP64 1
      #define __UINT8_C(c) c
      #define __FLT64_MAX_EXP__ 1024
      #define __INT_LEAST32_TYPE__ int
      #define __SIZEOF_WCHAR_T__ 4
      #define __UINT64_TYPE__ long long unsigned int
      #define __ARM_NEON 1
      #define __FLT128_HAS_QUIET_NAN__ 1
      #define __INTMAX_MAX__ 0x7fffffffffffffffL
      #define __UINT_FAST8_TYPE__ unsigned char
      #define __INT_FAST8_TYPE__ signed char
      #define __FLT64X_MIN__ 3.36210314311209350626267781732175260e-4932F64x
      #define __GNUC_STDC_INLINE__ 1
      #define __FLT64_HAS_DENORM__ 1
      #define __FLT32_EPSILON__ 1.19209289550781250000000000000000000e-7F32
      #define __FLT16_HAS_DENORM__ 1
      #define __STDC_UTF_32__ 1
      #define __INT_FAST8_WIDTH__ 8
      #define __FLT32X_MAX__ 1.79769313486231570814527423731704357e+308F32x
      #define __DBL_NORM_MAX__ ((double)1.79769313486231570814527423731704357e+308L)
      #define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
      #define __ARM_ALIGN_MAX_STACK_PWR 16
      #define __LDBL_DENORM_MIN__ 4.94065645841246544176568792868221372e-324L
      #define __GCC_DESTRUCTIVE_SIZE 256
      #define __UINT32_C(c) c ## U
      #define __FLT32X_MIN__ 2.22507385850720138309023271733240406e-308F32x
      #define __WINT_MIN__ (-__WINT_MAX__ - 1)
      #define __INT8_MAX__ 0x7f
      #define __LONG_WIDTH__ 64
      #define __PIC__ 2
      #define __FLT32X_NORM_MAX__ 1.79769313486231570814527423731704357e+308F32x
      #define __CHAR32_TYPE__ unsigned int
      #define __ARM_FEATURE_NUMERIC_MAXMIN 1
      #define __INT32_TYPE__ int
      #define __SIZEOF_DOUBLE__ 8
      #define __FLT64_MIN__ 2.22507385850720138309023271733240406e-308F64
      #define __FLT_DENORM_MIN__ 1.40129846432481707092372958328991613e-45F
      #define __INT_LEAST32_WIDTH__ 32
      #define __SIZEOF_FLOAT__ 4
      #define __ATOMIC_CONSUME 1
      #define __GNUC_MINOR__ 1
      #define __INT_FAST16_WIDTH__ 16
      #define __UINTMAX_MAX__ 0xffffffffffffffffUL
      #define __FLT32X_DENORM_MIN__ 4.94065645841246544176568792868221372e-324F32x
      #define __DBL_MAX_10_EXP__ 308
      #define __INT16_C(c) c
      #define __ARM_ARCH_ISA_A64 1
      #define __STDC__ 1
      #define __PTRDIFF_TYPE__ long int
      #define __FLT32_MIN__ 1.17549435082228750796873653722224568e-38F32
      #define __ATOMIC_SEQ_CST 5
      #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_16 1
      #define __UINT32_TYPE__ unsigned int
      #define __FLT32X_MIN_10_EXP__ (-307)
      #define __UINTPTR_TYPE__ long unsigned int
      #define __LDBL_MIN_10_EXP__ (-307)
      #define __FLT128_EPSILON__ 1.92592994438723585305597794258492732e-34F128
      #define __SIZEOF_LONG_LONG__ 8
      #define __FLT128_DECIMAL_DIG__ 36
      #define __GCC_ATOMIC_LLONG_LOCK_FREE 2
      #define __FLT_DECIMAL_DIG__ 9
      #define __UINT_FAST16_MAX__ 0xffff
      #define __LDBL_NORM_MAX__ 1.79769313486231570814527423731704357e+308L
      #define __FLT_MIN_10_EXP__ (-37)
      #define __GCC_ATOMIC_SHORT_LOCK_FREE 2
      #define __ORDER_LITTLE_ENDIAN__ 1234
      #define __SIZE_MAX__ 0xffffffffffffffffUL
      #define __UINT_LEAST32_MAX__ 0xffffffffU
      #define __ATOMIC_ACQ_REL 4
      #define __ATOMIC_RELEASE 3
      
      -----
      Compiler stderr:
      <built-in>: error: unknown value ‘14.2.0’ of ‘-mmacosx-version-min’
      
      -----
      
      
      A full log can be found at /private/var/folders/zt/rg6420k534d3rzp028wjk_4r0000gn/T/pip-install-qs2mqsur/pyshtools_a642a2ec8c694a1b8b092f05dc3bc38e/.mesonpy-nmkstgam/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Any idea of how to fix this?

**System information**
MacBook Pro with Apple M1 Pro chip
Mac OS X 14.2.0

**Comment by MarkWieczorek** [comment]
what is the command you are using to install pyshtools?

**Comment by rklees** [comment]
pip install pyshtools --no-binary pyshtools


From: markwieczorek ***@***.***>
Reply to: SHTOOLS/SHTOOLS ***@***.***>
Date: Monday, 4 March 2024 at 11:03
To: SHTOOLS/SHTOOLS ***@***.***>
Cc: Roland Klees ***@***.***>, Author ***@***.***>
Subject: Re: [SHTOOLS/SHTOOLS] Error message when attempting to install pyshtools on Mac OS X 14.2.0 (Issue #450)


You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


what is the command you are using to install pyshtools?

**Comment by MarkWieczorek** [comment]
I would first try cloning the repo and then doing a `pip install -v .` in the directory (see the build from source instructions here: https://shtools.github.io/SHTOOLS/python-installing.html). But that probably won't work.

Then, try installing gcc with brew `brew install gcc`. There is probably a gcc on conda-forge too.

I use this on macos, so there is probably an easy solution to this!

**Comment by rklees** [comment]
Will do that and let you know. gcc installation should be with Xcode, but let me see.
Roland

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MarkWieczorek** [comment]
apples gcc that comes with xcode doesn't have a fortran compiler.

**Comment by rklees** [comment]
I did

sudo port install gcc12

which installed gcc12 using MacPorts. Then, I did

pip install pyshtools

and got the same error message as I already posted.

Roland

From: markwieczorek ***@***.***>
Reply to: SHTOOLS/SHTOOLS ***@***.***>
Date: Monday, 4 March 2024 at 14:50
To: SHTOOLS/SHTOOLS ***@***.***>
Cc: Roland Klees ***@***.***>, Author ***@***.***>
Subject: Re: [SHTOOLS/SHTOOLS] Error message when attempting to install pyshtools on Mac OS X 14.2.0 (Issue #450)


You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


apples gcc that comes with xcode doesn't have a fortran compiler.

**Comment by rklees** [comment]
I uninstalled XCODE and CommandLineTools. Then I installed CommandLineTools. Unfortunately, got exactly the same error message.
Roland

From: markwieczorek ***@***.***>
Reply to: SHTOOLS/SHTOOLS ***@***.***>
Date: Monday, 4 March 2024 at 21:12
To: SHTOOLS/SHTOOLS ***@***.***>
Cc: Roland Klees ***@***.***>, Author ***@***.***>
Subject: Re: [SHTOOLS/SHTOOLS] Error message when attempting to install pyshtools on Mac OS X 14.2.0 (Issue #450)


You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


The only think that I could suggest would be to uninstall and reinstall the XCode command line utilities. It appears that some people had success in fixing a similar error on another project: https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target/65094410#65094410<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F63972113%2Fbig-sur-clang-invalid-version-error-due-to-macosx-deployment-target%2F65094410%2365094410&data=05%7C02%7Cr.klees%40tudelft.nl%7Cd2d67f3aa0514040221708dc3c876173%7C096e524d692940308cd38ab42de0887b%7C0%7C0%7C638451799344880693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=4OuGfg9miskTPnMB6eTqDz7DfkxgWTOcyw%2Bc7WO4jlY%3D&reserved=0>

**Comment by rklees** [comment]
Maybe that this message points to the problem:


../meson.build:1:0: ERROR: Unable to detect GNU compiler type:

Any idea what GNU compiler meson refers to and how to fix this?

Roland

From: markwieczorek ***@***.***>
Reply to: SHTOOLS/SHTOOLS ***@***.***>
Date: Monday, 4 March 2024 at 21:12
To: SHTOOLS/SHTOOLS ***@***.***>
Cc: Roland Klees ***@***.***>, Author ***@***.***>
Subject: Re: [SHTOOLS/SHTOOLS] Error message when attempting to install pyshtools on Mac OS X 14.2.0 (Issue #450)


You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


The only think that I could suggest would be to uninstall and reinstall the XCode command line utilities. It appears that some people had success in fixing a similar error on another project: https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target/65094410#65094410<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F63972113%2Fbig-sur-clang-invalid-version-error-due-to-macosx-deployment-target%2F65094410%2365094410&data=05%7C02%7Cr.klees%40tudelft.nl%7Cd2d67f3aa0514040221708dc3c876173%7C096e524d692940308cd38ab42de0887b%7C0%7C0%7C638451799344880693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=4OuGfg9miskTPnMB6eTqDz7DfkxgWTOcyw%2Bc7WO4jlY%3D&reserved=0>

**Comment by MarkWieczorek** [comment]
Sorry, I don't know. That only other thing that I would suggest is to install conda and create a clean environment before installing pyshtools. Its possible that the default macos python is causing problems, or that there are some weird conflicts with packages that you already installed on your machine.

**Comment by MarkWieczorek** [comment]
I am going to close this, as it appears that you resolved this issue. Please note that we just put out a new release today (4.13.1). If you encounter any other problems, please open a new issue.
