### ISSUE TITLE
pypi package

### ISSUE THREAD

**Issue by MMesch** [SHTOOLS/SHTOOLS#46]
I just made a test upload to this test site:
https://testpypi.python.org/pypi/pyshtools/3.3

Unfortunately, this command:
```pip install -i https://testpypi.python.org/pypi pyshtools```

fails with this message:
```
Collecting pyshtools
  Using cached https://testpypi.python.org/packages/fa/36/1e02150908daa6d2f23fc7747d50b5a879e824bb1b107821275bc8d8719a/pyshtools-3.3.tar.gz
    Complete output from command python setup.py egg_info:
    customize Gnu95FCompiler
    Found executable /usr/bin/gfortran
    customize Gnu95FCompiler
    searching SHTOOLS in: build/temp.linux-x86_64-2.7
    non-existing path in '': 'src/pyshtools.pyf'
    non-existing path in '': 'build/temp.linux-x86_64-2.7'
    non-existing path in '': 'build/temp.linux-x86_64-2.7'
    running egg_info
    running build_src
    build_src
    building library "SHTOOLS" sources
    building extension "pyshtools._SHTOOLS" sources
      target build/src.linux-x86_64-2.7/src/_SHTOOLSmodule.c does not exist:
       Assuming _SHTOOLSmodule.c was generated with "build_src --inplace" command.
       Yes! Using 'src/_SHTOOLSmodule.c' as up-to-date target.
    f2py options: ['--quiet', '--quiet']
      adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
      adding 'build/src.linux-x86_64-2.7' to include_dirs.
    error: f2py target_c file 'build/src.linux-x86_64-2.7/fortranobject.c' not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5D43ZE/pyshtools/
```

It seems that setup.py doesn't find the correct directory. Any ideas?

I followed this tutorial to upload it:
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by MMesch** [comment]
Other points that need to be adjusted:

* the version number has to be specified explicitely in ```setup.py```:
```
...
    name='pyshtools',
    version='3.3',
    description='SHTOOLS - Tools for working with spherical harmonics',
...
```
* the ```README.md``` description is ugly on the pypi website and needs to be adapted

**Comment by ioshchepkov** [comment]
There is  no `src/pyshtools.pyf` in the pypi archive, I think we need to add this in Manifest.in file

**Comment by MMesch** [comment]
thx @ioshchepkov . That was the issue. It works now with:

``` pip install -i https://testpypi.python.org/pypi pyshtools```

As soon as Mark returns from vacation, we can put it onto the actual pypi server ...

**Comment by MMesch** [comment]
documentation looks fine now as well but Pandoc needs to be installed before the upload:

https://testpypi.python.org/pypi/pyshtools/3.3.2

**Comment by MMesch** [comment]
see #47

**Comment by MarkWieczorek** [comment]
can we close this issue?
