### ISSUE TITLE
Plotting methods in `shclasses` use deprecated matplotlib function `matplotlib.cm.get_cmap`

### ISSUE THREAD

**Issue by spicydonkey** [SHTOOLS/SHTOOLS#477]
**Description of the problem**

Plotting methods in `shclasses` use deprecated matplotlib function `matplotlib.cm.get_cmap`, detailed in https://github.com/matplotlib/matplotlib/issues/20853.

There may be more deprecated calls to matplotlib, but this is the only one I found.

**Comment by QuLogic** [comment]
Those was already removed in #472 (note, GitHub searches the default `master` branch, but this is in `develop` only.)
