### ISSUE TITLE
plotgmt does not work for grids with extend=False

### ISSUE THREAD

**Issue by ValentinBonnetGibet** [SHTOOLS/SHTOOLS#489]
**Description of the problem**
I tried to open data from Beuthe et al. 2020 (https://zenodo.org/records/3727115)

```
file = 'Data_map/CrustalThickness_mercury/CrustalThickness_ModelV4.dat'
thick = pysh.SHGrid.from_file(file)
fig = thick.plotgmt()
```

the result : 

![image](https://github.com/user-attachments/assets/68b2a378-dc1c-4d87-8825-5de870f0506f)

but if I use : 

`thick = pysh.SHGrid.from_file(file).expand().expand()`

 it works (thanks Adrien for the trick). 
![image](https://github.com/user-attachments/assets/3f692cd6-8635-4053-8fd4-96b917fdc498)

 The only difference I see is that 
`extend = False`
in the first case and
`extend = True`
in the second case. The problem is only with plotgmt(), it works well with plot().

Valentin B

**System information**

**Comment by MarkWieczorek** [comment]
https://github.com/GenericMappingTools/pygmt/issues/3331

**Comment by MarkWieczorek** [comment]
This has been fixed upstream in gmt, so I am going to close this.
