### ISSUE TITLE
Compile/install issues with f2py and scipy_distutils

### ISSUE THREAD

**Issue by astrobradley** [SHTOOLS/SHTOOLS#5]
I'm attempting to install the SHTOOLS package on a Linux machine, and I'm having trouble with f2py and scipy_distutils.

I found the f2py executable from https://sysbio.ioc.ee/projects/f2py2e/, and installed it according to instructions (python setup.py install).  I found the scipy_distutils package from the same source and installed it according to instructions (python setup.py install).

I added the /usr/lib/python2.4/site-packages paths to my Python path so that the f2py and scipy_distutils modules could be used.

I then ran "make F2PY="/usr/bin/f2py" to point the F2PY environment variable to the correct location.  make finds f2py just fine, but has a problem with scipy_distutils.  The relevant portion of the output is below.  It appeared that scipy_distutils installed successfully (no errors), and the package seems to have installed to the appropriate location.  There doesn't seem to be a module named "scipy_distutils," though the subroutines (e.g build_src) seem to exist in the install location.

I've seen that scipy_distutils and f2py are no longer maintained as standalone packages, and are now included in numpy.  What am I missing to be able to install SHTOOLS properly?  Thank you!

-Nick

MAKE OF FORTRAN COMPONENT SUCCESSFUL!

/usr/bin/f2py --quiet -Imodules -Llib --f90flags="-m64 -fPIC -O3 -ffast-math" \
                -c src/pyshtools.pyf src/PythonWrapper.f95\
                -lSHTOOLS -lfftw3 -lm -llapack  -lblas
Traceback (most recent call last):
  File "/usr/bin/f2py", line 4, in ?
    f2py2e.main()
  File "/usr/lib/python2.4/site-packages/f2py2e/f2py2e.py", line 677, in main
    run_compile()
  File "/usr/lib/python2.4/site-packages/f2py2e/f2py2e.py", line 579, in run_compile
    from scipy_distutils.command.build_src import get_f2py_modulename
ImportError: No module named scipy_distutils.command.build_src
make: *** [all] Error 1

**Comment by ioshchepkov** [comment]
What reason do you have to not use numpy's version of the f2py package?

**Comment by astrobradley** [comment]
The SHTOOLS installation instructions specify that one must point to the f2py executable, not the numpy version.  I ran "make all" originally, and the installation failed on a call to f2py, since the executable didn't exist.

I should add that the installation using "brew" worked just fine on Mac OS - I'm trying to do a manual install from the source code on a Linux machine.

**Comment by MMesch** [comment]
Hi,

I think it is best to use the numpy version. f2py should just be in the PATH of your computer.

Was the problem resolved?

**Comment by elmerehbi** [comment]
@MMesch I just installed Ubuntu 14.04and got stuck here. I have Anaconda and updated numpy to the latest version with conda. Running make spits an error that it cannot find f2py.

You mention it should be in the PATH of the computer. How can I check that and what should I do here?

**Comment by MMesch** [comment]
Yes. anaconda for python3 has the f2py3 executable instead of f2py. At the moment SHTOOLS supports python 2.7  only ! To support python 3, we have to check the syntax of __init__.py and the python examples as well as adjusting the Makefile to find the correct f2py variable...

**Comment by MarkWieczorek** [comment]
If you do not have an f2py binary, a work around is to use the following:

~~~~
make F2PY="python -m numpy.f2py" F2PY3="python3 -m numpy.f2py"
~~~~

**Comment by MMesch** [comment]
This should be fixed in the new version with ```setup.py```
