### ISSUE TITLE
Installing SHTOOLS on Linux

### ISSUE THREAD

**Issue by astrobradley** [SHTOOLS/SHTOOLS#6]
Hi,

I am trying to install SHTOOLS on a Linux machine, and am running into difficulties.  All the supporting libraries and executables are installed, but make fails on a gfortran compilation call.  The make output is pasted below.  

Is it possible to install SHTOOLS on a Linux machine?  Does anyone have a suggestion for what might be missing, based on the make output?

Thank you!

[root@flagstaff SHTOOLS-3.1]# make
make -C src -f Makefile all F95=gfortran F95FLAGS="-m64 -fPIC -O3 -ffast-math"
make[1]: Entering directory `/root/work/SHTOOLS-3.1/src'
gfortran -c -m64 -fPIC -O3 -ffast-math SHTOOLS.f95
gfortran -c -m64 -fPIC -O3 -ffast-math CilmPlus.f95
gfortran -c -m64 -fPIC -O3 -ffast-math CilmMinus.f95
gfortran -c -m64 -fPIC -O3 -ffast-math ComputeDG82.f95
gfortran -c -m64 -fPIC -O3 -ffast-math ComputeDm.f95
gfortran -c -m64 -fPIC -O3 -ffast-math DHaj.f95
gfortran -c -m64 -fPIC -O3 -ffast-math djpi2.f95
gfortran -c -m64 -fPIC -O3 -ffast-math FFTW3.f95
gfortran -c -m64 -fPIC -O3 -ffast-math BAtoHilm.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGrid2D.f95
gfortran -c -m64 -fPIC -O3 -ffast-math GLQGridCoord.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGridPoint.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlanetsConstants.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlBar.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlBar_d1.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PLegendre.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PLegendreA.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PLegendreA_d1.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlmBar.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlmBar_d1.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlmIndex.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlmSchmidt.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlmSchmidt_d1.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlSchmidt.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlSchmidt_d1.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PreGLQ.f95
gfortran -c -m64 -fPIC -O3 -ffast-math Random.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHAdmitCorr.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHBias.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHBiasK.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHConvertCoef.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHFindLWin.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHLocalizedAdmitCorr.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHMultiply.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHMultiTaperCSE.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHMultiTaperSE.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHPowerSpectra.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHRead.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHReadJPL.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHReturnTapersM.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHRotateCoef.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHRotateRealCoef.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SphericalCapCoef.f95
gfortran -c -m64 -fPIC -O3 -ffast-math Wigner3j.f95
gfortran -c -m64 -fPIC -O3 -ffast-math DownContFilter.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHRead2.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGeoidGrid.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeCircleCoord.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHMTCouplingMatrix.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHReturnTapers.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHSjkPG.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlON.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlON_d1.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlmON.f95
gfortran -c -m64 -fPIC -O3 -ffast-math PlmON_d1.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHConfidence.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHMagPowerSpectra.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHPowerSpectraC.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHBiasAdmitCorr.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHCilmToVector.f95
gfortran -c -m64 -fPIC -O3 -ffast-math YilmIndexVector.f95
gfortran -c -m64 -fPIC -O3 -ffast-math ComputeDMap.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHReturnTapersMap.f95
gfortran -c -m64 -fPIC -O3 -ffast-math Curve2Mask.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeEllipseCoord.f95
gfortran -c -m64 -fPIC -O3 -ffast-math CilmPlusRhoH.f95
gfortran -c -m64 -fPIC -O3 -ffast-math CilmMinusRhoH.f95
gfortran -c -m64 -fPIC -O3 -ffast-math BAtoHilmRhoH.f95
gfortran -c -m64 -fPIC -O3 -ffast-math NormalGravity.f95
gfortran -c -m64 -fPIC -O3 -ffast-math EigValSym.f95
gfortran -c -m64 -fPIC -O3 -ffast-math EigValVecSym.f95
gfortran -c -m64 -fPIC -O3 -ffast-math EigValVecSymTri.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHExpandLSQ.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHMTDebias.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHMTVarOpt.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGridDH.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGridDHC.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGridGLQ.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGridGLQC.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHGLQ.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHExpandDH.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHExpandDHC.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHExpandGLQ.f95
gfortran -c -m64 -fPIC -O3 -ffast-math SHExpandGLQC.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGravGradGridDH.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeGravGridDH.f95
gfortran -c -m64 -fPIC -O3 -ffast-math MakeMagGridDH.f95

COMPILATION OF SOURCE FILES SUCCESSFUL.

ar -r ../lib/libSHTOOLS.a CilmPlus.o CilmMinus.o ComputeDG82.o ComputeDm.o DHaj.o
djpi2.o FFTW3.o BAtoHilm.o MakeGrid2D.o GLQGridCoord.o MakeGridPoint.o
PlanetsConstants.o PlBar.o PlBar_d1.o PLegendre.o PLegendreA.o PLegendreA_d1.o
PlmBar.o PlmBar_d1.o PlmIndex.o PlmSchmidt.o PlmSchmidt_d1.o PlSchmidt.o
PlSchmidt_d1.o PreGLQ.o Random.o SHAdmitCorr.o SHBias.o SHBiasK.o SHConvertCoef.o
SHFindLWin.o SHLocalizedAdmitCorr.o SHMultiply.o SHMultiTaperCSE.o
SHMultiTaperSE.o SHPowerSpectra.o SHRead.o SHReadJPL.o SHReturnTapersM.o
SHRotateCoef.o SHRotateRealCoef.o SHTOOLS.o SphericalCapCoef.o Wigner3j.o
DownContFilter.o SHRead2.o MakeGeoidGrid.o MakeCircleCoord.o SHMTCouplingMatrix.o
SHReturnTapers.o SHSjkPG.o PlON.o PlON_d1.o PlmON.o PlmON_d1.o SHConfidence.o
SHMagPowerSpectra.o SHPowerSpectraC.o SHBiasAdmitCorr.o SHCilmToVector.o
YilmIndexVector.o ComputeDMap.o SHReturnTapersMap.o Curve2Mask.o
MakeEllipseCoord.o CilmPlusRhoH.o CilmMinusRhoH.o BAtoHilmRhoH.o NormalGravity.o
EigValSym.o EigValVecSym.o EigValVecSymTri.o SHExpandLSQ.o SHMTDebias.o
SHMTVarOpt.o MakeGridDH.o MakeGridDHC.o MakeGridGLQ.o MakeGridGLQC.o SHGLQ.o
SHExpandDH.o SHExpandDHC.o SHExpandGLQ.o SHExpandGLQC.o MakeGravGradGridDH.o
MakeGravGridDH.o MakeMagGridDH.o
ar: creating ../lib/libSHTOOLS.a

ranlib  ../lib/libSHTOOLS.a

CREATION OF STATIC LIBRARY SUCCESSFUL.

LIBRARY AND MODULE FILES MOVED TO ../lib and ../modules

ARCHIVE SUCCESSFULLY CREATED
make[1]: Leaving directory `/root/work/SHTOOLS-3.1/src'

MAKE OF FORTRAN COMPONENT SUCCESSFUL!

f2py --quiet -Imodules -Llib --f90flags="-m64 -fPIC -O3 -ffast-math" \
                -c src/pyshtools.pyf src/PythonWrapper.f95\
                -lSHTOOLS -lfftw3 -lm -llapack  -lblas
sortvarnames: failed to compute dependencies because of cyclic dependencies
between w, w_d0
Could not locate executable g77
Could not locate executable f77
Could not locate executable ifort
Could not locate executable ifc
Could not locate executable lf95
Could not locate executable pgf90
Could not locate executable pgf77
Could not locate executable f90
Found executable /usr/bin/f95
Could not locate executable fort
Could not locate executable efort
Could not locate executable efc
Found executable /usr/bin/gfortran
/usr/bin/ld: cannot find -lfftw3
collect2: ld returned 1 exit status
/usr/bin/ld: cannot find -lfftw3
collect2: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -Wall -shared
/tmp/tmpyqId0L/tmp/tmpyqId0L/src.linux-x86_64-2.4/src/_SHTOOLSmodule.o
/tmp/tmpyqId0L/tmp/tmpyqId0L/src.linux-x86_64-2.4/fortranobject.o
/tmp/tmpyqId0L/src/PythonWrapper.o
/tmp/tmpyqId0L/tmp/tmpyqId0L/src.linux-x86_64-2.4/src/_SHTOOLS-f2pywrappers.o
-Llib -lSHTOOLS -lfftw3 -lm -llapack -lblas -lgfortran -o ./_SHTOOLS.so" failed
with exit status 1
make: *** [all] Error 1

**Comment by sachu92** [comment]
/usr/bin/ld: cannot find -lfftw3 

It says you do not have fftw3 library installed or it is not linked correctly.

**Comment by MMesch** [comment]
Could you check if you have the file libfftw3.so  somewhere on your machine (e.g. under /usr/local/lib)?

**Comment by elmerehbi** [comment]
Which Linux are you running? I had difficulties 2 weeks ago and now it seems fixed by installed fftw from the Ubuntu (my Linux distro) repo: libfftw3-dev

**Comment by Mstabdelbaky** [comment]
Hi All,
I try to install SHTOOLS in Linux Ubuntu. I start for the first step. I installed Gfortran and Updated Python. then i installed FFTW correctly with the help from here. now i install LAPACK package but i get that error.
![lapack error](https://cloud.githubusercontent.com/assets/16101683/11734815/4751e924-9fc3-11e5-89df-e4e5e648c56f.png)

**Comment by sachu92** [comment]
@Mstabdelbaky You have to install BLAS before installing LAPACK.

**Comment by Mstabdelbaky** [comment]
Ok. Should i uninstall LAPACK first or just install BLAS then LAPACK?

**Comment by sachu92** [comment]
@Mstabdelbaky BLAS then LAPACK

**Comment by Mstabdelbaky** [comment]
I installed BLAS
![blas](https://cloud.githubusercontent.com/assets/16101683/11737516/8b42b9aa-9fe2-11e5-9650-5fa250e6a5d8.png)
then i installed LAPACK and give me this error
![lapack](https://cloud.githubusercontent.com/assets/16101683/11737532/ab264e12-9fe2-11e5-8712-21fe59589ab1.png)

**Comment by sachu92** [comment]
Can you try installing BLAS and LAPACK using the package manager?
sudo apt-get install libblas-dev liblapack-dev

**Comment by Mstabdelbaky** [comment]
![blas and lapack](https://cloud.githubusercontent.com/assets/16101683/11739263/d77baae2-9ff2-11e5-9e66-1ca94799d05f.png)

is that ok?
can i try to install SHTOOLS now? or i need to install something else?

**Comment by sachu92** [comment]
Try installing SHTOOLS. It will tell you if it needs anything more.

**Comment by Mstabdelbaky** [comment]
![shtools1](https://cloud.githubusercontent.com/assets/16101683/11739653/aed0744e-9ff5-11e5-8f37-6188296bf48e.png)

is that ok? can i make the test now?

**Comment by MarkWieczorek** [comment]
I'm going to close this issue as it appears to be resolved. If any of the information in the above thread is useful for platform specific installations, I suggest that someone add this to the SHTOOLS wiki on github.
