### ISSUE TITLE
SHTOOLS Installation

### ISSUE THREAD

**Issue by Mstabdelbaky** [SHTOOLS/SHTOOLS#7]
I would to use SHTOOLS programs. when i installed the SHTOOLS, i got this error and i don't know the reasons. I wish if you can help me to solve this error.
Thank you.
![shtools p1](https://cloud.githubusercontent.com/assets/16101683/11565640/80453088-99e7-11e5-885b-5aeabf795eca.png)

Best Regards,
Mostafa

**Comment by MMesch** [comment]
Hi Mostafa,

apparently there is a problem linking fftw3 to the SHTOOLS library. The Error msg says that you should recompile it with the option fPIC (position independent code) . Could you try this? Did you compile it yourself or did you use a package from the operating system?

Matthias

**Comment by Mstabdelbaky** [comment]
Hi Matthias,
Thank you for your help. I downloaded it from this website "http://www.fftw.org/"
then i installed it by using these steps
./configure
make
make install
then when i checked the usr/local/lib/
i founded it (libfftw3.a)
what should i do now?

Best regards,
Mostafa

**Comment by MMesch** [comment]
Hi Mostafa,

I see that you seem to be using ubuntu. Can you remove the fftw3 file in usr/local/lib and then install the distribution version with:

    sudo apt-get install libfftw3-dev

Otherwise, you can do

    ./configure --enable-shared

instead of

    ./configure

and then do the rest.

Please tell me if it works!

**Comment by Mstabdelbaky** [comment]
Dear Matthias,
 I removed the libfftw3.a
then i used sudo apt-get install libfftw3-dev
then i go to SHTOOLS and write make
but still same error

**Comment by MMesch** [comment]
Can you check if you have libfftw3.so somewhere? I have for example:

    /usr/lib/libfftw3.so
    /usr/lib/libfftw3.so.3
    /usr/lib/libfftw3.so.3.3.0

**Comment by Mstabdelbaky** [comment]
Hi Matthias,
can you help me to install it from begging?
1- setup virtualbox ( i have already virtualbox)
2- i will install Linux (ubuntu-14.04.3-desktop-amd64)
3- to install gfortran
sudo apt-get install gfortran
4- to update python
sudo apt-get install python
5-check about f2py is installed or not by open "terminal" and write "f2py"
if not installed then write in terminal "sudo apt-get install python-numpy" 
then install anothe program by written "sudo apt-get install python-dev"
6- install FFTW
./configure --enable-shared
make
make install
7- install BLAS
download it from this website "http://www.netlib.org/blas/"
then open the terminal and write
make
8- install LAPACK
change the file name from make.inc.example to make.inc
then open the terminal and write
make
9- go inside the BLAS folder and change the name of the liburary to libblas.a
10- open the "terminal" and write su then copy the files libblas.a, from their folder to computer/usr/local/lib (3 files)
11- change the word tcsh to bash in the file makefile (line 105)
12- change the word tcsh to bash in the file Makefile inside src 
13- copy the folder of SHTOOLS in computer/usr/local
14- make

is that ok?

Best Regards, 
Mostafa

**Comment by Mstabdelbaky** [comment]
no i don't have

**Comment by MMesch** [comment]
Hi Mostafa,

try to recompile fftw3 with the  --enable-shared option. You should get the file libfftw3.so under:
    fftw-3.3.4/.libs/ibfftw3.so
if you type
    sudo make install
afterwards it puts this file in
    /usr/local/lib
then you can try to reinstall as you did before.

**Comment by Mstabdelbaky** [comment]
I don't have the folder libs inside the folder fftw-3.4.4

**Comment by MMesch** [comment]
the folder is hidden. It is called .libs with the dot in front

**Comment by Mstabdelbaky** [comment]
![3](https://cloud.githubusercontent.com/assets/16101683/11591091/cbcdd17a-9a9d-11e5-9a71-f877e235c6ee.png)

**Comment by MMesch** [comment]
OK. In this folder do:

    ./compile --enable-shared
    make

then type

    cd .lib
    ls -la

(don't forget the dot)

**Comment by Mstabdelbaky** [comment]
![4](https://cloud.githubusercontent.com/assets/16101683/11591707/9a63353a-9aa2-11e5-9fc2-635b7372b7d2.png)

**Comment by MMesch** [comment]
I am sorry, I meat to say:

    ./configure --enable-shared
    make

my bad! Thinking too much about compilation :)

**Comment by Mstabdelbaky** [comment]
it's ok thank you for your help 
![5](https://cloud.githubusercontent.com/assets/16101683/11592933/22889354-9aaa-11e5-8853-8a628a7e50c5.png)

**Comment by MMesch** [comment]
OK. In my case, it generates these files:
    >> cd ./lib
    >> ls 
    libfftw3.a  libfftw3.la  libfftw3.lai  libfftw3.so  libfftw3.so.3  libfftw3.so.3.4.4

These should be there if the compilation works correctly. If you type

    make install

they should be moved to /usr/local/lib (default)

SHTOOLS should be able to link to the libfftw3.so library then.

**Comment by Mstabdelbaky** [comment]
Dear Matthias,
I download Ubuntu again and i start from Zero
I installed Gfortran
i updated Python
i used sudo apt-get install python-numpy and sudo apt-get install python-dev
i downloaded FFTW, BLAS, LAPACK and SHTOOLS
I installed FFTW as you told me using ./configure --enable-shared
make
make install
and i get these files:
![fftw](https://cloud.githubusercontent.com/assets/16101683/11606424/0596da96-9b2a-11e5-803e-594ed91f2a4d.png)
should i replace all of them to  /usr/local/lib? or that's ok
libfftw3.a  libfftw3.la  libfftw3.lai  libfftw3.so  libfftw3.so.3  libfftw3.so.3.4.4

Best Regards,
Mostafa

**Comment by MMesch** [comment]
OK perfect. Try:

    sudo make install

now! Then try:

    sudo apt-get install python-pip python-dev build-essential 
    sudo pip install --upgrade pip 
    sudo pip install numpy
    sudo pip install matplotlib
    sudo pip install scipy

Then recompile SHTOOLS. You could also use anaconda instead of the normal python distribution. It simplifies things a lot. You can get it here:  https://www.continuum.io/downloads

check whether you can import numpy, scipy and matplotlib by opening python and running in the console:

>>> import numpy
>>> import matplotlib
>>> import scipy

Then see whether SHTOOLS compiles without error. If yes, try to go to the root SHTOOLS folder and try in python:

>>> import pyshtools

Good luck!

Matthias

**Comment by Mstabdelbaky** [comment]
after FFTW, i try to install LAPACK but i get that error
i change the file name from make.inc.example to make.inc
then make
![lapack error](https://cloud.githubusercontent.com/assets/16101683/11608275/509ee590-9b6d-11e5-97c0-ae0d995953cc.png)

**Comment by elmerehbi** [comment]
I was having similar difficulties (with libfftw). I already had fortran & LAPACK and the rest installed. So I just fixed fftw by installing it from the Ubuntu repo (libfftw3-dev) as you suggest in the comments. It fixed it and I just tested with the Python examples and the work. And I was able to import pyshtools.

Mostafa, I hope things are not messed up. I will instruct you here on a way that might work. I cannot guarantee it (and I suggest you wait for Matthias's feedback):

Try each of the following in the terminal one at a time.
```
apt-cache show libblas3gf
apt-cache show liblapack
apt-cache show libfftw3-dev
```
Do they return a "Unable to locate packages"? I do not suggest you compile them from source as it can be quite a hassle. I suggest you use the command I once used on Ubuntu 10 ( and then on Ubuntu 12) to get them (I was [compiling the Muesli Fortran](http://elmerehbi.com/2012/05/18/compiling-muesli-fortran/) if you wish to know):

```
sudo apt-get install libblas-dev liblapack-dev g++ gfortran libfftw3-dev
```
Then try to compile SHTOOLs:
```
cd /path-to-directory/
make
```
If you do not get any error then it was successful. You can now do one (or both) of the tests:

```
make fortran-tests
make python-tests
````

Hope this helps. if you get an error somewhere just share it as you've been doing.

Good luck

**Comment by MMesch** [comment]
@elmerehbi  First of all thank you for your help! Then: anaconda/shtools installation is going to be cleaner once we add a 'real' setup.py . Then you can use the pip command to install SHTOOLS directly into the anaconda directory.

it is dangerous doing:

    sys.path.append('/usr/local/lib/python2.7/site-packages')

because you are not only adding pyshtools but all the other modules under this path as well. If you import matplotlib and you have two versions in your path, one from the standard python and one from anaconda, it will ultimately mess up your installation. I would suggest to keep the pyshtools folder separate if you are using anaconda.

If you want to have it available automatically, you can either move the pyshtools folder into any
folder that anaconda watches. To find out which ones anaconda sees type:

    import sys
    print sys.path

But I agree that at some point someone ( :) ) needs to write a setup.py !

**Comment by elmerehbi** [comment]
@MMesch Thanks for the feedback. I didn't like the sys.path thing. I took your word and copied the folder and it works now :)

I am new to Python and I am figuring out the tools to work with spherical harmonics for a project I am working on so I am not sure I am the best to help with this. If you can point me to some useful resources I might look into it and see if I can help.

And thanks for the Python wrappers :)

**Comment by MMesch** [comment]
Hi Mostafa,

see #2  where we should discuss the setup.py
