### ISSUE TITLE
SHTOOLS doesn't load with Numpy 1.9.3-py27_0

### ISSUE THREAD

**Issue by elmerehbi** [SHTOOLS/SHTOOLS#8]
Earlier I installed the mayavi module which required that I downgrade numpy from 1.10 to 1.9.3
After that I tried importing shtools after I imported numpy and it resulted in

```
ImportError: cannot import name _SHTOOLS
```

When numpy was not imported and I tried importing SHTOOLS I got an ImportError regarding numpy (by shtools).

I upgraded numpy again to 10.3 and things things were fixed.

Thought I'd open an issue about it.

**Comment by MMesch** [comment]
Thank's for reporting. I personally have mayavi 4.0.0 running fine with numpy 1.10.1 . Why do you think that downgrading numpy is necessary?

**Comment by elmerehbi** [comment]
@MMesch It not my thinking. Anaconda's installation did the downgrade. then I re-installed numpy to upgrade it again.

**Comment by MMesch** [comment]
Ok. I'll have a look into this at some point. Thanks for reporting in any
case!

**Comment by MMesch** [comment]
@elmerehbi I had the same issue now. I managed to get around this by installing mayavi manually but it is not very comfortable. I think this problem has to be fixed by the anaconda/mayavi development teams

**Comment by elmerehbi** [comment]
@MMesch That's what I had on mind. I just wanted to raise your attention to it.

**Comment by MMesch** [comment]
Hi @elmerehbi . I managed to get mayavi working with anaconda using the environment variable:

export QT_API=pyqt

Maybe this can help you as well?

**Comment by QuLogic** [comment]
It seems like you build `pyshtools` against one NumPy and downgraded it. It's pretty likely that these two versions are not ABI compatible, so that's why it wouldn't load. You need to rebuild `pyshtools` after downgrading NumPy. I can use NumPy 1.9 without any problem if built for it.

**Comment by MMesch** [comment]
It seems to work. I'll close this because we don't have any further information ...
