### ISSUE TITLE
version 4.1

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#83]
- [ ] Add option to plot projected grids using the cartopy backend
- [ ] Add optional `axes` argument for all plotting routines, so that plots can be drawn on an already existing figures.
- [ ] Provide native python functions for all routines in the subpackage `shio`.
- [ ] Provide a native python function to replace `SHMagPowerL` and `SHMagPowerSpectrum`.
- [ ] Provide support for installing via conda.
- [ ] Create new classes `SHGrav` and `SHMag` for working with gravity and magnetic field data.
- [ ] Reorganize the python tutorials to minimize duplication and aid ease of use.
- [ ] Remove annoying warnings when compiling the fortran source code via `pip install -v`.

**Comment by ioshchepkov** [comment]
- [ ] Add Ellipsoid class as inheritance from proj.Geod class
- [ ] Add coordinate transformations routines
- [ ] Add LevelEllipsoid class for the normal gravity field

**Comment by leouieda** [comment]
@MarkWieczorek one way of organizing TODOs for a new release on github is through their milestones feature: https://github.com/SHTOOLS/SHTOOLS/milestones

You can assign issues to a specific milestone (v4.1 in your case) and a nice progress bar is filled when each issue is closed. It's a good way of keeping track of what you want to have done for a release.

I've been using this for Fatiando lately and I quite like it: https://github.com/fatiando/fatiando/milestone/8

**Comment by MarkWieczorek** [comment]
I have added all these tasks as milestones.
