### ISSUE TITLE
division by zero in sub Wigner3j

### ISSUE THREAD

**Issue by MikaelBeuthe** [SHTOOLS/SHTOOLS#87]
lines 341-342 of Wigner3j.f95:
if (abs(wnmid/wl(jindex(jmid-1))) < 1.d-6 .and. wl(jindex(jmid-1)) /= 0.0d0) then
For some parameters (try j2=j3=2; m1=m2=m3=0), division by zero in the first test in the 'if condition' causes program to crash if compiled with gfortran -ffpe-trap=zero
The tests in the 'if condition' should be reversed so that the 2nd test is not done if the 1st is not true:
if (wl(jindex(jmid-1)) /= 0.0d0 .and. abs(wnmid/wl(jindex(jmid-1))) < 1.d-6) then

**Comment by MarkWieczorek** [comment]
The PR should fix it: #88

Let me know if there are any other problems. I'll merge this with develop in about a day. Thanks!
