### ISSUE TITLE
PLegendre & PLegendreA crash kernel if z > 1

### ISSUE THREAD

**Issue by elmerehbi** [SHTOOLS/SHTOOLS#9]
I am reporting the crash caused by using z > 1 for PLegendre & PLegendreA:

```
Error --- PLegendreA
 ABS(Z) must be less than or equal to 1.
 Input value is    2.0000000000000000
```

It should be able to report the error to the user but not crash the kernel. Ipython notebook reports the kernel failed and will restart while ipython in the terminal completely crashes.

**Comment by MMesch** [comment]
This is unfortunately not possible right now because the Exception is thrown by Fortran. I agree though that it would be nice to change this!

**Comment by MarkWieczorek** [comment]
I'm going to close this issue. As much as we would like to fix this, this is a fortran-python issue. If you know how to do this better, please let us know.
