### ISSUE TITLE
Different between CilmPlus and CilmMinus

### ISSUE THREAD

**Issue by banlidawang** [SHTOOLS/SHTOOLS#94]
Dear Prof. Wieczorek
I found those two subroutine in src file.
I think it represented the eq(10) and eq(12) in (Wieczorek and Phillips 1998)
My question is that when I about to calculate bouguer correction, which subroutine should I choose.
Or should I use both of them and added them together?
Or just one of those subroutine, depending on my reference radius?
The fortran sample MarsCrustalThickness use only the CilmPlus to calculate bouguer correction

**Comment by MarkWieczorek** [comment]
If you want to calculate the gravity field outside of the body you use `cilmplus`. Inside the body use `cilmminus`.
